//*
// # Block Header
// The block header reports information required to correctly process a block.
// This includes versions, block number, and algorithms used.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/block_header.proto

package output

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A Block Header.
//
// Each block in the block stream SHALL begin with a block header.<br/>
// The block header SHALL provide the base minimum information needed to
// correctly interpret and process that block, or stop processing
// if appropriate.<br/>
// The block header MUST describe, at minimum, the following items.
//   - The version of the block stream data
//   - The block number
//   - The hash of the previous block
//   - The hash algorithm used to generate the block hash
//
// All fields of this message are REQUIRED, with the exception that
// `hash_algorithm` MAY be _transmitted_ as a default value to improve
// data efficiency.
type BlockHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A version of the HAPI specification.<br/>
	// This is the API version that was used to serialize the block.
	HapiProtoVersion *common.SemanticVersion `protobuf:"bytes,1,opt,name=hapi_proto_version,json=hapiProtoVersion,proto3" json:"hapi_proto_version,omitempty"`
	// *
	// A version of the consensus node software.<br/>
	// This is the software version that executed the transactions
	// within this block.
	SoftwareVersion *common.SemanticVersion `protobuf:"bytes,2,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	// *
	// A block number for this block.
	// <p>
	// This value MUST be exactly `1` more than the previous block.<br/>
	// Client systems SHOULD optimistically reject any block with a gap or
	// reverse in `number` sequence, and MAY assume the block stream has
	// encountered data loss, data corruption, or unauthorized modification.
	Number uint64 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	// *
	// A block root hash for the previous block.
	// <p>
	// This value MUST match the block merkle tree root hash of the previous
	// block in the block stream.<br/>
	// This value SHALL be empty for the genesis block, and SHALL NOT be empty
	// for any other block.<br/>
	// Client systems SHOULD optimistically reject any block with a
	// `previous_block_proof_hash` that does not match the block hash of the
	// previous block and MAY assume the block stream has encountered data
	// loss, data corruption, or unauthorized modification.
	// <p>
	// The process for computing a block hash is somewhat complex, and involves
	// creating a "virtual" merkle tree to obtain the root merkle hash of
	// that virtual tree.<br/>
	// The merkle tree SHALL have a 4 part structure with 2 internal nodes,
	// structured in a strictly binary tree.
	// <ul>
	//
	//	<li>The merkle tree root SHALL be the parent of both
	//	    internal nodes.
	//	  <ol>
	//	    <li>The first "internal" node SHALL be the parent of the
	//	        two "left-most" nodes.
	//	      <ol>
	//	        <li>The first leaf MUST be the previous block hash, and is a
	//	            single 48-byte value.</li>
	//	        <li>The second leaf MUST be the root of a, strictly binary,
	//	            merkle tree composed of all "input" block items in
	//	            the block.<br/>
	//	            Input items SHALL be transactions, system transactions,
	//	            and events.<br/>
	//	            Leaf nodes in this subtree SHALL be ordered in the
	//	            same order that the block items are encountered
	//	            in the stream.</li>
	//	      </ol>
	//	    </li>
	//	    <li>The second "internal" node SHALL be the parent of the
	//	        two "right-most" nodes.
	//	      <ol>
	//	        <li>The third leaf MUST be the root of a, strictly binary,
	//	            merkle tree composed of all "output" block items in
	//	            the block.<br/>
	//	            Output items SHALL be transaction result, transaction
	//	            output, and state changes.<br/>
	//	            Leaf nodes in this subtree SHALL be ordered in the
	//	            same order that the block items are encountered
	//	            in the stream.</li>
	//	        <li>The fourth leaf MUST be the merkle tree root hash for
	//	            network state at the end of the block, and is a single
	//	            48-byte value.</li>
	//	      </ol>
	//	    </li>
	//	  </ol>
	//	</li>
	//	<li>The block hash SHALL be the SHA-384 hash calculated for the root
	//	    of this merkle tree.</li>
	//
	// </ul>
	PreviousBlockHash []byte `protobuf:"bytes,4,opt,name=previous_block_hash,json=previousBlockHash,proto3" json:"previous_block_hash,omitempty"`
	// *
	// A consensus timestamp for the start of this block.
	// <p>
	// This SHALL be the timestamp assigned by the hashgraph consensus
	// algorithm to the first transaction of this block.
	FirstTransactionConsensusTime *common.Timestamp `protobuf:"bytes,5,opt,name=first_transaction_consensus_time,json=firstTransactionConsensusTime,proto3" json:"first_transaction_consensus_time,omitempty"`
	// *
	// A hash algorithm used for this block, including the block proof.
	// <p>
	// This SHOULD always be `SHA2_384`, currently.
	HashAlgorithm common.BlockHashAlgorithm `protobuf:"varint,6,opt,name=hash_algorithm,json=hashAlgorithm,proto3,enum=proto.BlockHashAlgorithm" json:"hash_algorithm,omitempty"`
	// *
	// A version for the network address book.<br/>
	// The address book version is needed to determine the correct public
	// key(s) to use to validate block signatures and state proofs.
	// <p>
	// This MUST be the version of the address book that signed this
	// block.
	AddressBookVersion *common.SemanticVersion `protobuf:"bytes,7,opt,name=address_book_version,json=addressBookVersion,proto3" json:"address_book_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_stream_output_block_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_block_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_stream_output_block_header_proto_rawDescGZIP(), []int{0}
}

func (x *BlockHeader) GetHapiProtoVersion() *common.SemanticVersion {
	if x != nil {
		return x.HapiProtoVersion
	}
	return nil
}

func (x *BlockHeader) GetSoftwareVersion() *common.SemanticVersion {
	if x != nil {
		return x.SoftwareVersion
	}
	return nil
}

func (x *BlockHeader) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockHeader) GetPreviousBlockHash() []byte {
	if x != nil {
		return x.PreviousBlockHash
	}
	return nil
}

func (x *BlockHeader) GetFirstTransactionConsensusTime() *common.Timestamp {
	if x != nil {
		return x.FirstTransactionConsensusTime
	}
	return nil
}

func (x *BlockHeader) GetHashAlgorithm() common.BlockHashAlgorithm {
	if x != nil {
		return x.HashAlgorithm
	}
	return common.BlockHashAlgorithm(0)
}

func (x *BlockHeader) GetAddressBookVersion() *common.SemanticVersion {
	if x != nil {
		return x.AddressBookVersion
	}
	return nil
}

var File_stream_output_block_header_proto protoreflect.FileDescriptor

const file_stream_output_block_header_proto_rawDesc = "" +
	"\n" +
	" stream/output/block_header.proto\x12#com.hedera.hapi.block.stream.output\x1a\x11basic_types.proto\x1a\x0ftimestamp.proto\"\xc5\x03\n" +
	"\vBlockHeader\x12D\n" +
	"\x12hapi_proto_version\x18\x01 \x01(\v2\x16.proto.SemanticVersionR\x10hapiProtoVersion\x12A\n" +
	"\x10software_version\x18\x02 \x01(\v2\x16.proto.SemanticVersionR\x0fsoftwareVersion\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x04R\x06number\x12.\n" +
	"\x13previous_block_hash\x18\x04 \x01(\fR\x11previousBlockHash\x12Y\n" +
	" first_transaction_consensus_time\x18\x05 \x01(\v2\x10.proto.TimestampR\x1dfirstTransactionConsensusTime\x12@\n" +
	"\x0ehash_algorithm\x18\x06 \x01(\x0e2\x19.proto.BlockHashAlgorithmR\rhashAlgorithm\x12H\n" +
	"\x14address_book_version\x18\a \x01(\v2\x16.proto.SemanticVersionR\x12addressBookVersionBm\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z=github.com/cordialsys/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_block_header_proto_rawDescOnce sync.Once
	file_stream_output_block_header_proto_rawDescData []byte
)

func file_stream_output_block_header_proto_rawDescGZIP() []byte {
	file_stream_output_block_header_proto_rawDescOnce.Do(func() {
		file_stream_output_block_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_block_header_proto_rawDesc), len(file_stream_output_block_header_proto_rawDesc)))
	})
	return file_stream_output_block_header_proto_rawDescData
}

var file_stream_output_block_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stream_output_block_header_proto_goTypes = []any{
	(*BlockHeader)(nil),            // 0: com.hedera.hapi.block.stream.output.BlockHeader
	(*common.SemanticVersion)(nil), // 1: proto.SemanticVersion
	(*common.Timestamp)(nil),       // 2: proto.Timestamp
	(common.BlockHashAlgorithm)(0), // 3: proto.BlockHashAlgorithm
}
var file_stream_output_block_header_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.block.stream.output.BlockHeader.hapi_proto_version:type_name -> proto.SemanticVersion
	1, // 1: com.hedera.hapi.block.stream.output.BlockHeader.software_version:type_name -> proto.SemanticVersion
	2, // 2: com.hedera.hapi.block.stream.output.BlockHeader.first_transaction_consensus_time:type_name -> proto.Timestamp
	3, // 3: com.hedera.hapi.block.stream.output.BlockHeader.hash_algorithm:type_name -> proto.BlockHashAlgorithm
	1, // 4: com.hedera.hapi.block.stream.output.BlockHeader.address_book_version:type_name -> proto.SemanticVersion
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_stream_output_block_header_proto_init() }
func file_stream_output_block_header_proto_init() {
	if File_stream_output_block_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_block_header_proto_rawDesc), len(file_stream_output_block_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_block_header_proto_goTypes,
		DependencyIndexes: file_stream_output_block_header_proto_depIdxs,
		MessageInfos:      file_stream_output_block_header_proto_msgTypes,
	}.Build()
	File_stream_output_block_header_proto = out.File
	file_stream_output_block_header_proto_goTypes = nil
	file_stream_output_block_header_proto_depIdxs = nil
}
