//*
// # Consensus Service
// Block stream messages that report the results of transactions handled
// by the `Consensus` service.
//
// ### Topic Running Hash Calculation
// Submitted messages include a topic running hash. This value has changed
// over time, with the known versions detailed in the `RunningHashVersion`
// enumeration. The running hash version SHALL NOT be transmitted in the
// Block Stream, however, as it is a fixed value that can only be changed
// with a new release of consensus node software following a HIP to update
// the specification, so repeating that fixed value in the block stream is
// wasteful and unnecessary.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/consensus_service.proto

package output

import (
	_ "github.com/hashgraph/hedera-protobufs-go/services"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A version of the topic running hash.
//
// The inputs to the topic running hash have changed over time.
// This is tracked in earlier record streams as an integer. For the
// block stream we chose to use an enumeration for both efficiency
// and clarity. Placing the most recent, and most common/highest
// volume, version as `0` reduces the serialized size of this message
// by not serializing that default value.
//
// <hr style="margin: 0.2em 5em 0.2em 5em; height: 0.5em;
//
//	border-style: solid none solid none; border-width: 2px;"/>
//
// The topic running hash is a 48-byte value that is the output
// of a hash digest with input data determined by the value of
// the `topic_running_hash_version` field.<br/>
// All new transactions SHALL use `topic_running_hash_version`
// `WITH_MESSAGE_DIGEST_AND_PAYER`.<br/>
type RunningHashVersion int32

const (
	// *
	// The most recent version.
	// <p>
	// This version SHALL include, in order
	// <ol>
	//
	//	<li>The previous running hash of the topic (48 bytes)</li>
	//	<li>The `topic_running_hash_version` field (8 bytes)</li>
	//	<li>The payer account's shard (8 bytes)</li>
	//	<li>The payer account's realm (8 bytes)</li>
	//	<li>The payer account's number (8 bytes)</li>
	//	<li>The topic's shard (8 bytes)</li>
	//	<li>The topic's realm (8 bytes)</li>
	//	<li>The topic's number (8 bytes)</li>
	//	<li>The number of seconds since the epoch when the
	//	    `ConsensusSubmitMessage` reached consensus (8 bytes)</li>
	//	<li>The number of nanoseconds within the second when the
	//	    `ConsensusSubmitMessage` reached consensus (4 bytes)</li>
	//	<li>The `topic_sequence_number` field (8 bytes)</li>
	//	<li>The output of a SHA-384 digest of the message bytes from the
	//	    `ConsensusSubmitMessage` (48 bytes)</li>
	//
	// </ol>
	RunningHashVersion_WITH_MESSAGE_DIGEST_AND_PAYER RunningHashVersion = 0
	// *
	// An earlier version.
	// <p>
	// This version SHALL include, in order
	// <ol>
	//
	//	<li>The previous running hash of the topic (48 bytes)</li>
	//	<li>The `topic_running_hash_version` field (8 bytes)</li>
	//	<li>The topic's shard (8 bytes)</li>
	//	<li>The topic's realm (8 bytes)</li>
	//	<li>The topic's number (8 bytes)</li>
	//	<li>The number of seconds since the epoch when the
	//	    `ConsensusSubmitMessage` reached consensus (8 bytes)</li>
	//	<li>The number of nanoseconds within the second when the
	//	    `ConsensusSubmitMessage` reached consensus (4 bytes)</li>
	//	<li>The `topic_sequence_number` field (8 bytes)</li>
	//	<li>The output of a SHA-384 digest of the message bytes from the
	//	    `ConsensusSubmitMessage` (48 bytes)</li>
	//
	// </ol>
	RunningHashVersion_WITH_MESSAGE_DIGEST RunningHashVersion = 1
	// *
	// The original version, used at genesis.
	// <p>
	// This version SHALL include, in order
	// <ol>
	//
	//	<li>The previous running hash of the topic (48 bytes)</li>
	//	<li>The topic's shard (8 bytes)</li>
	//	<li>The topic's realm (8 bytes)</li>
	//	<li>The topic's number (8 bytes)</li>
	//	<li>The number of seconds since the epoch when the
	//	    `ConsensusSubmitMessage` reached consensus (8 bytes)</li>
	//	<li>The number of nanoseconds within the second when the
	//	    `ConsensusSubmitMessage` reached consensus (4 bytes)</li>
	//	<li>The `topic_sequence_number` field (8 bytes)</li>
	//	<li>The message bytes from the `ConsensusSubmitMessage`
	//	    (variable)</li>
	//
	// </ol>
	RunningHashVersion_WITH_FULL_MESSAGE RunningHashVersion = 2
)

// Enum value maps for RunningHashVersion.
var (
	RunningHashVersion_name = map[int32]string{
		0: "WITH_MESSAGE_DIGEST_AND_PAYER",
		1: "WITH_MESSAGE_DIGEST",
		2: "WITH_FULL_MESSAGE",
	}
	RunningHashVersion_value = map[string]int32{
		"WITH_MESSAGE_DIGEST_AND_PAYER": 0,
		"WITH_MESSAGE_DIGEST":           1,
		"WITH_FULL_MESSAGE":             2,
	}
)

func (x RunningHashVersion) Enum() *RunningHashVersion {
	p := new(RunningHashVersion)
	*p = x
	return p
}

func (x RunningHashVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunningHashVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_output_consensus_service_proto_enumTypes[0].Descriptor()
}

func (RunningHashVersion) Type() protoreflect.EnumType {
	return &file_stream_output_consensus_service_proto_enumTypes[0]
}

func (x RunningHashVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunningHashVersion.Descriptor instead.
func (RunningHashVersion) EnumDescriptor() ([]byte, []int) {
	return file_stream_output_consensus_service_proto_rawDescGZIP(), []int{0}
}

// *
// Block Stream data for a `createTopic` transaction.
//
// This message SHALL NOT duplicate information already contained in the
// original transaction.
type CreateTopicOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicOutput) Reset() {
	*x = CreateTopicOutput{}
	mi := &file_stream_output_consensus_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicOutput) ProtoMessage() {}

func (x *CreateTopicOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_consensus_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicOutput.ProtoReflect.Descriptor instead.
func (*CreateTopicOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_consensus_service_proto_rawDescGZIP(), []int{0}
}

// *
// Block Stream data for a `updateTopic` transaction.
//
// This message SHALL NOT duplicate information already contained in the
// original transaction.
type UpdateTopicOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicOutput) Reset() {
	*x = UpdateTopicOutput{}
	mi := &file_stream_output_consensus_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicOutput) ProtoMessage() {}

func (x *UpdateTopicOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_consensus_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicOutput.ProtoReflect.Descriptor instead.
func (*UpdateTopicOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_consensus_service_proto_rawDescGZIP(), []int{1}
}

// *
// Block Stream data for a `deleteTopic` transaction.
//
// This message SHALL NOT duplicate information already contained in the
// original transaction.
type DeleteTopicOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicOutput) Reset() {
	*x = DeleteTopicOutput{}
	mi := &file_stream_output_consensus_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicOutput) ProtoMessage() {}

func (x *DeleteTopicOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_consensus_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicOutput.ProtoReflect.Descriptor instead.
func (*DeleteTopicOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_consensus_service_proto_rawDescGZIP(), []int{2}
}

// *
// Block Stream data for a `submitMessage` transaction.
//
// This message SHALL NOT duplicate information already contained in the
// original transaction.<br/>
// The actual topic running hash SHALL be present in a `StateChanges` block
// item, and is not duplicated here.
type SubmitMessageOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageOutput) Reset() {
	*x = SubmitMessageOutput{}
	mi := &file_stream_output_consensus_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageOutput) ProtoMessage() {}

func (x *SubmitMessageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_consensus_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageOutput.ProtoReflect.Descriptor instead.
func (*SubmitMessageOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_consensus_service_proto_rawDescGZIP(), []int{3}
}

var File_stream_output_consensus_service_proto protoreflect.FileDescriptor

const file_stream_output_consensus_service_proto_rawDesc = "" +
	"\n" +
	"%stream/output/consensus_service.proto\x12#com.hedera.hapi.block.stream.output\x1a\x11custom_fees.proto\"\x13\n" +
	"\x11CreateTopicOutput\"\x13\n" +
	"\x11UpdateTopicOutput\"\x13\n" +
	"\x11DeleteTopicOutput\"\x15\n" +
	"\x13SubmitMessageOutput*g\n" +
	"\x12RunningHashVersion\x12!\n" +
	"\x1dWITH_MESSAGE_DIGEST_AND_PAYER\x10\x00\x12\x17\n" +
	"\x13WITH_MESSAGE_DIGEST\x10\x01\x12\x15\n" +
	"\x11WITH_FULL_MESSAGE\x10\x02Bl\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z<github.com/hashgraph/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_consensus_service_proto_rawDescOnce sync.Once
	file_stream_output_consensus_service_proto_rawDescData []byte
)

func file_stream_output_consensus_service_proto_rawDescGZIP() []byte {
	file_stream_output_consensus_service_proto_rawDescOnce.Do(func() {
		file_stream_output_consensus_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_consensus_service_proto_rawDesc), len(file_stream_output_consensus_service_proto_rawDesc)))
	})
	return file_stream_output_consensus_service_proto_rawDescData
}

var file_stream_output_consensus_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stream_output_consensus_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stream_output_consensus_service_proto_goTypes = []any{
	(RunningHashVersion)(0),     // 0: com.hedera.hapi.block.stream.output.RunningHashVersion
	(*CreateTopicOutput)(nil),   // 1: com.hedera.hapi.block.stream.output.CreateTopicOutput
	(*UpdateTopicOutput)(nil),   // 2: com.hedera.hapi.block.stream.output.UpdateTopicOutput
	(*DeleteTopicOutput)(nil),   // 3: com.hedera.hapi.block.stream.output.DeleteTopicOutput
	(*SubmitMessageOutput)(nil), // 4: com.hedera.hapi.block.stream.output.SubmitMessageOutput
}
var file_stream_output_consensus_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_output_consensus_service_proto_init() }
func file_stream_output_consensus_service_proto_init() {
	if File_stream_output_consensus_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_consensus_service_proto_rawDesc), len(file_stream_output_consensus_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_consensus_service_proto_goTypes,
		DependencyIndexes: file_stream_output_consensus_service_proto_depIdxs,
		EnumInfos:         file_stream_output_consensus_service_proto_enumTypes,
		MessageInfos:      file_stream_output_consensus_service_proto_msgTypes,
	}.Build()
	File_stream_output_consensus_service_proto = out.File
	file_stream_output_consensus_service_proto_goTypes = nil
	file_stream_output_consensus_service_proto_depIdxs = nil
}
