//*
// # File Service
// Block stream messages that report the results of transactions handled
// by the `File` service.
//
// A `file` in Hedera is an arbitrary sequence of bytes and may be up to
// `1048576` total bytes. Files are used anywhere a transaction requires a
// large amount of data (anything that would not fit within the
// transaction size limit).
//
// Examples
//  - smart contract bytecode
//  - network configuration updates
//  - network fee schedules
//  - image files for NFTs
//  - property title documents
// There are many other uses; these examples are illustrative.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/file_service.proto

package output

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Block Stream data for a `fileAppend` transaction.
//
// This message SHALL NOT duplicate information already contained
// in the original transaction.
type AppendFileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendFileOutput) Reset() {
	*x = AppendFileOutput{}
	mi := &file_stream_output_file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendFileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendFileOutput) ProtoMessage() {}

func (x *AppendFileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendFileOutput.ProtoReflect.Descriptor instead.
func (*AppendFileOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_file_service_proto_rawDescGZIP(), []int{0}
}

// *
// Block Stream data for a `fileCreate` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type CreateFileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileOutput) Reset() {
	*x = CreateFileOutput{}
	mi := &file_stream_output_file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileOutput) ProtoMessage() {}

func (x *CreateFileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileOutput.ProtoReflect.Descriptor instead.
func (*CreateFileOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_file_service_proto_rawDescGZIP(), []int{1}
}

// *
// Block Stream data for a `fileDelete` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type DeleteFileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileOutput) Reset() {
	*x = DeleteFileOutput{}
	mi := &file_stream_output_file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileOutput) ProtoMessage() {}

func (x *DeleteFileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileOutput.ProtoReflect.Descriptor instead.
func (*DeleteFileOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_file_service_proto_rawDescGZIP(), []int{2}
}

// *
// Block Stream data for a `fileUpdate` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UpdateFileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileOutput) Reset() {
	*x = UpdateFileOutput{}
	mi := &file_stream_output_file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileOutput) ProtoMessage() {}

func (x *UpdateFileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileOutput.ProtoReflect.Descriptor instead.
func (*UpdateFileOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_file_service_proto_rawDescGZIP(), []int{3}
}

// *
// Block Stream data for a `systemDelete` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type SystemDeleteOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemDeleteOutput) Reset() {
	*x = SystemDeleteOutput{}
	mi := &file_stream_output_file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemDeleteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemDeleteOutput) ProtoMessage() {}

func (x *SystemDeleteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemDeleteOutput.ProtoReflect.Descriptor instead.
func (*SystemDeleteOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_file_service_proto_rawDescGZIP(), []int{4}
}

// *
// Block Stream data for a `systemUndelete` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type SystemUndeleteOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemUndeleteOutput) Reset() {
	*x = SystemUndeleteOutput{}
	mi := &file_stream_output_file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemUndeleteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemUndeleteOutput) ProtoMessage() {}

func (x *SystemUndeleteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemUndeleteOutput.ProtoReflect.Descriptor instead.
func (*SystemUndeleteOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_file_service_proto_rawDescGZIP(), []int{5}
}

var File_stream_output_file_service_proto protoreflect.FileDescriptor

const file_stream_output_file_service_proto_rawDesc = "" +
	"\n" +
	" stream/output/file_service.proto\x12#com.hedera.hapi.block.stream.output\"\x12\n" +
	"\x10AppendFileOutput\"\x12\n" +
	"\x10CreateFileOutput\"\x12\n" +
	"\x10DeleteFileOutput\"\x12\n" +
	"\x10UpdateFileOutput\"\x14\n" +
	"\x12SystemDeleteOutput\"\x16\n" +
	"\x14SystemUndeleteOutputBl\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z<github.com/hashgraph/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_file_service_proto_rawDescOnce sync.Once
	file_stream_output_file_service_proto_rawDescData []byte
)

func file_stream_output_file_service_proto_rawDescGZIP() []byte {
	file_stream_output_file_service_proto_rawDescOnce.Do(func() {
		file_stream_output_file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_file_service_proto_rawDesc), len(file_stream_output_file_service_proto_rawDesc)))
	})
	return file_stream_output_file_service_proto_rawDescData
}

var file_stream_output_file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stream_output_file_service_proto_goTypes = []any{
	(*AppendFileOutput)(nil),     // 0: com.hedera.hapi.block.stream.output.AppendFileOutput
	(*CreateFileOutput)(nil),     // 1: com.hedera.hapi.block.stream.output.CreateFileOutput
	(*DeleteFileOutput)(nil),     // 2: com.hedera.hapi.block.stream.output.DeleteFileOutput
	(*UpdateFileOutput)(nil),     // 3: com.hedera.hapi.block.stream.output.UpdateFileOutput
	(*SystemDeleteOutput)(nil),   // 4: com.hedera.hapi.block.stream.output.SystemDeleteOutput
	(*SystemUndeleteOutput)(nil), // 5: com.hedera.hapi.block.stream.output.SystemUndeleteOutput
}
var file_stream_output_file_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_output_file_service_proto_init() }
func file_stream_output_file_service_proto_init() {
	if File_stream_output_file_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_file_service_proto_rawDesc), len(file_stream_output_file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_file_service_proto_goTypes,
		DependencyIndexes: file_stream_output_file_service_proto_depIdxs,
		MessageInfos:      file_stream_output_file_service_proto_msgTypes,
	}.Build()
	File_stream_output_file_service_proto = out.File
	file_stream_output_file_service_proto_goTypes = nil
	file_stream_output_file_service_proto_depIdxs = nil
}
