//*
// # Schedule Service
// Block stream messages that report the results of transactions handled by
// the `Schedule` service.
//
// The Schedule service handles delayed execution in two major forms.
// - Transactions that only execute after being signed, via scheduleSign
//   transactions, with additional keys beyond the keys that signe the
//   scheduleCreate transaction.
// - Transactions that only execute after a specified consensus time.
//
// Some outputs contain a scheduled transaction identifier.<br/>
// That value SHALL be set if, and only if, the transaction resulted in
// _execution_ of the scheduled child transaction.<br/>
// Most outputs from this service SHALL NOT set the scheduled transaction
// identifier, because the transaction has not executed yet. Only when the
// schedule has gathered all of the signatures required to execute the
// scheduled child transaction is the network able to execute that child
// transaction, and assign a final transaction identifier.
//
// When a scheduled child transaction is executed, the identifier of the
// schedule that executed that transaction SHALL be included as a
// `schedule_ref` in the _result_ for the _child_ transaction.<br/>
// The output of the schedule transaction (create or sign) SHALL NOT contain
// the `schedule_ref`.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/schedule_service.proto

package output

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Block Stream data for a `createSchedule` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type CreateScheduleOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A scheduled transaction identifier.
	// <p>
	// This value SHALL be the transaction identifier for the _scheduled_
	// child transaction executed as a result of gathering sufficient
	// signatures to complete the schedule.<br/>
	// This value SHALL NOT be set unless the scheduled transaction was
	// executed as a child of this schedule create transaction.<br/>
	// This value SHALL NOT be set unless this schedule create transaction
	// was signed by sufficient keys to meet the signature requirements
	// for the scheduled child transaction immediately.
	ScheduledTransactionId *common.TransactionID `protobuf:"bytes,2,opt,name=scheduled_transaction_id,json=scheduledTransactionId,proto3" json:"scheduled_transaction_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateScheduleOutput) Reset() {
	*x = CreateScheduleOutput{}
	mi := &file_stream_output_schedule_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleOutput) ProtoMessage() {}

func (x *CreateScheduleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_schedule_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleOutput.ProtoReflect.Descriptor instead.
func (*CreateScheduleOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_schedule_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScheduleOutput) GetScheduledTransactionId() *common.TransactionID {
	if x != nil {
		return x.ScheduledTransactionId
	}
	return nil
}

// *
// Block Stream data for a `deleteSchedule` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type DeleteScheduleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleOutput) Reset() {
	*x = DeleteScheduleOutput{}
	mi := &file_stream_output_schedule_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleOutput) ProtoMessage() {}

func (x *DeleteScheduleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_schedule_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleOutput.ProtoReflect.Descriptor instead.
func (*DeleteScheduleOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_schedule_service_proto_rawDescGZIP(), []int{1}
}

// *
// Block Stream data for a `signSchedule` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type SignScheduleOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A scheduled transaction identifier.
	// <p>
	// This value SHALL be the transaction identifier for the _scheduled_
	// child transaction executed as a result of gathering sufficient
	// signatures to complete the schedule.<br/>
	// This value SHALL NOT be set unless the scheduled transaction was
	// executed as a child of this schedule sign transaction.<br/>
	// This value SHALL NOT be set unless this schedule sign transaction
	// was signed by sufficient additional keys to meet the signature
	// requirements for the scheduled child transaction.
	ScheduledTransactionId *common.TransactionID `protobuf:"bytes,1,opt,name=scheduled_transaction_id,json=scheduledTransactionId,proto3" json:"scheduled_transaction_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SignScheduleOutput) Reset() {
	*x = SignScheduleOutput{}
	mi := &file_stream_output_schedule_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignScheduleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignScheduleOutput) ProtoMessage() {}

func (x *SignScheduleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_schedule_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignScheduleOutput.ProtoReflect.Descriptor instead.
func (*SignScheduleOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_schedule_service_proto_rawDescGZIP(), []int{2}
}

func (x *SignScheduleOutput) GetScheduledTransactionId() *common.TransactionID {
	if x != nil {
		return x.ScheduledTransactionId
	}
	return nil
}

var File_stream_output_schedule_service_proto protoreflect.FileDescriptor

const file_stream_output_schedule_service_proto_rawDesc = "" +
	"\n" +
	"$stream/output/schedule_service.proto\x12#com.hedera.hapi.block.stream.output\x1a\x11basic_types.proto\"f\n" +
	"\x14CreateScheduleOutput\x12N\n" +
	"\x18scheduled_transaction_id\x18\x02 \x01(\v2\x14.proto.TransactionIDR\x16scheduledTransactionId\"\x16\n" +
	"\x14DeleteScheduleOutput\"d\n" +
	"\x12SignScheduleOutput\x12N\n" +
	"\x18scheduled_transaction_id\x18\x01 \x01(\v2\x14.proto.TransactionIDR\x16scheduledTransactionIdBm\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z=github.com/cordialsys/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_schedule_service_proto_rawDescOnce sync.Once
	file_stream_output_schedule_service_proto_rawDescData []byte
)

func file_stream_output_schedule_service_proto_rawDescGZIP() []byte {
	file_stream_output_schedule_service_proto_rawDescOnce.Do(func() {
		file_stream_output_schedule_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_schedule_service_proto_rawDesc), len(file_stream_output_schedule_service_proto_rawDesc)))
	})
	return file_stream_output_schedule_service_proto_rawDescData
}

var file_stream_output_schedule_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stream_output_schedule_service_proto_goTypes = []any{
	(*CreateScheduleOutput)(nil), // 0: com.hedera.hapi.block.stream.output.CreateScheduleOutput
	(*DeleteScheduleOutput)(nil), // 1: com.hedera.hapi.block.stream.output.DeleteScheduleOutput
	(*SignScheduleOutput)(nil),   // 2: com.hedera.hapi.block.stream.output.SignScheduleOutput
	(*common.TransactionID)(nil), // 3: proto.TransactionID
}
var file_stream_output_schedule_service_proto_depIdxs = []int32{
	3, // 0: com.hedera.hapi.block.stream.output.CreateScheduleOutput.scheduled_transaction_id:type_name -> proto.TransactionID
	3, // 1: com.hedera.hapi.block.stream.output.SignScheduleOutput.scheduled_transaction_id:type_name -> proto.TransactionID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stream_output_schedule_service_proto_init() }
func file_stream_output_schedule_service_proto_init() {
	if File_stream_output_schedule_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_schedule_service_proto_rawDesc), len(file_stream_output_schedule_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_schedule_service_proto_goTypes,
		DependencyIndexes: file_stream_output_schedule_service_proto_depIdxs,
		MessageInfos:      file_stream_output_schedule_service_proto_msgTypes,
	}.Build()
	File_stream_output_schedule_service_proto = out.File
	file_stream_output_schedule_service_proto_goTypes = nil
	file_stream_output_schedule_service_proto_depIdxs = nil
}
