//*
// #  Service
// Block stream messages that report the results of transactions handled
// by the `smart contract` service.
//
// > REVIEW NOTE
// >> The use of sidecar records is a bit odd here. We may find it more
// >> effective to extract the actual changes into proper output messages
// >> and fields included in the ethereum call output and/or related state
// >> changes items, and remove the whole sidecar concept going forward.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/smart_contract_service.proto

package output

import (
	services "github.com/cordialsys/hedera-protobufs-go/services"
	streams "github.com/cordialsys/hedera-protobufs-go/streams"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Block Stream data for a `contractCallMethod` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type CallContractOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A list of additional outputs.
	// <p>
	// This field MAY record one or more additional outputs and smart
	// contract state changes produced during the ethereum call
	// transaction handling.<br/>
	// This field SHALL NOT be set if the transaction handling did not
	// produce additional outputs.<br/>
	// This field is not settled and MAY be removed or modified.
	Sidecars []*streams.TransactionSidecarRecord `protobuf:"bytes,1,rep,name=sidecars,proto3" json:"sidecars,omitempty"`
	// *
	// An EVM contract call result.
	// <p>
	// This field SHALL contain all of the data produced by the contract
	// call transaction as well as basic accounting results.
	ContractCallResult *services.ContractFunctionResult `protobuf:"bytes,2,opt,name=contract_call_result,json=contractCallResult,proto3" json:"contract_call_result,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CallContractOutput) Reset() {
	*x = CallContractOutput{}
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractOutput) ProtoMessage() {}

func (x *CallContractOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractOutput.ProtoReflect.Descriptor instead.
func (*CallContractOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_smart_contract_service_proto_rawDescGZIP(), []int{0}
}

func (x *CallContractOutput) GetSidecars() []*streams.TransactionSidecarRecord {
	if x != nil {
		return x.Sidecars
	}
	return nil
}

func (x *CallContractOutput) GetContractCallResult() *services.ContractFunctionResult {
	if x != nil {
		return x.ContractCallResult
	}
	return nil
}

// *
// Block Stream data for a `createContract` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type CreateContractOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A list of additional outputs.
	// <p>
	// This field MAY record one or more additional outputs and smart
	// contract state changes produced during the ethereum call
	// transaction handling.<br/>
	// This field SHALL NOT be set if the transaction handling did not
	// produce additional outputs.<br/>
	// This field is not settled and MAY be removed or modified.
	Sidecars []*streams.TransactionSidecarRecord `protobuf:"bytes,1,rep,name=sidecars,proto3" json:"sidecars,omitempty"`
	// *
	// An EVM contract call result.
	// <p>
	// This field SHALL contain all of the data produced by the contract
	// create transaction as well as basic accounting results.
	ContractCreateResult *services.ContractFunctionResult `protobuf:"bytes,2,opt,name=contract_create_result,json=contractCreateResult,proto3" json:"contract_create_result,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateContractOutput) Reset() {
	*x = CreateContractOutput{}
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContractOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContractOutput) ProtoMessage() {}

func (x *CreateContractOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContractOutput.ProtoReflect.Descriptor instead.
func (*CreateContractOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_smart_contract_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContractOutput) GetSidecars() []*streams.TransactionSidecarRecord {
	if x != nil {
		return x.Sidecars
	}
	return nil
}

func (x *CreateContractOutput) GetContractCreateResult() *services.ContractFunctionResult {
	if x != nil {
		return x.ContractCreateResult
	}
	return nil
}

// *
// Block Stream data for a `updateContract` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UpdateContractOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContractOutput) Reset() {
	*x = UpdateContractOutput{}
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContractOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractOutput) ProtoMessage() {}

func (x *UpdateContractOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractOutput.ProtoReflect.Descriptor instead.
func (*UpdateContractOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_smart_contract_service_proto_rawDescGZIP(), []int{2}
}

// *
// Block Stream data for a `deleteContract` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type DeleteContractOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContractOutput) Reset() {
	*x = DeleteContractOutput{}
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContractOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContractOutput) ProtoMessage() {}

func (x *DeleteContractOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContractOutput.ProtoReflect.Descriptor instead.
func (*DeleteContractOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_smart_contract_service_proto_rawDescGZIP(), []int{3}
}

// *
// Block Stream data for a contract `systemUndelete` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type SystemUnDeleteContractOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemUnDeleteContractOutput) Reset() {
	*x = SystemUnDeleteContractOutput{}
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemUnDeleteContractOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemUnDeleteContractOutput) ProtoMessage() {}

func (x *SystemUnDeleteContractOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemUnDeleteContractOutput.ProtoReflect.Descriptor instead.
func (*SystemUnDeleteContractOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_smart_contract_service_proto_rawDescGZIP(), []int{4}
}

// *
// Block Stream data for a contract `systemDelete` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type SystemDeleteContractOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemDeleteContractOutput) Reset() {
	*x = SystemDeleteContractOutput{}
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemDeleteContractOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemDeleteContractOutput) ProtoMessage() {}

func (x *SystemDeleteContractOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemDeleteContractOutput.ProtoReflect.Descriptor instead.
func (*SystemDeleteContractOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_smart_contract_service_proto_rawDescGZIP(), []int{5}
}

// *
// Block Stream data for a `callEthereum` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type EthereumOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A list of additional outputs.
	// <p>
	// This field MAY record one or more additional outputs and smart
	// contract state changes produced during the ethereum call
	// transaction handling.<br/>
	// This field SHALL NOT be set if the transaction handling did not
	// produce additional outputs.<br/>
	// This field is not settled and MAY be removed or modified.
	Sidecars []*streams.TransactionSidecarRecord `protobuf:"bytes,1,rep,name=sidecars,proto3" json:"sidecars,omitempty"`
	// *
	// An ethereum hash value.
	// <p>
	// This SHALL be a keccak256 hash of the ethereumData.
	EthereumHash []byte `protobuf:"bytes,2,opt,name=ethereum_hash,json=ethereumHash,proto3" json:"ethereum_hash,omitempty"`
	// Types that are valid to be assigned to EthResult:
	//
	//	*EthereumOutput_EthereumCallResult
	//	*EthereumOutput_EthereumCreateResult
	EthResult     isEthereumOutput_EthResult `protobuf_oneof:"eth_result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EthereumOutput) Reset() {
	*x = EthereumOutput{}
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EthereumOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthereumOutput) ProtoMessage() {}

func (x *EthereumOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_smart_contract_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthereumOutput.ProtoReflect.Descriptor instead.
func (*EthereumOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_smart_contract_service_proto_rawDescGZIP(), []int{6}
}

func (x *EthereumOutput) GetSidecars() []*streams.TransactionSidecarRecord {
	if x != nil {
		return x.Sidecars
	}
	return nil
}

func (x *EthereumOutput) GetEthereumHash() []byte {
	if x != nil {
		return x.EthereumHash
	}
	return nil
}

func (x *EthereumOutput) GetEthResult() isEthereumOutput_EthResult {
	if x != nil {
		return x.EthResult
	}
	return nil
}

func (x *EthereumOutput) GetEthereumCallResult() *services.ContractFunctionResult {
	if x != nil {
		if x, ok := x.EthResult.(*EthereumOutput_EthereumCallResult); ok {
			return x.EthereumCallResult
		}
	}
	return nil
}

func (x *EthereumOutput) GetEthereumCreateResult() *services.ContractFunctionResult {
	if x != nil {
		if x, ok := x.EthResult.(*EthereumOutput_EthereumCreateResult); ok {
			return x.EthereumCreateResult
		}
	}
	return nil
}

type isEthereumOutput_EthResult interface {
	isEthereumOutput_EthResult()
}

type EthereumOutput_EthereumCallResult struct {
	// *
	// A result for an Ethereum Transaction executed as a call.
	// <p>
	// This field SHALL contain all of the data produced by the contract
	// call transaction as well as basic accounting results.
	EthereumCallResult *services.ContractFunctionResult `protobuf:"bytes,3,opt,name=ethereum_call_result,json=ethereumCallResult,proto3,oneof"`
}

type EthereumOutput_EthereumCreateResult struct {
	// *
	// A result for an Ethereum Transaction executed as a create.
	// <p>
	// This field SHALL contain all of the data produced by the contract
	// create transaction as well as basic accounting results.
	EthereumCreateResult *services.ContractFunctionResult `protobuf:"bytes,4,opt,name=ethereum_create_result,json=ethereumCreateResult,proto3,oneof"`
}

func (*EthereumOutput_EthereumCallResult) isEthereumOutput_EthResult() {}

func (*EthereumOutput_EthereumCreateResult) isEthereumOutput_EthResult() {}

var File_stream_output_smart_contract_service_proto protoreflect.FileDescriptor

const file_stream_output_smart_contract_service_proto_rawDesc = "" +
	"\n" +
	"*stream/output/smart_contract_service.proto\x12#com.hedera.hapi.block.stream.output\x1a\x14contract_types.proto\x1a\x12sidecar_file.proto\"\xa2\x01\n" +
	"\x12CallContractOutput\x12;\n" +
	"\bsidecars\x18\x01 \x03(\v2\x1f.proto.TransactionSidecarRecordR\bsidecars\x12O\n" +
	"\x14contract_call_result\x18\x02 \x01(\v2\x1d.proto.ContractFunctionResultR\x12contractCallResult\"\xa8\x01\n" +
	"\x14CreateContractOutput\x12;\n" +
	"\bsidecars\x18\x01 \x03(\v2\x1f.proto.TransactionSidecarRecordR\bsidecars\x12S\n" +
	"\x16contract_create_result\x18\x02 \x01(\v2\x1d.proto.ContractFunctionResultR\x14contractCreateResult\"\x16\n" +
	"\x14UpdateContractOutput\"\x16\n" +
	"\x14DeleteContractOutput\"\x1e\n" +
	"\x1cSystemUnDeleteContractOutput\"\x1c\n" +
	"\x1aSystemDeleteContractOutput\"\xaa\x02\n" +
	"\x0eEthereumOutput\x12;\n" +
	"\bsidecars\x18\x01 \x03(\v2\x1f.proto.TransactionSidecarRecordR\bsidecars\x12#\n" +
	"\rethereum_hash\x18\x02 \x01(\fR\fethereumHash\x12Q\n" +
	"\x14ethereum_call_result\x18\x03 \x01(\v2\x1d.proto.ContractFunctionResultH\x00R\x12ethereumCallResult\x12U\n" +
	"\x16ethereum_create_result\x18\x04 \x01(\v2\x1d.proto.ContractFunctionResultH\x00R\x14ethereumCreateResultB\f\n" +
	"\n" +
	"eth_resultBm\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z=github.com/cordialsys/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_smart_contract_service_proto_rawDescOnce sync.Once
	file_stream_output_smart_contract_service_proto_rawDescData []byte
)

func file_stream_output_smart_contract_service_proto_rawDescGZIP() []byte {
	file_stream_output_smart_contract_service_proto_rawDescOnce.Do(func() {
		file_stream_output_smart_contract_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_smart_contract_service_proto_rawDesc), len(file_stream_output_smart_contract_service_proto_rawDesc)))
	})
	return file_stream_output_smart_contract_service_proto_rawDescData
}

var file_stream_output_smart_contract_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stream_output_smart_contract_service_proto_goTypes = []any{
	(*CallContractOutput)(nil),               // 0: com.hedera.hapi.block.stream.output.CallContractOutput
	(*CreateContractOutput)(nil),             // 1: com.hedera.hapi.block.stream.output.CreateContractOutput
	(*UpdateContractOutput)(nil),             // 2: com.hedera.hapi.block.stream.output.UpdateContractOutput
	(*DeleteContractOutput)(nil),             // 3: com.hedera.hapi.block.stream.output.DeleteContractOutput
	(*SystemUnDeleteContractOutput)(nil),     // 4: com.hedera.hapi.block.stream.output.SystemUnDeleteContractOutput
	(*SystemDeleteContractOutput)(nil),       // 5: com.hedera.hapi.block.stream.output.SystemDeleteContractOutput
	(*EthereumOutput)(nil),                   // 6: com.hedera.hapi.block.stream.output.EthereumOutput
	(*streams.TransactionSidecarRecord)(nil), // 7: proto.TransactionSidecarRecord
	(*services.ContractFunctionResult)(nil),  // 8: proto.ContractFunctionResult
}
var file_stream_output_smart_contract_service_proto_depIdxs = []int32{
	7, // 0: com.hedera.hapi.block.stream.output.CallContractOutput.sidecars:type_name -> proto.TransactionSidecarRecord
	8, // 1: com.hedera.hapi.block.stream.output.CallContractOutput.contract_call_result:type_name -> proto.ContractFunctionResult
	7, // 2: com.hedera.hapi.block.stream.output.CreateContractOutput.sidecars:type_name -> proto.TransactionSidecarRecord
	8, // 3: com.hedera.hapi.block.stream.output.CreateContractOutput.contract_create_result:type_name -> proto.ContractFunctionResult
	7, // 4: com.hedera.hapi.block.stream.output.EthereumOutput.sidecars:type_name -> proto.TransactionSidecarRecord
	8, // 5: com.hedera.hapi.block.stream.output.EthereumOutput.ethereum_call_result:type_name -> proto.ContractFunctionResult
	8, // 6: com.hedera.hapi.block.stream.output.EthereumOutput.ethereum_create_result:type_name -> proto.ContractFunctionResult
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_stream_output_smart_contract_service_proto_init() }
func file_stream_output_smart_contract_service_proto_init() {
	if File_stream_output_smart_contract_service_proto != nil {
		return
	}
	file_stream_output_smart_contract_service_proto_msgTypes[6].OneofWrappers = []any{
		(*EthereumOutput_EthereumCallResult)(nil),
		(*EthereumOutput_EthereumCreateResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_smart_contract_service_proto_rawDesc), len(file_stream_output_smart_contract_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_smart_contract_service_proto_goTypes,
		DependencyIndexes: file_stream_output_smart_contract_service_proto_depIdxs,
		MessageInfos:      file_stream_output_smart_contract_service_proto_msgTypes,
	}.Build()
	File_stream_output_smart_contract_service_proto = out.File
	file_stream_output_smart_contract_service_proto_goTypes = nil
	file_stream_output_smart_contract_service_proto_depIdxs = nil
}
