//*
// # State Changes
// Serialization of change records which describe the mutation of state
// during a block.
//
// The _ordered_ application of all `StateChanges` in a block to an initial
// state that matches network state at the beginning of that block MUST produce
// a resultant state that matches the network state at the end of that block.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/state_changes.proto

package output

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	state "github.com/cordialsys/hedera-protobufs-go/platform/state"
	services "github.com/cordialsys/hedera-protobufs-go/services"
	addressbook "github.com/cordialsys/hedera-protobufs-go/services/state/addressbook"
	blockrecords "github.com/cordialsys/hedera-protobufs-go/services/state/blockrecords"
	blockstream "github.com/cordialsys/hedera-protobufs-go/services/state/blockstream"
	congestion "github.com/cordialsys/hedera-protobufs-go/services/state/congestion"
	consensus "github.com/cordialsys/hedera-protobufs-go/services/state/consensus"
	contract "github.com/cordialsys/hedera-protobufs-go/services/state/contract"
	file "github.com/cordialsys/hedera-protobufs-go/services/state/file"
	recordcache "github.com/cordialsys/hedera-protobufs-go/services/state/recordcache"
	roster "github.com/cordialsys/hedera-protobufs-go/services/state/roster"
	schedule "github.com/cordialsys/hedera-protobufs-go/services/state/schedule"
	throttles "github.com/cordialsys/hedera-protobufs-go/services/state/throttles"
	token "github.com/cordialsys/hedera-protobufs-go/services/state/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// An informational enumeration of all known states.
// This enumeration is included here So that people know the mapping from
// integer to state "name".
//
// State changes are expressed in terms of changes to named states at the
// high level conceptual model of the state type like map key/values or
// queue appends. To say which state the change is on we will include an
// `integer` number for the state name. This is done for performance and
// efficiency as there will be 10s of thousands of state changes in a block.
//
// We use an integer, and provide this enumeration, for the following reasons.
//   - If we have a extra 8-10 bytes per state change at 40-50K state changes
//     per second then that is an extra 2.5-4 megabits of bandwidth. Compression
//     should help a lot but that is not guaranteed.
//   - When the state name is used as part of complex key in the big state
//     merkle map. The smaller the key is, in bytes, the more efficient the
//     database is, because more keys can fit in a single disk page.
//   - When parsing keys, parsing a UTF-8 string to a Java String is a many
//     times more expensive than parsing a VARINT to an integer.
//
// Note: This enumeration is never transmitted directly in the block stream.
// This enumeration is provided for clients to _interpret_ the value
// of the `StateChange`.`state_id` field.
type StateIdentifier int32

const (
	// *
	// A state identifier for the Topics state.
	StateIdentifier_STATE_ID_TOPICS StateIdentifier = 0
	// *
	// A state identifier for the next entity Identifier.
	StateIdentifier_STATE_ID_ENTITY_ID StateIdentifier = 1
	// *
	// A state identifier for the Accounts state.
	StateIdentifier_STATE_ID_ACCOUNTS StateIdentifier = 2
	// *
	// A state identifier for account aliases.
	StateIdentifier_STATE_ID_ALIASES StateIdentifier = 3
	// *
	// A state identifier for contract storage slots.
	StateIdentifier_STATE_ID_CONTRACT_STORAGE StateIdentifier = 4
	// *
	// A state identifier for contract bytecode.
	StateIdentifier_STATE_ID_CONTRACT_BYTECODE StateIdentifier = 5
	// *
	// A state identifier for Hedera File Service (HFS).
	StateIdentifier_STATE_ID_FILES StateIdentifier = 6
	// *
	// A state identifier for Hedera Token Service (HTS).
	StateIdentifier_STATE_ID_TOKENS StateIdentifier = 7
	// *
	// A state identifier for non-fungible/unique tokens.
	StateIdentifier_STATE_ID_NFTS StateIdentifier = 8
	// *
	// A state identifier for token relationships.
	StateIdentifier_STATE_ID_TOKEN_RELATIONS StateIdentifier = 9
	// *
	// A state identifier for network staking information.
	StateIdentifier_STATE_ID_STAKING_INFO StateIdentifier = 10
	// *
	// A state identifier for network staking rewards.
	StateIdentifier_STATE_ID_NETWORK_REWARDS StateIdentifier = 11
	// *
	// A state identifier for throttle usage.
	StateIdentifier_STATE_ID_THROTTLE_USAGE StateIdentifier = 12
	// *
	// A state identifier for network congestion start times.
	StateIdentifier_STATE_ID_CONGESTION_STARTS StateIdentifier = 13
	// *
	// A state identifier for scheduled transactions.
	StateIdentifier_STATE_ID_SCHEDULES_BY_ID StateIdentifier = 14
	// *
	// A state identifier for scheduled transaction expiration.
	StateIdentifier_STATE_ID_SCHEDULES_BY_EXPIRY StateIdentifier = 15
	// *
	// A state identifier for scheduled transaction deduplication.
	StateIdentifier_STATE_ID_SCHEDULES_BY_EQUALITY StateIdentifier = 16
	// *
	// A state identifier for conversion rate updates.
	StateIdentifier_STATE_ID_MIDNIGHT_RATES StateIdentifier = 17
	// *
	// A state identifier for the network running hash(es).
	StateIdentifier_STATE_ID_RUNNING_HASHES StateIdentifier = 18
	// *
	// A state identifier for network block information.
	StateIdentifier_STATE_ID_BLOCK_INFO StateIdentifier = 19
	// *
	// A state identifier for address book nodes.
	StateIdentifier_STATE_ID_NODES StateIdentifier = 20
	// *
	// A state identifier for the next "upgrade" file.
	StateIdentifier_STATE_ID_UPGRADE_FILE StateIdentifier = 21
	// *
	// A state identifier for the hash of the next "upgrade" file.
	StateIdentifier_STATE_ID_UPGRADE_FILE_HASH StateIdentifier = 22
	// *
	// A state identifier for the next network freeze time.
	StateIdentifier_STATE_ID_FREEZE_TIME StateIdentifier = 23
	// *
	// A state identifier for the block stream status singleton.
	StateIdentifier_STATE_ID_BLOCK_STREAM_INFO StateIdentifier = 24
	// *
	// A state identifier for pending airdrops.
	StateIdentifier_STATE_ID_PENDING_AIRDROPS StateIdentifier = 25
	// *
	// A state identifier for the platform state singleton.
	StateIdentifier_STATE_ID_PLATFORM_STATE StateIdentifier = 26
	// *
	// A state identifier for the roster state singleton.
	StateIdentifier_STATE_ID_ROSTER_STATE StateIdentifier = 27
	// *
	// A state identifier for the rosters key/value map.
	StateIdentifier_STATE_ID_ROSTERS StateIdentifier = 28
	// *
	// A state identifier for the round receipts queue.
	StateIdentifier_STATE_ID_TRANSACTION_RECEIPTS_QUEUE StateIdentifier = 126
	// *
	// A state for the `150` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_150 StateIdentifier = 10001
	// *
	// A state for the `151` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_151 StateIdentifier = 10002
	// *
	// A state for the `152` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_152 StateIdentifier = 10003
	// *
	// A state for the `153` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_153 StateIdentifier = 10004
	// *
	// A state for the `154` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_154 StateIdentifier = 10005
	// *
	// A state for the `155` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_155 StateIdentifier = 10006
	// *
	// A state for the `156` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_156 StateIdentifier = 10007
	// *
	// A state for the `157` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_157 StateIdentifier = 10008
	// *
	// A state for the `158` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_158 StateIdentifier = 10009
	// *
	// A state for the `159` upgrade file data
	StateIdentifier_STATE_ID_UPGRADE_DATA_159 StateIdentifier = 10010
)

// Enum value maps for StateIdentifier.
var (
	StateIdentifier_name = map[int32]string{
		0:     "STATE_ID_TOPICS",
		1:     "STATE_ID_ENTITY_ID",
		2:     "STATE_ID_ACCOUNTS",
		3:     "STATE_ID_ALIASES",
		4:     "STATE_ID_CONTRACT_STORAGE",
		5:     "STATE_ID_CONTRACT_BYTECODE",
		6:     "STATE_ID_FILES",
		7:     "STATE_ID_TOKENS",
		8:     "STATE_ID_NFTS",
		9:     "STATE_ID_TOKEN_RELATIONS",
		10:    "STATE_ID_STAKING_INFO",
		11:    "STATE_ID_NETWORK_REWARDS",
		12:    "STATE_ID_THROTTLE_USAGE",
		13:    "STATE_ID_CONGESTION_STARTS",
		14:    "STATE_ID_SCHEDULES_BY_ID",
		15:    "STATE_ID_SCHEDULES_BY_EXPIRY",
		16:    "STATE_ID_SCHEDULES_BY_EQUALITY",
		17:    "STATE_ID_MIDNIGHT_RATES",
		18:    "STATE_ID_RUNNING_HASHES",
		19:    "STATE_ID_BLOCK_INFO",
		20:    "STATE_ID_NODES",
		21:    "STATE_ID_UPGRADE_FILE",
		22:    "STATE_ID_UPGRADE_FILE_HASH",
		23:    "STATE_ID_FREEZE_TIME",
		24:    "STATE_ID_BLOCK_STREAM_INFO",
		25:    "STATE_ID_PENDING_AIRDROPS",
		26:    "STATE_ID_PLATFORM_STATE",
		27:    "STATE_ID_ROSTER_STATE",
		28:    "STATE_ID_ROSTERS",
		126:   "STATE_ID_TRANSACTION_RECEIPTS_QUEUE",
		10001: "STATE_ID_UPGRADE_DATA_150",
		10002: "STATE_ID_UPGRADE_DATA_151",
		10003: "STATE_ID_UPGRADE_DATA_152",
		10004: "STATE_ID_UPGRADE_DATA_153",
		10005: "STATE_ID_UPGRADE_DATA_154",
		10006: "STATE_ID_UPGRADE_DATA_155",
		10007: "STATE_ID_UPGRADE_DATA_156",
		10008: "STATE_ID_UPGRADE_DATA_157",
		10009: "STATE_ID_UPGRADE_DATA_158",
		10010: "STATE_ID_UPGRADE_DATA_159",
	}
	StateIdentifier_value = map[string]int32{
		"STATE_ID_TOPICS":                     0,
		"STATE_ID_ENTITY_ID":                  1,
		"STATE_ID_ACCOUNTS":                   2,
		"STATE_ID_ALIASES":                    3,
		"STATE_ID_CONTRACT_STORAGE":           4,
		"STATE_ID_CONTRACT_BYTECODE":          5,
		"STATE_ID_FILES":                      6,
		"STATE_ID_TOKENS":                     7,
		"STATE_ID_NFTS":                       8,
		"STATE_ID_TOKEN_RELATIONS":            9,
		"STATE_ID_STAKING_INFO":               10,
		"STATE_ID_NETWORK_REWARDS":            11,
		"STATE_ID_THROTTLE_USAGE":             12,
		"STATE_ID_CONGESTION_STARTS":          13,
		"STATE_ID_SCHEDULES_BY_ID":            14,
		"STATE_ID_SCHEDULES_BY_EXPIRY":        15,
		"STATE_ID_SCHEDULES_BY_EQUALITY":      16,
		"STATE_ID_MIDNIGHT_RATES":             17,
		"STATE_ID_RUNNING_HASHES":             18,
		"STATE_ID_BLOCK_INFO":                 19,
		"STATE_ID_NODES":                      20,
		"STATE_ID_UPGRADE_FILE":               21,
		"STATE_ID_UPGRADE_FILE_HASH":          22,
		"STATE_ID_FREEZE_TIME":                23,
		"STATE_ID_BLOCK_STREAM_INFO":          24,
		"STATE_ID_PENDING_AIRDROPS":           25,
		"STATE_ID_PLATFORM_STATE":             26,
		"STATE_ID_ROSTER_STATE":               27,
		"STATE_ID_ROSTERS":                    28,
		"STATE_ID_TRANSACTION_RECEIPTS_QUEUE": 126,
		"STATE_ID_UPGRADE_DATA_150":           10001,
		"STATE_ID_UPGRADE_DATA_151":           10002,
		"STATE_ID_UPGRADE_DATA_152":           10003,
		"STATE_ID_UPGRADE_DATA_153":           10004,
		"STATE_ID_UPGRADE_DATA_154":           10005,
		"STATE_ID_UPGRADE_DATA_155":           10006,
		"STATE_ID_UPGRADE_DATA_156":           10007,
		"STATE_ID_UPGRADE_DATA_157":           10008,
		"STATE_ID_UPGRADE_DATA_158":           10009,
		"STATE_ID_UPGRADE_DATA_159":           10010,
	}
)

func (x StateIdentifier) Enum() *StateIdentifier {
	p := new(StateIdentifier)
	*p = x
	return p
}

func (x StateIdentifier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateIdentifier) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_output_state_changes_proto_enumTypes[0].Descriptor()
}

func (StateIdentifier) Type() protoreflect.EnumType {
	return &file_stream_output_state_changes_proto_enumTypes[0]
}

func (x StateIdentifier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateIdentifier.Descriptor instead.
func (StateIdentifier) EnumDescriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{0}
}

// *
// An enumeration of the types of named states.<br/>
// The default, Singleton, is the type of state most frequently
// added and removed.
type NewStateType int32

const (
	NewStateType_SINGLETON   NewStateType = 0
	NewStateType_VIRTUAL_MAP NewStateType = 1
	NewStateType_QUEUE       NewStateType = 2
)

// Enum value maps for NewStateType.
var (
	NewStateType_name = map[int32]string{
		0: "SINGLETON",
		1: "VIRTUAL_MAP",
		2: "QUEUE",
	}
	NewStateType_value = map[string]int32{
		"SINGLETON":   0,
		"VIRTUAL_MAP": 1,
		"QUEUE":       2,
	}
)

func (x NewStateType) Enum() *NewStateType {
	p := new(NewStateType)
	*p = x
	return p
}

func (x NewStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NewStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_output_state_changes_proto_enumTypes[1].Descriptor()
}

func (NewStateType) Type() protoreflect.EnumType {
	return &file_stream_output_state_changes_proto_enumTypes[1]
}

func (x NewStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NewStateType.Descriptor instead.
func (NewStateType) EnumDescriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{1}
}

// *
// A set of state changes.
//
// Each set of changes in the network deterministically mutates the
// current state to a new state, and all nodes MUST apply the same
// changes in the same order.<br/>
// Each change set described in the block stream SHALL describe an
// ordered set of mutations which mutate the previous valid state to
// produce a new valid state.<br/>
// The order of state change sets SHALL be determined by the
// `consensus_timestamp`, which is a strictly ascending value
// determined by network consensus.
//
// ### Consensus Timestamp
// This value enables a consumer of the block stream to order state
// changes by a consistent ascending value that is determined by network
// consensus. A primary use case would be to enter state changes in a
// time-series database.<br/>
// This value depends on the cause of the state change.
//  1. For transactions, this is the transaction consensus timestamp.
//  1. For events without transactions, this is the consensus timestamp of
//     the event (round?).
//  1. For changes that are not the result of a transaction, but still follow
//     a transaction within an event, this is the consensus timestamp of the
//     preceding transaction.
type StateChanges struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The consensus timestamp of this set of changes.
	// <p>
	// This value SHALL be deterministic with the cause of the state change.
	ConsensusTimestamp *common.Timestamp `protobuf:"bytes,1,opt,name=consensus_timestamp,json=consensusTimestamp,proto3" json:"consensus_timestamp,omitempty"`
	// *
	// An ordered list of individual changes.
	// <p>
	// These changes MUST be applied in the order listed to produce
	// a correct modified state.
	StateChanges  []*StateChange `protobuf:"bytes,2,rep,name=state_changes,json=stateChanges,proto3" json:"state_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChanges) Reset() {
	*x = StateChanges{}
	mi := &file_stream_output_state_changes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChanges) ProtoMessage() {}

func (x *StateChanges) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChanges.ProtoReflect.Descriptor instead.
func (*StateChanges) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{0}
}

func (x *StateChanges) GetConsensusTimestamp() *common.Timestamp {
	if x != nil {
		return x.ConsensusTimestamp
	}
	return nil
}

func (x *StateChanges) GetStateChanges() []*StateChange {
	if x != nil {
		return x.StateChanges
	}
	return nil
}

// *
// A change to any item in the merkle tree.
//
// A State change SHALL represent one mutation of the network state merkle
// tree. The state changes published in the block stream MAY be combined
// into an ordered set of state mutations that transform the tree from any
// initial state to a destination state.<br/>
// When the full set of state change items from the block stream for a round
// is applied to the network state at the start of that round the result
// SHALL match the network state at the end of the round.
// TODO: Need documentation for how the merkle tree is constructed.
//
//	Need to reference that document, stored in platform docs?, here.
type StateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A state identifier.<br/>
	// The reason we use an integer field here, and not an enum field is to
	// better support forward compatibility. There will be many cases when a
	// block node or other client (such as a dApp) with HAPI version N wants
	// to process blocks from HAPI version N+1, for example. If we use a
	// protobuf enum then when that is mapped Java or Rust it would not be
	// parsed as an enum value because those languages do not support unknown
	// enum values. ProtoC has a workaround for this but it is complex and
	// requires non-deterministic parsing. Our solution to create an integer
	// field and provide an enumeration for mapping that integer is intended
	// as an acceptable compromise solution.
	// <p>
	// This number SHALL identify the merkle subtree "state" to be modified and
	// often corresponds to a `VirtualMap` identifier.
	// This number SHALL be a valid value for the `StateIdentifier` enum.
	StateId uint32 `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	// Types that are valid to be assigned to ChangeOperation:
	//
	//	*StateChange_StateAdd
	//	*StateChange_StateRemove
	//	*StateChange_SingletonUpdate
	//	*StateChange_MapUpdate
	//	*StateChange_MapDelete
	//	*StateChange_QueuePush
	//	*StateChange_QueuePop
	ChangeOperation isStateChange_ChangeOperation `protobuf_oneof:"change_operation"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StateChange) Reset() {
	*x = StateChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChange) ProtoMessage() {}

func (x *StateChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChange.ProtoReflect.Descriptor instead.
func (*StateChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{1}
}

func (x *StateChange) GetStateId() uint32 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *StateChange) GetChangeOperation() isStateChange_ChangeOperation {
	if x != nil {
		return x.ChangeOperation
	}
	return nil
}

func (x *StateChange) GetStateAdd() *NewStateChange {
	if x != nil {
		if x, ok := x.ChangeOperation.(*StateChange_StateAdd); ok {
			return x.StateAdd
		}
	}
	return nil
}

func (x *StateChange) GetStateRemove() *RemovedStateChange {
	if x != nil {
		if x, ok := x.ChangeOperation.(*StateChange_StateRemove); ok {
			return x.StateRemove
		}
	}
	return nil
}

func (x *StateChange) GetSingletonUpdate() *SingletonUpdateChange {
	if x != nil {
		if x, ok := x.ChangeOperation.(*StateChange_SingletonUpdate); ok {
			return x.SingletonUpdate
		}
	}
	return nil
}

func (x *StateChange) GetMapUpdate() *MapUpdateChange {
	if x != nil {
		if x, ok := x.ChangeOperation.(*StateChange_MapUpdate); ok {
			return x.MapUpdate
		}
	}
	return nil
}

func (x *StateChange) GetMapDelete() *MapDeleteChange {
	if x != nil {
		if x, ok := x.ChangeOperation.(*StateChange_MapDelete); ok {
			return x.MapDelete
		}
	}
	return nil
}

func (x *StateChange) GetQueuePush() *QueuePushChange {
	if x != nil {
		if x, ok := x.ChangeOperation.(*StateChange_QueuePush); ok {
			return x.QueuePush
		}
	}
	return nil
}

func (x *StateChange) GetQueuePop() *QueuePopChange {
	if x != nil {
		if x, ok := x.ChangeOperation.(*StateChange_QueuePop); ok {
			return x.QueuePop
		}
	}
	return nil
}

type isStateChange_ChangeOperation interface {
	isStateChange_ChangeOperation()
}

type StateChange_StateAdd struct {
	// *
	// Addition of a new state.<br/>
	// This may be a singleton, virtual map, or queue state.
	StateAdd *NewStateChange `protobuf:"bytes,2,opt,name=state_add,json=stateAdd,proto3,oneof"`
}

type StateChange_StateRemove struct {
	// *
	// Removal of an existing state.<br/>
	// The entire singleton, virtual map, or queue state is removed,
	// and not just the contents.
	StateRemove *RemovedStateChange `protobuf:"bytes,3,opt,name=state_remove,json=stateRemove,proto3,oneof"`
}

type StateChange_SingletonUpdate struct {
	// *
	// An add or update to a `Singleton` state.
	SingletonUpdate *SingletonUpdateChange `protobuf:"bytes,4,opt,name=singleton_update,json=singletonUpdate,proto3,oneof"`
}

type StateChange_MapUpdate struct {
	// *
	// An add or update to a single item in a `VirtualMap`.
	MapUpdate *MapUpdateChange `protobuf:"bytes,5,opt,name=map_update,json=mapUpdate,proto3,oneof"`
}

type StateChange_MapDelete struct {
	// *
	// A removal of a single item from a `VirtualMap`.
	MapDelete *MapDeleteChange `protobuf:"bytes,6,opt,name=map_delete,json=mapDelete,proto3,oneof"`
}

type StateChange_QueuePush struct {
	// *
	// Addition of an item to a `Queue` state.
	QueuePush *QueuePushChange `protobuf:"bytes,7,opt,name=queue_push,json=queuePush,proto3,oneof"`
}

type StateChange_QueuePop struct {
	// *
	// Removal of an item from a `Queue` state.
	QueuePop *QueuePopChange `protobuf:"bytes,8,opt,name=queue_pop,json=queuePop,proto3,oneof"`
}

func (*StateChange_StateAdd) isStateChange_ChangeOperation() {}

func (*StateChange_StateRemove) isStateChange_ChangeOperation() {}

func (*StateChange_SingletonUpdate) isStateChange_ChangeOperation() {}

func (*StateChange_MapUpdate) isStateChange_ChangeOperation() {}

func (*StateChange_MapDelete) isStateChange_ChangeOperation() {}

func (*StateChange_QueuePush) isStateChange_ChangeOperation() {}

func (*StateChange_QueuePop) isStateChange_ChangeOperation() {}

// *
// An addition of a new named state.
//
// Adding a new named state SHALL only require the name and type.<br/>
// The content of the new state SHALL be filled in via subsequent
// state change items specific to the type of state
// (e.g. SingletonUpdateChange or MapUpdateChange).
type NewStateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The type (e.g. Singleton, Virtual Map, Queue) of state to add.
	StateType     NewStateType `protobuf:"varint,1,opt,name=state_type,json=stateType,proto3,enum=com.hedera.hapi.block.stream.output.NewStateType" json:"state_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewStateChange) Reset() {
	*x = NewStateChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewStateChange) ProtoMessage() {}

func (x *NewStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewStateChange.ProtoReflect.Descriptor instead.
func (*NewStateChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{2}
}

func (x *NewStateChange) GetStateType() NewStateType {
	if x != nil {
		return x.StateType
	}
	return NewStateType_SINGLETON
}

// *
// A removal of a named state.
//
// Removing a named state does not, currently, require additional
// information beyond the state name common to all state changes.<br/>
// A named state, other than a singleton, SHOULD be empty before it is removed.
type RemovedStateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovedStateChange) Reset() {
	*x = RemovedStateChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovedStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovedStateChange) ProtoMessage() {}

func (x *RemovedStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovedStateChange.ProtoReflect.Descriptor instead.
func (*RemovedStateChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{3}
}

// *
// An update to a `Singleton` state.
type SingletonUpdateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to NewValue:
	//
	//	*SingletonUpdateChange_BlockInfoValue
	//	*SingletonUpdateChange_CongestionLevelStartsValue
	//	*SingletonUpdateChange_EntityNumberValue
	//	*SingletonUpdateChange_ExchangeRateSetValue
	//	*SingletonUpdateChange_NetworkStakingRewardsValue
	//	*SingletonUpdateChange_BytesValue
	//	*SingletonUpdateChange_StringValue
	//	*SingletonUpdateChange_RunningHashesValue
	//	*SingletonUpdateChange_ThrottleUsageSnapshotsValue
	//	*SingletonUpdateChange_TimestampValue
	//	*SingletonUpdateChange_BlockStreamInfoValue
	//	*SingletonUpdateChange_PlatformStateValue
	//	*SingletonUpdateChange_RosterStateValue
	NewValue      isSingletonUpdateChange_NewValue `protobuf_oneof:"new_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingletonUpdateChange) Reset() {
	*x = SingletonUpdateChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingletonUpdateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingletonUpdateChange) ProtoMessage() {}

func (x *SingletonUpdateChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingletonUpdateChange.ProtoReflect.Descriptor instead.
func (*SingletonUpdateChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{4}
}

func (x *SingletonUpdateChange) GetNewValue() isSingletonUpdateChange_NewValue {
	if x != nil {
		return x.NewValue
	}
	return nil
}

func (x *SingletonUpdateChange) GetBlockInfoValue() *blockrecords.BlockInfo {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_BlockInfoValue); ok {
			return x.BlockInfoValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetCongestionLevelStartsValue() *congestion.CongestionLevelStarts {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_CongestionLevelStartsValue); ok {
			return x.CongestionLevelStartsValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetEntityNumberValue() *wrapperspb.UInt64Value {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_EntityNumberValue); ok {
			return x.EntityNumberValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetExchangeRateSetValue() *services.ExchangeRateSet {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_ExchangeRateSetValue); ok {
			return x.ExchangeRateSetValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetNetworkStakingRewardsValue() *token.NetworkStakingRewards {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_NetworkStakingRewardsValue); ok {
			return x.NetworkStakingRewardsValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_StringValue); ok {
			return x.StringValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetRunningHashesValue() *blockrecords.RunningHashes {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_RunningHashesValue); ok {
			return x.RunningHashesValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetThrottleUsageSnapshotsValue() *throttles.ThrottleUsageSnapshots {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_ThrottleUsageSnapshotsValue); ok {
			return x.ThrottleUsageSnapshotsValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetTimestampValue() *common.Timestamp {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetBlockStreamInfoValue() *blockstream.BlockStreamInfo {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_BlockStreamInfoValue); ok {
			return x.BlockStreamInfoValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetPlatformStateValue() *state.PlatformState {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_PlatformStateValue); ok {
			return x.PlatformStateValue
		}
	}
	return nil
}

func (x *SingletonUpdateChange) GetRosterStateValue() *roster.RosterState {
	if x != nil {
		if x, ok := x.NewValue.(*SingletonUpdateChange_RosterStateValue); ok {
			return x.RosterStateValue
		}
	}
	return nil
}

type isSingletonUpdateChange_NewValue interface {
	isSingletonUpdateChange_NewValue()
}

type SingletonUpdateChange_BlockInfoValue struct {
	// *
	// A change to the block info singleton.
	// <p>
	// The `BlockInfo` SHALL be updated at the end of every block and
	// SHALL store, among other fields, the last 256 block hash values.
	// <blockquote>REVIEW NOTE<blockquote>
	// The full BlockInfo will be in the state proof, and may not be
	// necessary here.</blockquote></blockquote>
	BlockInfoValue *blockrecords.BlockInfo `protobuf:"bytes,1,opt,name=block_info_value,json=blockInfoValue,proto3,oneof"`
}

type SingletonUpdateChange_CongestionLevelStartsValue struct {
	// *
	// A change to the congestion level starts singleton.
	// <p>
	// This change SHALL be present if congestion level pricing for
	// general fees or gas fees started during the current block.
	CongestionLevelStartsValue *congestion.CongestionLevelStarts `protobuf:"bytes,2,opt,name=congestion_level_starts_value,json=congestionLevelStartsValue,proto3,oneof"`
}

type SingletonUpdateChange_EntityNumberValue struct {
	// *
	// A change to the Entity Identifier singleton.
	// <p>
	// The Entity Identifier singleton SHALL track the highest entity
	// identifier used for the current shard and realm and SHALL be used
	// to issue new entity numbers.
	EntityNumberValue *wrapperspb.UInt64Value `protobuf:"bytes,3,opt,name=entity_number_value,json=entityNumberValue,proto3,oneof"`
}

type SingletonUpdateChange_ExchangeRateSetValue struct {
	// *
	// A change to the exchange rates singleton.
	// <p>
	// This change SHALL be present if the <tt>HBAR&lt;=&gt;USD</tt> exchange
	// rate, as stored in the "midnight rates" singleton changed
	// during the current block.
	ExchangeRateSetValue *services.ExchangeRateSet `protobuf:"bytes,4,opt,name=exchange_rate_set_value,json=exchangeRateSetValue,proto3,oneof"`
}

type SingletonUpdateChange_NetworkStakingRewardsValue struct {
	// *
	// A change to the network staking rewards singleton.
	// <p>
	// Network staking rewards SHALL be updated for every non-empty block.
	NetworkStakingRewardsValue *token.NetworkStakingRewards `protobuf:"bytes,5,opt,name=network_staking_rewards_value,json=networkStakingRewardsValue,proto3,oneof"`
}

type SingletonUpdateChange_BytesValue struct {
	// *
	// A change to a raw byte array singleton.
	// <p>
	// This change SHALL present a change made to a raw byte array
	// singleton.<br/>
	// The "upgrade file hash" state is an example of a raw byte
	// array singleton.
	BytesValue *wrapperspb.BytesValue `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type SingletonUpdateChange_StringValue struct {
	// *
	// A change to a raw string singleton.
	// <p>
	// <dl><dt>Note</dt><dd>There are no current examples of a raw string
	// singleton state.</dd></dl>
	StringValue *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type SingletonUpdateChange_RunningHashesValue struct {
	// *
	// A change to the running hashes singleton.
	// <p>
	// Running hashes SHALL be updated for each transaction.
	// <p>
	// <blockquote>REVIEW NOTE<blockquote>
	// Running hashes is a record stream item. Can it be elided from
	// the block stream? It's not written to the record stream, as far
	// as I can tell. If we do write this it's adding over 144 bytes
	// for every transaction. It's also not clear how we'll calculate
	// this, as it's a hash of the records currently, so it would have
	// to be a hash of the block items, including this one...
	// </blockquote></blockquote>
	RunningHashesValue *blockrecords.RunningHashes `protobuf:"bytes,8,opt,name=running_hashes_value,json=runningHashesValue,proto3,oneof"`
}

type SingletonUpdateChange_ThrottleUsageSnapshotsValue struct {
	// *
	// A change to the throttle usage snapshots singleton.
	// <p>
	// Throttle usage snapshots SHALL be updated for _every transaction_
	// to reflect the amount used for each tps throttle and
	// for the gas throttle.
	ThrottleUsageSnapshotsValue *throttles.ThrottleUsageSnapshots `protobuf:"bytes,9,opt,name=throttle_usage_snapshots_value,json=throttleUsageSnapshotsValue,proto3,oneof"`
}

type SingletonUpdateChange_TimestampValue struct {
	// *
	// A change to a raw `Timestamp` singleton.<br/>
	// An example of a raw `Timestamp` singleton is the
	// "network freeze time" singleton state, which, if set, stores
	// the time for the next scheduled freeze.
	TimestampValue *common.Timestamp `protobuf:"bytes,10,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type SingletonUpdateChange_BlockStreamInfoValue struct {
	// *
	// A change to the block stream status singleton.
	// <p>
	// This MUST be updated at the beginning of a block, with the
	// information for the immediately prior block.
	BlockStreamInfoValue *blockstream.BlockStreamInfo `protobuf:"bytes,11,opt,name=block_stream_info_value,json=blockStreamInfoValue,proto3,oneof"`
}

type SingletonUpdateChange_PlatformStateValue struct {
	// *
	// A change to the platform state singleton.
	PlatformStateValue *state.PlatformState `protobuf:"bytes,12,opt,name=platform_state_value,json=platformStateValue,proto3,oneof"`
}

type SingletonUpdateChange_RosterStateValue struct {
	// *
	// A change to the roster state singleton.
	RosterStateValue *roster.RosterState `protobuf:"bytes,13,opt,name=roster_state_value,json=rosterStateValue,proto3,oneof"`
}

func (*SingletonUpdateChange_BlockInfoValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_CongestionLevelStartsValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_EntityNumberValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_ExchangeRateSetValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_NetworkStakingRewardsValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_BytesValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_StringValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_RunningHashesValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_ThrottleUsageSnapshotsValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_TimestampValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_BlockStreamInfoValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_PlatformStateValue) isSingletonUpdateChange_NewValue() {}

func (*SingletonUpdateChange_RosterStateValue) isSingletonUpdateChange_NewValue() {}

// *
// An update to a single item in a `VirtualMap`.<br/>
// Each update consists of a "key" and a "value".
// Keys are often identifiers or scalar values.
// Values are generally full messages or byte arrays.
//
// The key presented here is not mutable, we do not update map keys.<br/>
// The value associated to the key provided is updated, or the value is
// added and associated with that key.<br/>
// A change of key would be expressed as removal of the prior key and
// an addition for the new key.
type MapUpdateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A key in a virtual map.
	// <p>
	// This key MUST be mapped to the value added or updated.<br/>
	// This field is REQUIRED.
	Key *MapChangeKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// *
	// A value in a virtual map.
	// <p>
	// This value MUST correctly represent the state of the map entry
	// _after_ the asserted update.<br/>
	// This value MAY be reduced to only transmit fields that differ
	// from the prior state.<br/>
	// This field is REQUIRED.
	Value         *MapChangeValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapUpdateChange) Reset() {
	*x = MapUpdateChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapUpdateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapUpdateChange) ProtoMessage() {}

func (x *MapUpdateChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapUpdateChange.ProtoReflect.Descriptor instead.
func (*MapUpdateChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{5}
}

func (x *MapUpdateChange) GetKey() *MapChangeKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MapUpdateChange) GetValue() *MapChangeValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// *
// A removal of a single item from a `VirtualMap`.
type MapDeleteChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A key in a virtual map.
	// <p>
	// This key SHALL be removed.<br/>
	// The mapped value SHALL also be removed.<br/>
	// This field is REQUIRED.
	Key           *MapChangeKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDeleteChange) Reset() {
	*x = MapDeleteChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDeleteChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDeleteChange) ProtoMessage() {}

func (x *MapDeleteChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDeleteChange.ProtoReflect.Descriptor instead.
func (*MapDeleteChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{6}
}

func (x *MapDeleteChange) GetKey() *MapChangeKey {
	if x != nil {
		return x.Key
	}
	return nil
}

// *
// A key identifying a specific entry in a key-value "virtual map".
type MapChangeKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to KeyChoice:
	//
	//	*MapChangeKey_AccountIdKey
	//	*MapChangeKey_TokenRelationshipKey
	//	*MapChangeKey_EntityNumberKey
	//	*MapChangeKey_FileIdKey
	//	*MapChangeKey_NftIdKey
	//	*MapChangeKey_ProtoBytesKey
	//	*MapChangeKey_ProtoLongKey
	//	*MapChangeKey_ProtoStringKey
	//	*MapChangeKey_ScheduleIdKey
	//	*MapChangeKey_SlotKeyKey
	//	*MapChangeKey_TokenIdKey
	//	*MapChangeKey_TopicIdKey
	//	*MapChangeKey_ContractIdKey
	//	*MapChangeKey_PendingAirdropIdKey
	KeyChoice     isMapChangeKey_KeyChoice `protobuf_oneof:"key_choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChangeKey) Reset() {
	*x = MapChangeKey{}
	mi := &file_stream_output_state_changes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChangeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChangeKey) ProtoMessage() {}

func (x *MapChangeKey) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChangeKey.ProtoReflect.Descriptor instead.
func (*MapChangeKey) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{7}
}

func (x *MapChangeKey) GetKeyChoice() isMapChangeKey_KeyChoice {
	if x != nil {
		return x.KeyChoice
	}
	return nil
}

func (x *MapChangeKey) GetAccountIdKey() *common.AccountID {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_AccountIdKey); ok {
			return x.AccountIdKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetTokenRelationshipKey() *common.TokenAssociation {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_TokenRelationshipKey); ok {
			return x.TokenRelationshipKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetEntityNumberKey() *wrapperspb.UInt64Value {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_EntityNumberKey); ok {
			return x.EntityNumberKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetFileIdKey() *common.FileID {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_FileIdKey); ok {
			return x.FileIdKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetNftIdKey() *common.NftID {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_NftIdKey); ok {
			return x.NftIdKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetProtoBytesKey() *wrapperspb.BytesValue {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_ProtoBytesKey); ok {
			return x.ProtoBytesKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetProtoLongKey() *wrapperspb.Int64Value {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_ProtoLongKey); ok {
			return x.ProtoLongKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetProtoStringKey() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_ProtoStringKey); ok {
			return x.ProtoStringKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetScheduleIdKey() *common.ScheduleID {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_ScheduleIdKey); ok {
			return x.ScheduleIdKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetSlotKeyKey() *contract.SlotKey {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_SlotKeyKey); ok {
			return x.SlotKeyKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetTokenIdKey() *common.TokenID {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_TokenIdKey); ok {
			return x.TokenIdKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetTopicIdKey() *common.TopicID {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_TopicIdKey); ok {
			return x.TopicIdKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetContractIdKey() *common.ContractID {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_ContractIdKey); ok {
			return x.ContractIdKey
		}
	}
	return nil
}

func (x *MapChangeKey) GetPendingAirdropIdKey() *common.PendingAirdropId {
	if x != nil {
		if x, ok := x.KeyChoice.(*MapChangeKey_PendingAirdropIdKey); ok {
			return x.PendingAirdropIdKey
		}
	}
	return nil
}

type isMapChangeKey_KeyChoice interface {
	isMapChangeKey_KeyChoice()
}

type MapChangeKey_AccountIdKey struct {
	// *
	// A key for a change affecting a map keyed by an Account identifier.
	AccountIdKey *common.AccountID `protobuf:"bytes,1,opt,name=account_id_key,json=accountIdKey,proto3,oneof"`
}

type MapChangeKey_TokenRelationshipKey struct {
	// *
	// A change to the token relationships virtual map.<br/>
	// This map is keyed by the pair of account identifier and
	// token identifier.
	TokenRelationshipKey *common.TokenAssociation `protobuf:"bytes,2,opt,name=token_relationship_key,json=tokenRelationshipKey,proto3,oneof"`
}

type MapChangeKey_EntityNumberKey struct {
	// *
	// A change to a map keyed by an EntityNumber (which is a whole number).
	// <p>
	// This SHOULD NOT be used. Virtual maps SHOULD be keyed to
	// full identifiers that include shard and realm information.
	EntityNumberKey *wrapperspb.UInt64Value `protobuf:"bytes,3,opt,name=entity_number_key,json=entityNumberKey,proto3,oneof"`
}

type MapChangeKey_FileIdKey struct {
	// *
	// A change to a virtual map keyed by File identifier.
	FileIdKey *common.FileID `protobuf:"bytes,4,opt,name=file_id_key,json=fileIdKey,proto3,oneof"`
}

type MapChangeKey_NftIdKey struct {
	// *
	// A change to a virtual map keyed by NFT identifier.
	NftIdKey *common.NftID `protobuf:"bytes,5,opt,name=nft_id_key,json=nftIdKey,proto3,oneof"`
}

type MapChangeKey_ProtoBytesKey struct {
	// *
	// A change to a virtual map keyed by a byte array.
	ProtoBytesKey *wrapperspb.BytesValue `protobuf:"bytes,6,opt,name=proto_bytes_key,json=protoBytesKey,proto3,oneof"`
}

type MapChangeKey_ProtoLongKey struct {
	// *
	// A change to a virtual map keyed by an int64 value.
	ProtoLongKey *wrapperspb.Int64Value `protobuf:"bytes,7,opt,name=proto_long_key,json=protoLongKey,proto3,oneof"`
}

type MapChangeKey_ProtoStringKey struct {
	// *
	// A change to a virtual map keyed by a string value.
	ProtoStringKey *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=proto_string_key,json=protoStringKey,proto3,oneof"`
}

type MapChangeKey_ScheduleIdKey struct {
	// *
	// A change to a virtual map keyed by a Schedule identifier.
	ScheduleIdKey *common.ScheduleID `protobuf:"bytes,9,opt,name=schedule_id_key,json=scheduleIdKey,proto3,oneof"`
}

type MapChangeKey_SlotKeyKey struct {
	// *
	// A change to the EVM storage "slot" virtual map.
	SlotKeyKey *contract.SlotKey `protobuf:"bytes,10,opt,name=slot_key_key,json=slotKeyKey,proto3,oneof"`
}

type MapChangeKey_TokenIdKey struct {
	// *
	// A change to a virtual map keyed by a Token identifier.
	TokenIdKey *common.TokenID `protobuf:"bytes,11,opt,name=token_id_key,json=tokenIdKey,proto3,oneof"`
}

type MapChangeKey_TopicIdKey struct {
	// *
	// A change to a virtual map keyed by a Topic identifier.
	TopicIdKey *common.TopicID `protobuf:"bytes,12,opt,name=topic_id_key,json=topicIdKey,proto3,oneof"`
}

type MapChangeKey_ContractIdKey struct {
	// *
	// A change to a virtual map keyed by contract id identifier.
	ContractIdKey *common.ContractID `protobuf:"bytes,13,opt,name=contract_id_key,json=contractIdKey,proto3,oneof"`
}

type MapChangeKey_PendingAirdropIdKey struct {
	// *
	// A change to a virtual map keyed by pending airdrop id identifier.
	PendingAirdropIdKey *common.PendingAirdropId `protobuf:"bytes,14,opt,name=pending_airdrop_id_key,json=pendingAirdropIdKey,proto3,oneof"`
}

func (*MapChangeKey_AccountIdKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_TokenRelationshipKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_EntityNumberKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_FileIdKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_NftIdKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_ProtoBytesKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_ProtoLongKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_ProtoStringKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_ScheduleIdKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_SlotKeyKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_TokenIdKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_TopicIdKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_ContractIdKey) isMapChangeKey_KeyChoice() {}

func (*MapChangeKey_PendingAirdropIdKey) isMapChangeKey_KeyChoice() {}

// *
// A value updated in, or added to, a virtual map.
type MapChangeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ValueChoice:
	//
	//	*MapChangeValue_AccountValue
	//	*MapChangeValue_AccountIdValue
	//	*MapChangeValue_BytecodeValue
	//	*MapChangeValue_FileValue
	//	*MapChangeValue_NftValue
	//	*MapChangeValue_ProtoStringValue
	//	*MapChangeValue_ScheduleValue
	//	*MapChangeValue_ScheduleListValue
	//	*MapChangeValue_SlotValueValue
	//	*MapChangeValue_StakingNodeInfoValue
	//	*MapChangeValue_TokenValue
	//	*MapChangeValue_TokenRelationValue
	//	*MapChangeValue_TopicValue
	//	*MapChangeValue_NodeValue
	//	*MapChangeValue_AccountPendingAirdropValue
	//	*MapChangeValue_RosterValue
	ValueChoice   isMapChangeValue_ValueChoice `protobuf_oneof:"value_choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChangeValue) Reset() {
	*x = MapChangeValue{}
	mi := &file_stream_output_state_changes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChangeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChangeValue) ProtoMessage() {}

func (x *MapChangeValue) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChangeValue.ProtoReflect.Descriptor instead.
func (*MapChangeValue) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{8}
}

func (x *MapChangeValue) GetValueChoice() isMapChangeValue_ValueChoice {
	if x != nil {
		return x.ValueChoice
	}
	return nil
}

func (x *MapChangeValue) GetAccountValue() *token.Account {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_AccountValue); ok {
			return x.AccountValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetAccountIdValue() *common.AccountID {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_AccountIdValue); ok {
			return x.AccountIdValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetBytecodeValue() *contract.Bytecode {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_BytecodeValue); ok {
			return x.BytecodeValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetFileValue() *file.File {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_FileValue); ok {
			return x.FileValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetNftValue() *token.Nft {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_NftValue); ok {
			return x.NftValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetProtoStringValue() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_ProtoStringValue); ok {
			return x.ProtoStringValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetScheduleValue() *schedule.Schedule {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_ScheduleValue); ok {
			return x.ScheduleValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetScheduleListValue() *schedule.ScheduleList {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_ScheduleListValue); ok {
			return x.ScheduleListValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetSlotValueValue() *contract.SlotValue {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_SlotValueValue); ok {
			return x.SlotValueValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetStakingNodeInfoValue() *token.StakingNodeInfo {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_StakingNodeInfoValue); ok {
			return x.StakingNodeInfoValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetTokenValue() *token.Token {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_TokenValue); ok {
			return x.TokenValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetTokenRelationValue() *token.TokenRelation {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_TokenRelationValue); ok {
			return x.TokenRelationValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetTopicValue() *consensus.Topic {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_TopicValue); ok {
			return x.TopicValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetNodeValue() *addressbook.Node {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_NodeValue); ok {
			return x.NodeValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetAccountPendingAirdropValue() *token.AccountPendingAirdrop {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_AccountPendingAirdropValue); ok {
			return x.AccountPendingAirdropValue
		}
	}
	return nil
}

func (x *MapChangeValue) GetRosterValue() *roster.Roster {
	if x != nil {
		if x, ok := x.ValueChoice.(*MapChangeValue_RosterValue); ok {
			return x.RosterValue
		}
	}
	return nil
}

type isMapChangeValue_ValueChoice interface {
	isMapChangeValue_ValueChoice()
}

type MapChangeValue_AccountValue struct {
	// *
	// An account value.
	AccountValue *token.Account `protobuf:"bytes,1,opt,name=account_value,json=accountValue,proto3,oneof"`
}

type MapChangeValue_AccountIdValue struct {
	// *
	// An account identifier.<br/>
	// In some cases a map is used to connect a value or identifier
	// to another identifier.
	AccountIdValue *common.AccountID `protobuf:"bytes,2,opt,name=account_id_value,json=accountIdValue,proto3,oneof"`
}

type MapChangeValue_BytecodeValue struct {
	// *
	// Compiled EVM bytecode.
	BytecodeValue *contract.Bytecode `protobuf:"bytes,3,opt,name=bytecode_value,json=bytecodeValue,proto3,oneof"`
}

type MapChangeValue_FileValue struct {
	// *
	// An Hedera "file" value.
	// <p>
	// <blockquote>REVIEW NOTE<blockquote>
	// A file can become quite large (up to 1048576 bytes).<br/>
	// Do we want to structure file changes separately?<br/>
	// Perhaps a file metadata update and a separate byte array for
	// just the bytes appended (or initial bytes on create). We only
	// allow create/append/delete, so the separate byte array would work
	// and keep the size below 6K per state change.
	// </blockquote></blockquote>
	FileValue *file.File `protobuf:"bytes,4,opt,name=file_value,json=fileValue,proto3,oneof"`
}

type MapChangeValue_NftValue struct {
	// *
	// A non-fungible/unique token value.
	NftValue *token.Nft `protobuf:"bytes,5,opt,name=nft_value,json=nftValue,proto3,oneof"`
}

type MapChangeValue_ProtoStringValue struct {
	// *
	// A string value.
	ProtoStringValue *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=proto_string_value,json=protoStringValue,proto3,oneof"`
}

type MapChangeValue_ScheduleValue struct {
	// *
	// A scheduled transaction value.
	ScheduleValue *schedule.Schedule `protobuf:"bytes,7,opt,name=schedule_value,json=scheduleValue,proto3,oneof"`
}

type MapChangeValue_ScheduleListValue struct {
	// *
	// A list of scheduled transactions.<br/>
	// An example for this value is the map of consensus second to
	// scheduled transactions that expire at that consensus time.
	ScheduleListValue *schedule.ScheduleList `protobuf:"bytes,8,opt,name=schedule_list_value,json=scheduleListValue,proto3,oneof"`
}

type MapChangeValue_SlotValueValue struct {
	// *
	// An EVM storage slot value.
	SlotValueValue *contract.SlotValue `protobuf:"bytes,9,opt,name=slot_value_value,json=slotValueValue,proto3,oneof"`
}

type MapChangeValue_StakingNodeInfoValue struct {
	// *
	// An updated set of staking information for all nodes in
	// the address book.
	StakingNodeInfoValue *token.StakingNodeInfo `protobuf:"bytes,10,opt,name=staking_node_info_value,json=stakingNodeInfoValue,proto3,oneof"`
}

type MapChangeValue_TokenValue struct {
	// *
	// An HTS token value.
	TokenValue *token.Token `protobuf:"bytes,11,opt,name=token_value,json=tokenValue,proto3,oneof"`
}

type MapChangeValue_TokenRelationValue struct {
	// *
	// A token relationship value.<br/>
	// These values track which accounts are willing to transact
	// in specific HTS tokens.
	TokenRelationValue *token.TokenRelation `protobuf:"bytes,12,opt,name=token_relation_value,json=tokenRelationValue,proto3,oneof"`
}

type MapChangeValue_TopicValue struct {
	// *
	// An HCS topic value.
	TopicValue *consensus.Topic `protobuf:"bytes,13,opt,name=topic_value,json=topicValue,proto3,oneof"`
}

type MapChangeValue_NodeValue struct {
	// *
	// An network node value.
	NodeValue *addressbook.Node `protobuf:"bytes,14,opt,name=node_value,json=nodeValue,proto3,oneof"`
}

type MapChangeValue_AccountPendingAirdropValue struct {
	// *
	// A pending airdrop value.
	AccountPendingAirdropValue *token.AccountPendingAirdrop `protobuf:"bytes,15,opt,name=account_pending_airdrop_value,json=accountPendingAirdropValue,proto3,oneof"`
}

type MapChangeValue_RosterValue struct {
	// *
	// A roster value.
	RosterValue *roster.Roster `protobuf:"bytes,16,opt,name=roster_value,json=rosterValue,proto3,oneof"`
}

func (*MapChangeValue_AccountValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_AccountIdValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_BytecodeValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_FileValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_NftValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_ProtoStringValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_ScheduleValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_ScheduleListValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_SlotValueValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_StakingNodeInfoValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_TokenValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_TokenRelationValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_TopicValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_NodeValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_AccountPendingAirdropValue) isMapChangeValue_ValueChoice() {}

func (*MapChangeValue_RosterValue) isMapChangeValue_ValueChoice() {}

// *
// Addition of an item to a `Queue` state.<br/>
//
// The new item SHALL be added after the current "last" element in the
// queue.<br/>
// The new item MUST be the same type of value as all other items in the queue.
type QueuePushChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*QueuePushChange_ProtoBytesElement
	//	*QueuePushChange_ProtoStringElement
	//	*QueuePushChange_TransactionReceiptEntriesElement
	Value         isQueuePushChange_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuePushChange) Reset() {
	*x = QueuePushChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuePushChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePushChange) ProtoMessage() {}

func (x *QueuePushChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePushChange.ProtoReflect.Descriptor instead.
func (*QueuePushChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{9}
}

func (x *QueuePushChange) GetValue() isQueuePushChange_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *QueuePushChange) GetProtoBytesElement() *wrapperspb.BytesValue {
	if x != nil {
		if x, ok := x.Value.(*QueuePushChange_ProtoBytesElement); ok {
			return x.ProtoBytesElement
		}
	}
	return nil
}

func (x *QueuePushChange) GetProtoStringElement() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.Value.(*QueuePushChange_ProtoStringElement); ok {
			return x.ProtoStringElement
		}
	}
	return nil
}

func (x *QueuePushChange) GetTransactionReceiptEntriesElement() *recordcache.TransactionReceiptEntries {
	if x != nil {
		if x, ok := x.Value.(*QueuePushChange_TransactionReceiptEntriesElement); ok {
			return x.TransactionReceiptEntriesElement
		}
	}
	return nil
}

type isQueuePushChange_Value interface {
	isQueuePushChange_Value()
}

type QueuePushChange_ProtoBytesElement struct {
	// *
	// A byte array added to the queue state.
	ProtoBytesElement *wrapperspb.BytesValue `protobuf:"bytes,1,opt,name=proto_bytes_element,json=protoBytesElement,proto3,oneof"`
}

type QueuePushChange_ProtoStringElement struct {
	// *
	// A string added to the queue state.
	ProtoStringElement *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=proto_string_element,json=protoStringElement,proto3,oneof"`
}

type QueuePushChange_TransactionReceiptEntriesElement struct {
	// *
	// All transaction receipts for a round added to queue state.
	TransactionReceiptEntriesElement *recordcache.TransactionReceiptEntries `protobuf:"bytes,3,opt,name=transaction_receipt_entries_element,json=transactionReceiptEntriesElement,proto3,oneof"`
}

func (*QueuePushChange_ProtoBytesElement) isQueuePushChange_Value() {}

func (*QueuePushChange_ProtoStringElement) isQueuePushChange_Value() {}

func (*QueuePushChange_TransactionReceiptEntriesElement) isQueuePushChange_Value() {}

// *
// Removal of an item from a `Queue` state.<br/>
//
// The item removed SHALL be the current "front" (or "head") of the queue.<br/>
// Removing from a queue "head" does not, currently, require additional
// information beyond the state name common to all state changes.
type QueuePopChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuePopChange) Reset() {
	*x = QueuePopChange{}
	mi := &file_stream_output_state_changes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuePopChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePopChange) ProtoMessage() {}

func (x *QueuePopChange) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_state_changes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePopChange.ProtoReflect.Descriptor instead.
func (*QueuePopChange) Descriptor() ([]byte, []int) {
	return file_stream_output_state_changes_proto_rawDescGZIP(), []int{10}
}

var File_stream_output_state_changes_proto protoreflect.FileDescriptor

const file_stream_output_state_changes_proto_rawDesc = "" +
	"\n" +
	"!stream/output/state_changes.proto\x12#com.hedera.hapi.block.stream.output\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11basic_types.proto\x1a\x13exchange_rate.proto\x1a\x1cstate/addressbook/node.proto\x1a#state/blockrecords/block_info.proto\x1a'state/blockrecords/running_hashes.proto\x1a)state/blockstream/block_stream_info.proto\x1a.state/congestion/congestion_level_starts.proto\x1a\x1bstate/consensus/topic.proto\x1a\x1dstate/contract/bytecode.proto\x1a!state/contract/storage_slot.proto\x1a\x15state/file/file.proto\x1a#state/recordcache/recordcache.proto\x1a\x19state/roster/roster.proto\x1a\x1fstate/roster/roster_state.proto\x1a\x1dstate/schedule/schedule.proto\x1a.state/throttles/throttle_usage_snapshots.proto\x1a\x19state/token/account.proto\x1a)state/token/account_pending_airdrop.proto\x1a)state/token/network_staking_rewards.proto\x1a\x15state/token/nft.proto\x1a#state/token/staking_node_info.proto\x1a\x17state/token/token.proto\x1a state/token/token_relation.proto\x1a\x1astate/platform_state.proto\x1a\x0ftimestamp.proto\"\xa8\x01\n" +
	"\fStateChanges\x12A\n" +
	"\x13consensus_timestamp\x18\x01 \x01(\v2\x10.proto.TimestampR\x12consensusTimestamp\x12U\n" +
	"\rstate_changes\x18\x02 \x03(\v20.com.hedera.hapi.block.stream.output.StateChangeR\fstateChanges\"\xb0\x05\n" +
	"\vStateChange\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\rR\astateId\x12R\n" +
	"\tstate_add\x18\x02 \x01(\v23.com.hedera.hapi.block.stream.output.NewStateChangeH\x00R\bstateAdd\x12\\\n" +
	"\fstate_remove\x18\x03 \x01(\v27.com.hedera.hapi.block.stream.output.RemovedStateChangeH\x00R\vstateRemove\x12g\n" +
	"\x10singleton_update\x18\x04 \x01(\v2:.com.hedera.hapi.block.stream.output.SingletonUpdateChangeH\x00R\x0fsingletonUpdate\x12U\n" +
	"\n" +
	"map_update\x18\x05 \x01(\v24.com.hedera.hapi.block.stream.output.MapUpdateChangeH\x00R\tmapUpdate\x12U\n" +
	"\n" +
	"map_delete\x18\x06 \x01(\v24.com.hedera.hapi.block.stream.output.MapDeleteChangeH\x00R\tmapDelete\x12U\n" +
	"\n" +
	"queue_push\x18\a \x01(\v24.com.hedera.hapi.block.stream.output.QueuePushChangeH\x00R\tqueuePush\x12R\n" +
	"\tqueue_pop\x18\b \x01(\v23.com.hedera.hapi.block.stream.output.QueuePopChangeH\x00R\bqueuePopB\x12\n" +
	"\x10change_operation\"b\n" +
	"\x0eNewStateChange\x12P\n" +
	"\n" +
	"state_type\x18\x01 \x01(\x0e21.com.hedera.hapi.block.stream.output.NewStateTypeR\tstateType\"\x14\n" +
	"\x12RemovedStateChange\"\xee\b\n" +
	"\x15SingletonUpdateChange\x12<\n" +
	"\x10block_info_value\x18\x01 \x01(\v2\x10.proto.BlockInfoH\x00R\x0eblockInfoValue\x12a\n" +
	"\x1dcongestion_level_starts_value\x18\x02 \x01(\v2\x1c.proto.CongestionLevelStartsH\x00R\x1acongestionLevelStartsValue\x12N\n" +
	"\x13entity_number_value\x18\x03 \x01(\v2\x1c.google.protobuf.UInt64ValueH\x00R\x11entityNumberValue\x12O\n" +
	"\x17exchange_rate_set_value\x18\x04 \x01(\v2\x16.proto.ExchangeRateSetH\x00R\x14exchangeRateSetValue\x12a\n" +
	"\x1dnetwork_staking_rewards_value\x18\x05 \x01(\v2\x1c.proto.NetworkStakingRewardsH\x00R\x1anetworkStakingRewardsValue\x12>\n" +
	"\vbytes_value\x18\x06 \x01(\v2\x1b.google.protobuf.BytesValueH\x00R\n" +
	"bytesValue\x12A\n" +
	"\fstring_value\x18\a \x01(\v2\x1c.google.protobuf.StringValueH\x00R\vstringValue\x12H\n" +
	"\x14running_hashes_value\x18\b \x01(\v2\x14.proto.RunningHashesH\x00R\x12runningHashesValue\x12d\n" +
	"\x1ethrottle_usage_snapshots_value\x18\t \x01(\v2\x1d.proto.ThrottleUsageSnapshotsH\x00R\x1bthrottleUsageSnapshotsValue\x12;\n" +
	"\x0ftimestamp_value\x18\n" +
	" \x01(\v2\x10.proto.TimestampH\x00R\x0etimestampValue\x12p\n" +
	"\x17block_stream_info_value\x18\v \x01(\v27.com.hedera.hapi.node.state.blockstream.BlockStreamInfoH\x00R\x14blockStreamInfoValue\x12a\n" +
	"\x14platform_state_value\x18\f \x01(\v2-.com.hedera.hapi.platform.state.PlatformStateH\x00R\x12platformStateValue\x12^\n" +
	"\x12roster_state_value\x18\r \x01(\v2..com.hedera.hapi.node.state.roster.RosterStateH\x00R\x10rosterStateValueB\v\n" +
	"\tnew_value\"\xa1\x01\n" +
	"\x0fMapUpdateChange\x12C\n" +
	"\x03key\x18\x01 \x01(\v21.com.hedera.hapi.block.stream.output.MapChangeKeyR\x03key\x12I\n" +
	"\x05value\x18\x02 \x01(\v23.com.hedera.hapi.block.stream.output.MapChangeValueR\x05value\"V\n" +
	"\x0fMapDeleteChange\x12C\n" +
	"\x03key\x18\x01 \x01(\v21.com.hedera.hapi.block.stream.output.MapChangeKeyR\x03key\"\x8e\a\n" +
	"\fMapChangeKey\x128\n" +
	"\x0eaccount_id_key\x18\x01 \x01(\v2\x10.proto.AccountIDH\x00R\faccountIdKey\x12O\n" +
	"\x16token_relationship_key\x18\x02 \x01(\v2\x17.proto.TokenAssociationH\x00R\x14tokenRelationshipKey\x12J\n" +
	"\x11entity_number_key\x18\x03 \x01(\v2\x1c.google.protobuf.UInt64ValueH\x00R\x0fentityNumberKey\x12/\n" +
	"\vfile_id_key\x18\x04 \x01(\v2\r.proto.FileIDH\x00R\tfileIdKey\x12,\n" +
	"\n" +
	"nft_id_key\x18\x05 \x01(\v2\f.proto.NftIDH\x00R\bnftIdKey\x12E\n" +
	"\x0fproto_bytes_key\x18\x06 \x01(\v2\x1b.google.protobuf.BytesValueH\x00R\rprotoBytesKey\x12C\n" +
	"\x0eproto_long_key\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueH\x00R\fprotoLongKey\x12H\n" +
	"\x10proto_string_key\x18\b \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x0eprotoStringKey\x12;\n" +
	"\x0fschedule_id_key\x18\t \x01(\v2\x11.proto.ScheduleIDH\x00R\rscheduleIdKey\x122\n" +
	"\fslot_key_key\x18\n" +
	" \x01(\v2\x0e.proto.SlotKeyH\x00R\n" +
	"slotKeyKey\x122\n" +
	"\ftoken_id_key\x18\v \x01(\v2\x0e.proto.TokenIDH\x00R\n" +
	"tokenIdKey\x122\n" +
	"\ftopic_id_key\x18\f \x01(\v2\x0e.proto.TopicIDH\x00R\n" +
	"topicIdKey\x12;\n" +
	"\x0fcontract_id_key\x18\r \x01(\v2\x11.proto.ContractIDH\x00R\rcontractIdKey\x12N\n" +
	"\x16pending_airdrop_id_key\x18\x0e \x01(\v2\x17.proto.PendingAirdropIdH\x00R\x13pendingAirdropIdKeyB\f\n" +
	"\n" +
	"key_choice\"\xb4\b\n" +
	"\x0eMapChangeValue\x125\n" +
	"\raccount_value\x18\x01 \x01(\v2\x0e.proto.AccountH\x00R\faccountValue\x12<\n" +
	"\x10account_id_value\x18\x02 \x01(\v2\x10.proto.AccountIDH\x00R\x0eaccountIdValue\x128\n" +
	"\x0ebytecode_value\x18\x03 \x01(\v2\x0f.proto.BytecodeH\x00R\rbytecodeValue\x12,\n" +
	"\n" +
	"file_value\x18\x04 \x01(\v2\v.proto.FileH\x00R\tfileValue\x12)\n" +
	"\tnft_value\x18\x05 \x01(\v2\n" +
	".proto.NftH\x00R\bnftValue\x12L\n" +
	"\x12proto_string_value\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x10protoStringValue\x128\n" +
	"\x0eschedule_value\x18\a \x01(\v2\x0f.proto.ScheduleH\x00R\rscheduleValue\x12E\n" +
	"\x13schedule_list_value\x18\b \x01(\v2\x13.proto.ScheduleListH\x00R\x11scheduleListValue\x12<\n" +
	"\x10slot_value_value\x18\t \x01(\v2\x10.proto.SlotValueH\x00R\x0eslotValueValue\x12O\n" +
	"\x17staking_node_info_value\x18\n" +
	" \x01(\v2\x16.proto.StakingNodeInfoH\x00R\x14stakingNodeInfoValue\x12/\n" +
	"\vtoken_value\x18\v \x01(\v2\f.proto.TokenH\x00R\n" +
	"tokenValue\x12H\n" +
	"\x14token_relation_value\x18\f \x01(\v2\x14.proto.TokenRelationH\x00R\x12tokenRelationValue\x12/\n" +
	"\vtopic_value\x18\r \x01(\v2\f.proto.TopicH\x00R\n" +
	"topicValue\x12M\n" +
	"\n" +
	"node_value\x18\x0e \x01(\v2,.com.hedera.hapi.node.state.addressbook.NodeH\x00R\tnodeValue\x12a\n" +
	"\x1daccount_pending_airdrop_value\x18\x0f \x01(\v2\x1c.proto.AccountPendingAirdropH\x00R\x1aaccountPendingAirdropValue\x12N\n" +
	"\froster_value\x18\x10 \x01(\v2).com.hedera.hapi.node.state.roster.RosterH\x00R\vrosterValueB\x0e\n" +
	"\fvalue_choice\"\xae\x02\n" +
	"\x0fQueuePushChange\x12M\n" +
	"\x13proto_bytes_element\x18\x01 \x01(\v2\x1b.google.protobuf.BytesValueH\x00R\x11protoBytesElement\x12P\n" +
	"\x14proto_string_element\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x12protoStringElement\x12q\n" +
	"#transaction_receipt_entries_element\x18\x03 \x01(\v2 .proto.TransactionReceiptEntriesH\x00R transactionReceiptEntriesElementB\a\n" +
	"\x05value\"\x10\n" +
	"\x0eQueuePopChange*\x90\t\n" +
	"\x0fStateIdentifier\x12\x13\n" +
	"\x0fSTATE_ID_TOPICS\x10\x00\x12\x16\n" +
	"\x12STATE_ID_ENTITY_ID\x10\x01\x12\x15\n" +
	"\x11STATE_ID_ACCOUNTS\x10\x02\x12\x14\n" +
	"\x10STATE_ID_ALIASES\x10\x03\x12\x1d\n" +
	"\x19STATE_ID_CONTRACT_STORAGE\x10\x04\x12\x1e\n" +
	"\x1aSTATE_ID_CONTRACT_BYTECODE\x10\x05\x12\x12\n" +
	"\x0eSTATE_ID_FILES\x10\x06\x12\x13\n" +
	"\x0fSTATE_ID_TOKENS\x10\a\x12\x11\n" +
	"\rSTATE_ID_NFTS\x10\b\x12\x1c\n" +
	"\x18STATE_ID_TOKEN_RELATIONS\x10\t\x12\x19\n" +
	"\x15STATE_ID_STAKING_INFO\x10\n" +
	"\x12\x1c\n" +
	"\x18STATE_ID_NETWORK_REWARDS\x10\v\x12\x1b\n" +
	"\x17STATE_ID_THROTTLE_USAGE\x10\f\x12\x1e\n" +
	"\x1aSTATE_ID_CONGESTION_STARTS\x10\r\x12\x1c\n" +
	"\x18STATE_ID_SCHEDULES_BY_ID\x10\x0e\x12 \n" +
	"\x1cSTATE_ID_SCHEDULES_BY_EXPIRY\x10\x0f\x12\"\n" +
	"\x1eSTATE_ID_SCHEDULES_BY_EQUALITY\x10\x10\x12\x1b\n" +
	"\x17STATE_ID_MIDNIGHT_RATES\x10\x11\x12\x1b\n" +
	"\x17STATE_ID_RUNNING_HASHES\x10\x12\x12\x17\n" +
	"\x13STATE_ID_BLOCK_INFO\x10\x13\x12\x12\n" +
	"\x0eSTATE_ID_NODES\x10\x14\x12\x19\n" +
	"\x15STATE_ID_UPGRADE_FILE\x10\x15\x12\x1e\n" +
	"\x1aSTATE_ID_UPGRADE_FILE_HASH\x10\x16\x12\x18\n" +
	"\x14STATE_ID_FREEZE_TIME\x10\x17\x12\x1e\n" +
	"\x1aSTATE_ID_BLOCK_STREAM_INFO\x10\x18\x12\x1d\n" +
	"\x19STATE_ID_PENDING_AIRDROPS\x10\x19\x12\x1b\n" +
	"\x17STATE_ID_PLATFORM_STATE\x10\x1a\x12\x19\n" +
	"\x15STATE_ID_ROSTER_STATE\x10\x1b\x12\x14\n" +
	"\x10STATE_ID_ROSTERS\x10\x1c\x12'\n" +
	"#STATE_ID_TRANSACTION_RECEIPTS_QUEUE\x10~\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_150\x10\x91N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_151\x10\x92N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_152\x10\x93N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_153\x10\x94N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_154\x10\x95N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_155\x10\x96N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_156\x10\x97N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_157\x10\x98N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_158\x10\x99N\x12\x1e\n" +
	"\x19STATE_ID_UPGRADE_DATA_159\x10\x9aN*9\n" +
	"\fNewStateType\x12\r\n" +
	"\tSINGLETON\x10\x00\x12\x0f\n" +
	"\vVIRTUAL_MAP\x10\x01\x12\t\n" +
	"\x05QUEUE\x10\x02Bm\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z=github.com/cordialsys/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_state_changes_proto_rawDescOnce sync.Once
	file_stream_output_state_changes_proto_rawDescData []byte
)

func file_stream_output_state_changes_proto_rawDescGZIP() []byte {
	file_stream_output_state_changes_proto_rawDescOnce.Do(func() {
		file_stream_output_state_changes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_state_changes_proto_rawDesc), len(file_stream_output_state_changes_proto_rawDesc)))
	})
	return file_stream_output_state_changes_proto_rawDescData
}

var file_stream_output_state_changes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stream_output_state_changes_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_stream_output_state_changes_proto_goTypes = []any{
	(StateIdentifier)(0),                          // 0: com.hedera.hapi.block.stream.output.StateIdentifier
	(NewStateType)(0),                             // 1: com.hedera.hapi.block.stream.output.NewStateType
	(*StateChanges)(nil),                          // 2: com.hedera.hapi.block.stream.output.StateChanges
	(*StateChange)(nil),                           // 3: com.hedera.hapi.block.stream.output.StateChange
	(*NewStateChange)(nil),                        // 4: com.hedera.hapi.block.stream.output.NewStateChange
	(*RemovedStateChange)(nil),                    // 5: com.hedera.hapi.block.stream.output.RemovedStateChange
	(*SingletonUpdateChange)(nil),                 // 6: com.hedera.hapi.block.stream.output.SingletonUpdateChange
	(*MapUpdateChange)(nil),                       // 7: com.hedera.hapi.block.stream.output.MapUpdateChange
	(*MapDeleteChange)(nil),                       // 8: com.hedera.hapi.block.stream.output.MapDeleteChange
	(*MapChangeKey)(nil),                          // 9: com.hedera.hapi.block.stream.output.MapChangeKey
	(*MapChangeValue)(nil),                        // 10: com.hedera.hapi.block.stream.output.MapChangeValue
	(*QueuePushChange)(nil),                       // 11: com.hedera.hapi.block.stream.output.QueuePushChange
	(*QueuePopChange)(nil),                        // 12: com.hedera.hapi.block.stream.output.QueuePopChange
	(*common.Timestamp)(nil),                      // 13: proto.Timestamp
	(*blockrecords.BlockInfo)(nil),                // 14: proto.BlockInfo
	(*congestion.CongestionLevelStarts)(nil),      // 15: proto.CongestionLevelStarts
	(*wrapperspb.UInt64Value)(nil),                // 16: google.protobuf.UInt64Value
	(*services.ExchangeRateSet)(nil),              // 17: proto.ExchangeRateSet
	(*token.NetworkStakingRewards)(nil),           // 18: proto.NetworkStakingRewards
	(*wrapperspb.BytesValue)(nil),                 // 19: google.protobuf.BytesValue
	(*wrapperspb.StringValue)(nil),                // 20: google.protobuf.StringValue
	(*blockrecords.RunningHashes)(nil),            // 21: proto.RunningHashes
	(*throttles.ThrottleUsageSnapshots)(nil),      // 22: proto.ThrottleUsageSnapshots
	(*blockstream.BlockStreamInfo)(nil),           // 23: com.hedera.hapi.node.state.blockstream.BlockStreamInfo
	(*state.PlatformState)(nil),                   // 24: com.hedera.hapi.platform.state.PlatformState
	(*roster.RosterState)(nil),                    // 25: com.hedera.hapi.node.state.roster.RosterState
	(*common.AccountID)(nil),                      // 26: proto.AccountID
	(*common.TokenAssociation)(nil),               // 27: proto.TokenAssociation
	(*common.FileID)(nil),                         // 28: proto.FileID
	(*common.NftID)(nil),                          // 29: proto.NftID
	(*wrapperspb.Int64Value)(nil),                 // 30: google.protobuf.Int64Value
	(*common.ScheduleID)(nil),                     // 31: proto.ScheduleID
	(*contract.SlotKey)(nil),                      // 32: proto.SlotKey
	(*common.TokenID)(nil),                        // 33: proto.TokenID
	(*common.TopicID)(nil),                        // 34: proto.TopicID
	(*common.ContractID)(nil),                     // 35: proto.ContractID
	(*common.PendingAirdropId)(nil),               // 36: proto.PendingAirdropId
	(*token.Account)(nil),                         // 37: proto.Account
	(*contract.Bytecode)(nil),                     // 38: proto.Bytecode
	(*file.File)(nil),                             // 39: proto.File
	(*token.Nft)(nil),                             // 40: proto.Nft
	(*schedule.Schedule)(nil),                     // 41: proto.Schedule
	(*schedule.ScheduleList)(nil),                 // 42: proto.ScheduleList
	(*contract.SlotValue)(nil),                    // 43: proto.SlotValue
	(*token.StakingNodeInfo)(nil),                 // 44: proto.StakingNodeInfo
	(*token.Token)(nil),                           // 45: proto.Token
	(*token.TokenRelation)(nil),                   // 46: proto.TokenRelation
	(*consensus.Topic)(nil),                       // 47: proto.Topic
	(*addressbook.Node)(nil),                      // 48: com.hedera.hapi.node.state.addressbook.Node
	(*token.AccountPendingAirdrop)(nil),           // 49: proto.AccountPendingAirdrop
	(*roster.Roster)(nil),                         // 50: com.hedera.hapi.node.state.roster.Roster
	(*recordcache.TransactionReceiptEntries)(nil), // 51: proto.TransactionReceiptEntries
}
var file_stream_output_state_changes_proto_depIdxs = []int32{
	13, // 0: com.hedera.hapi.block.stream.output.StateChanges.consensus_timestamp:type_name -> proto.Timestamp
	3,  // 1: com.hedera.hapi.block.stream.output.StateChanges.state_changes:type_name -> com.hedera.hapi.block.stream.output.StateChange
	4,  // 2: com.hedera.hapi.block.stream.output.StateChange.state_add:type_name -> com.hedera.hapi.block.stream.output.NewStateChange
	5,  // 3: com.hedera.hapi.block.stream.output.StateChange.state_remove:type_name -> com.hedera.hapi.block.stream.output.RemovedStateChange
	6,  // 4: com.hedera.hapi.block.stream.output.StateChange.singleton_update:type_name -> com.hedera.hapi.block.stream.output.SingletonUpdateChange
	7,  // 5: com.hedera.hapi.block.stream.output.StateChange.map_update:type_name -> com.hedera.hapi.block.stream.output.MapUpdateChange
	8,  // 6: com.hedera.hapi.block.stream.output.StateChange.map_delete:type_name -> com.hedera.hapi.block.stream.output.MapDeleteChange
	11, // 7: com.hedera.hapi.block.stream.output.StateChange.queue_push:type_name -> com.hedera.hapi.block.stream.output.QueuePushChange
	12, // 8: com.hedera.hapi.block.stream.output.StateChange.queue_pop:type_name -> com.hedera.hapi.block.stream.output.QueuePopChange
	1,  // 9: com.hedera.hapi.block.stream.output.NewStateChange.state_type:type_name -> com.hedera.hapi.block.stream.output.NewStateType
	14, // 10: com.hedera.hapi.block.stream.output.SingletonUpdateChange.block_info_value:type_name -> proto.BlockInfo
	15, // 11: com.hedera.hapi.block.stream.output.SingletonUpdateChange.congestion_level_starts_value:type_name -> proto.CongestionLevelStarts
	16, // 12: com.hedera.hapi.block.stream.output.SingletonUpdateChange.entity_number_value:type_name -> google.protobuf.UInt64Value
	17, // 13: com.hedera.hapi.block.stream.output.SingletonUpdateChange.exchange_rate_set_value:type_name -> proto.ExchangeRateSet
	18, // 14: com.hedera.hapi.block.stream.output.SingletonUpdateChange.network_staking_rewards_value:type_name -> proto.NetworkStakingRewards
	19, // 15: com.hedera.hapi.block.stream.output.SingletonUpdateChange.bytes_value:type_name -> google.protobuf.BytesValue
	20, // 16: com.hedera.hapi.block.stream.output.SingletonUpdateChange.string_value:type_name -> google.protobuf.StringValue
	21, // 17: com.hedera.hapi.block.stream.output.SingletonUpdateChange.running_hashes_value:type_name -> proto.RunningHashes
	22, // 18: com.hedera.hapi.block.stream.output.SingletonUpdateChange.throttle_usage_snapshots_value:type_name -> proto.ThrottleUsageSnapshots
	13, // 19: com.hedera.hapi.block.stream.output.SingletonUpdateChange.timestamp_value:type_name -> proto.Timestamp
	23, // 20: com.hedera.hapi.block.stream.output.SingletonUpdateChange.block_stream_info_value:type_name -> com.hedera.hapi.node.state.blockstream.BlockStreamInfo
	24, // 21: com.hedera.hapi.block.stream.output.SingletonUpdateChange.platform_state_value:type_name -> com.hedera.hapi.platform.state.PlatformState
	25, // 22: com.hedera.hapi.block.stream.output.SingletonUpdateChange.roster_state_value:type_name -> com.hedera.hapi.node.state.roster.RosterState
	9,  // 23: com.hedera.hapi.block.stream.output.MapUpdateChange.key:type_name -> com.hedera.hapi.block.stream.output.MapChangeKey
	10, // 24: com.hedera.hapi.block.stream.output.MapUpdateChange.value:type_name -> com.hedera.hapi.block.stream.output.MapChangeValue
	9,  // 25: com.hedera.hapi.block.stream.output.MapDeleteChange.key:type_name -> com.hedera.hapi.block.stream.output.MapChangeKey
	26, // 26: com.hedera.hapi.block.stream.output.MapChangeKey.account_id_key:type_name -> proto.AccountID
	27, // 27: com.hedera.hapi.block.stream.output.MapChangeKey.token_relationship_key:type_name -> proto.TokenAssociation
	16, // 28: com.hedera.hapi.block.stream.output.MapChangeKey.entity_number_key:type_name -> google.protobuf.UInt64Value
	28, // 29: com.hedera.hapi.block.stream.output.MapChangeKey.file_id_key:type_name -> proto.FileID
	29, // 30: com.hedera.hapi.block.stream.output.MapChangeKey.nft_id_key:type_name -> proto.NftID
	19, // 31: com.hedera.hapi.block.stream.output.MapChangeKey.proto_bytes_key:type_name -> google.protobuf.BytesValue
	30, // 32: com.hedera.hapi.block.stream.output.MapChangeKey.proto_long_key:type_name -> google.protobuf.Int64Value
	20, // 33: com.hedera.hapi.block.stream.output.MapChangeKey.proto_string_key:type_name -> google.protobuf.StringValue
	31, // 34: com.hedera.hapi.block.stream.output.MapChangeKey.schedule_id_key:type_name -> proto.ScheduleID
	32, // 35: com.hedera.hapi.block.stream.output.MapChangeKey.slot_key_key:type_name -> proto.SlotKey
	33, // 36: com.hedera.hapi.block.stream.output.MapChangeKey.token_id_key:type_name -> proto.TokenID
	34, // 37: com.hedera.hapi.block.stream.output.MapChangeKey.topic_id_key:type_name -> proto.TopicID
	35, // 38: com.hedera.hapi.block.stream.output.MapChangeKey.contract_id_key:type_name -> proto.ContractID
	36, // 39: com.hedera.hapi.block.stream.output.MapChangeKey.pending_airdrop_id_key:type_name -> proto.PendingAirdropId
	37, // 40: com.hedera.hapi.block.stream.output.MapChangeValue.account_value:type_name -> proto.Account
	26, // 41: com.hedera.hapi.block.stream.output.MapChangeValue.account_id_value:type_name -> proto.AccountID
	38, // 42: com.hedera.hapi.block.stream.output.MapChangeValue.bytecode_value:type_name -> proto.Bytecode
	39, // 43: com.hedera.hapi.block.stream.output.MapChangeValue.file_value:type_name -> proto.File
	40, // 44: com.hedera.hapi.block.stream.output.MapChangeValue.nft_value:type_name -> proto.Nft
	20, // 45: com.hedera.hapi.block.stream.output.MapChangeValue.proto_string_value:type_name -> google.protobuf.StringValue
	41, // 46: com.hedera.hapi.block.stream.output.MapChangeValue.schedule_value:type_name -> proto.Schedule
	42, // 47: com.hedera.hapi.block.stream.output.MapChangeValue.schedule_list_value:type_name -> proto.ScheduleList
	43, // 48: com.hedera.hapi.block.stream.output.MapChangeValue.slot_value_value:type_name -> proto.SlotValue
	44, // 49: com.hedera.hapi.block.stream.output.MapChangeValue.staking_node_info_value:type_name -> proto.StakingNodeInfo
	45, // 50: com.hedera.hapi.block.stream.output.MapChangeValue.token_value:type_name -> proto.Token
	46, // 51: com.hedera.hapi.block.stream.output.MapChangeValue.token_relation_value:type_name -> proto.TokenRelation
	47, // 52: com.hedera.hapi.block.stream.output.MapChangeValue.topic_value:type_name -> proto.Topic
	48, // 53: com.hedera.hapi.block.stream.output.MapChangeValue.node_value:type_name -> com.hedera.hapi.node.state.addressbook.Node
	49, // 54: com.hedera.hapi.block.stream.output.MapChangeValue.account_pending_airdrop_value:type_name -> proto.AccountPendingAirdrop
	50, // 55: com.hedera.hapi.block.stream.output.MapChangeValue.roster_value:type_name -> com.hedera.hapi.node.state.roster.Roster
	19, // 56: com.hedera.hapi.block.stream.output.QueuePushChange.proto_bytes_element:type_name -> google.protobuf.BytesValue
	20, // 57: com.hedera.hapi.block.stream.output.QueuePushChange.proto_string_element:type_name -> google.protobuf.StringValue
	51, // 58: com.hedera.hapi.block.stream.output.QueuePushChange.transaction_receipt_entries_element:type_name -> proto.TransactionReceiptEntries
	59, // [59:59] is the sub-list for method output_type
	59, // [59:59] is the sub-list for method input_type
	59, // [59:59] is the sub-list for extension type_name
	59, // [59:59] is the sub-list for extension extendee
	0,  // [0:59] is the sub-list for field type_name
}

func init() { file_stream_output_state_changes_proto_init() }
func file_stream_output_state_changes_proto_init() {
	if File_stream_output_state_changes_proto != nil {
		return
	}
	file_stream_output_state_changes_proto_msgTypes[1].OneofWrappers = []any{
		(*StateChange_StateAdd)(nil),
		(*StateChange_StateRemove)(nil),
		(*StateChange_SingletonUpdate)(nil),
		(*StateChange_MapUpdate)(nil),
		(*StateChange_MapDelete)(nil),
		(*StateChange_QueuePush)(nil),
		(*StateChange_QueuePop)(nil),
	}
	file_stream_output_state_changes_proto_msgTypes[4].OneofWrappers = []any{
		(*SingletonUpdateChange_BlockInfoValue)(nil),
		(*SingletonUpdateChange_CongestionLevelStartsValue)(nil),
		(*SingletonUpdateChange_EntityNumberValue)(nil),
		(*SingletonUpdateChange_ExchangeRateSetValue)(nil),
		(*SingletonUpdateChange_NetworkStakingRewardsValue)(nil),
		(*SingletonUpdateChange_BytesValue)(nil),
		(*SingletonUpdateChange_StringValue)(nil),
		(*SingletonUpdateChange_RunningHashesValue)(nil),
		(*SingletonUpdateChange_ThrottleUsageSnapshotsValue)(nil),
		(*SingletonUpdateChange_TimestampValue)(nil),
		(*SingletonUpdateChange_BlockStreamInfoValue)(nil),
		(*SingletonUpdateChange_PlatformStateValue)(nil),
		(*SingletonUpdateChange_RosterStateValue)(nil),
	}
	file_stream_output_state_changes_proto_msgTypes[7].OneofWrappers = []any{
		(*MapChangeKey_AccountIdKey)(nil),
		(*MapChangeKey_TokenRelationshipKey)(nil),
		(*MapChangeKey_EntityNumberKey)(nil),
		(*MapChangeKey_FileIdKey)(nil),
		(*MapChangeKey_NftIdKey)(nil),
		(*MapChangeKey_ProtoBytesKey)(nil),
		(*MapChangeKey_ProtoLongKey)(nil),
		(*MapChangeKey_ProtoStringKey)(nil),
		(*MapChangeKey_ScheduleIdKey)(nil),
		(*MapChangeKey_SlotKeyKey)(nil),
		(*MapChangeKey_TokenIdKey)(nil),
		(*MapChangeKey_TopicIdKey)(nil),
		(*MapChangeKey_ContractIdKey)(nil),
		(*MapChangeKey_PendingAirdropIdKey)(nil),
	}
	file_stream_output_state_changes_proto_msgTypes[8].OneofWrappers = []any{
		(*MapChangeValue_AccountValue)(nil),
		(*MapChangeValue_AccountIdValue)(nil),
		(*MapChangeValue_BytecodeValue)(nil),
		(*MapChangeValue_FileValue)(nil),
		(*MapChangeValue_NftValue)(nil),
		(*MapChangeValue_ProtoStringValue)(nil),
		(*MapChangeValue_ScheduleValue)(nil),
		(*MapChangeValue_ScheduleListValue)(nil),
		(*MapChangeValue_SlotValueValue)(nil),
		(*MapChangeValue_StakingNodeInfoValue)(nil),
		(*MapChangeValue_TokenValue)(nil),
		(*MapChangeValue_TokenRelationValue)(nil),
		(*MapChangeValue_TopicValue)(nil),
		(*MapChangeValue_NodeValue)(nil),
		(*MapChangeValue_AccountPendingAirdropValue)(nil),
		(*MapChangeValue_RosterValue)(nil),
	}
	file_stream_output_state_changes_proto_msgTypes[9].OneofWrappers = []any{
		(*QueuePushChange_ProtoBytesElement)(nil),
		(*QueuePushChange_ProtoStringElement)(nil),
		(*QueuePushChange_TransactionReceiptEntriesElement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_state_changes_proto_rawDesc), len(file_stream_output_state_changes_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_state_changes_proto_goTypes,
		DependencyIndexes: file_stream_output_state_changes_proto_depIdxs,
		EnumInfos:         file_stream_output_state_changes_proto_enumTypes,
		MessageInfos:      file_stream_output_state_changes_proto_msgTypes,
	}.Build()
	File_stream_output_state_changes_proto = out.File
	file_stream_output_state_changes_proto_goTypes = nil
	file_stream_output_state_changes_proto_depIdxs = nil
}
