//*
// # Token Service
// Block stream messages that report the results of transactions
// handled by the `Token` service.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/token_service.proto

package output

import (
	_ "github.com/cordialsys/hedera-protobufs-go/services"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Block Stream data for a `createToken` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type CreateTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenOutput) Reset() {
	*x = CreateTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenOutput) ProtoMessage() {}

func (x *CreateTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenOutput.ProtoReflect.Descriptor instead.
func (*CreateTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{0}
}

// *
// Block Stream data for a `freezeTokenAccount` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type FreezeTokenAccountOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeTokenAccountOutput) Reset() {
	*x = FreezeTokenAccountOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeTokenAccountOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeTokenAccountOutput) ProtoMessage() {}

func (x *FreezeTokenAccountOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeTokenAccountOutput.ProtoReflect.Descriptor instead.
func (*FreezeTokenAccountOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{1}
}

// *
// Block Stream data for an `unfreezeTokenAccount` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UnfreezeTokenAccountOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfreezeTokenAccountOutput) Reset() {
	*x = UnfreezeTokenAccountOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeTokenAccountOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeTokenAccountOutput) ProtoMessage() {}

func (x *UnfreezeTokenAccountOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeTokenAccountOutput.ProtoReflect.Descriptor instead.
func (*UnfreezeTokenAccountOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{2}
}

// *
// Block Stream data for a `grantKycToTokenAccount` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type GrantTokenKycOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTokenKycOutput) Reset() {
	*x = GrantTokenKycOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTokenKycOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTokenKycOutput) ProtoMessage() {}

func (x *GrantTokenKycOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTokenKycOutput.ProtoReflect.Descriptor instead.
func (*GrantTokenKycOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{3}
}

// *
// Block Stream data for a `revokeKycFromTokenAccount` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type RevokeTokenKycOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenKycOutput) Reset() {
	*x = RevokeTokenKycOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenKycOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenKycOutput) ProtoMessage() {}

func (x *RevokeTokenKycOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenKycOutput.ProtoReflect.Descriptor instead.
func (*RevokeTokenKycOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{4}
}

// *
// Block Stream data for a `deleteToken` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type DeleteTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenOutput) Reset() {
	*x = DeleteTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenOutput) ProtoMessage() {}

func (x *DeleteTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenOutput.ProtoReflect.Descriptor instead.
func (*DeleteTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{5}
}

// *
// Block Stream data for an `updateToken` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UpdateTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenOutput) Reset() {
	*x = UpdateTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenOutput) ProtoMessage() {}

func (x *UpdateTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenOutput.ProtoReflect.Descriptor instead.
func (*UpdateTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{6}
}

// *
// Block Stream data for a `mintToken` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type MintTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenOutput) Reset() {
	*x = MintTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenOutput) ProtoMessage() {}

func (x *MintTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenOutput.ProtoReflect.Descriptor instead.
func (*MintTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{7}
}

// *
// Block Stream data for a `burnToken` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type BurnTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnTokenOutput) Reset() {
	*x = BurnTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnTokenOutput) ProtoMessage() {}

func (x *BurnTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnTokenOutput.ProtoReflect.Descriptor instead.
func (*BurnTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{8}
}

// *
// Block Stream data for a `wipeTokenAccount` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type WipeTokenAccountOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WipeTokenAccountOutput) Reset() {
	*x = WipeTokenAccountOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WipeTokenAccountOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WipeTokenAccountOutput) ProtoMessage() {}

func (x *WipeTokenAccountOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WipeTokenAccountOutput.ProtoReflect.Descriptor instead.
func (*WipeTokenAccountOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{9}
}

// *
// Block Stream data for an `associateTokens` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type AssociateTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociateTokenOutput) Reset() {
	*x = AssociateTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateTokenOutput) ProtoMessage() {}

func (x *AssociateTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateTokenOutput.ProtoReflect.Descriptor instead.
func (*AssociateTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{10}
}

// *
// Block Stream data for a `dissociateTokens` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type DissociateTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DissociateTokenOutput) Reset() {
	*x = DissociateTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DissociateTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissociateTokenOutput) ProtoMessage() {}

func (x *DissociateTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissociateTokenOutput.ProtoReflect.Descriptor instead.
func (*DissociateTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{11}
}

// *
// Block Stream data for an `updateTokenFeeSchedule` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UpdateTokenFeeScheduleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenFeeScheduleOutput) Reset() {
	*x = UpdateTokenFeeScheduleOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenFeeScheduleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenFeeScheduleOutput) ProtoMessage() {}

func (x *UpdateTokenFeeScheduleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenFeeScheduleOutput.ProtoReflect.Descriptor instead.
func (*UpdateTokenFeeScheduleOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{12}
}

// *
// Block Stream data for a `pauseToken` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type PauseTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTokenOutput) Reset() {
	*x = PauseTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTokenOutput) ProtoMessage() {}

func (x *PauseTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTokenOutput.ProtoReflect.Descriptor instead.
func (*PauseTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{13}
}

// *
// Block Stream data for an `unpauseToken` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UnpauseTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpauseTokenOutput) Reset() {
	*x = UnpauseTokenOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpauseTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpauseTokenOutput) ProtoMessage() {}

func (x *UnpauseTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpauseTokenOutput.ProtoReflect.Descriptor instead.
func (*UnpauseTokenOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{14}
}

// *
// Block Stream data for an `updateNfts` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UpdateTokenNftsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenNftsOutput) Reset() {
	*x = UpdateTokenNftsOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenNftsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenNftsOutput) ProtoMessage() {}

func (x *UpdateTokenNftsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenNftsOutput.ProtoReflect.Descriptor instead.
func (*UpdateTokenNftsOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{15}
}

// *
// Block Stream data for a `tokenAirdrop` transaction.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type TokenAirdropOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenAirdropOutput) Reset() {
	*x = TokenAirdropOutput{}
	mi := &file_stream_output_token_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenAirdropOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAirdropOutput) ProtoMessage() {}

func (x *TokenAirdropOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_token_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAirdropOutput.ProtoReflect.Descriptor instead.
func (*TokenAirdropOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_token_service_proto_rawDescGZIP(), []int{16}
}

var File_stream_output_token_service_proto protoreflect.FileDescriptor

const file_stream_output_token_service_proto_rawDesc = "" +
	"\n" +
	"!stream/output/token_service.proto\x12#com.hedera.hapi.block.stream.output\x1a\x11custom_fees.proto\"\x13\n" +
	"\x11CreateTokenOutput\"\x1a\n" +
	"\x18FreezeTokenAccountOutput\"\x1c\n" +
	"\x1aUnfreezeTokenAccountOutput\"\x15\n" +
	"\x13GrantTokenKycOutput\"\x16\n" +
	"\x14RevokeTokenKycOutput\"\x13\n" +
	"\x11DeleteTokenOutput\"\x13\n" +
	"\x11UpdateTokenOutput\"\x11\n" +
	"\x0fMintTokenOutput\"\x11\n" +
	"\x0fBurnTokenOutput\"\x18\n" +
	"\x16WipeTokenAccountOutput\"\x16\n" +
	"\x14AssociateTokenOutput\"\x17\n" +
	"\x15DissociateTokenOutput\"\x1e\n" +
	"\x1cUpdateTokenFeeScheduleOutput\"\x12\n" +
	"\x10PauseTokenOutput\"\x14\n" +
	"\x12UnpauseTokenOutput\"\x17\n" +
	"\x15UpdateTokenNftsOutput\"\x14\n" +
	"\x12TokenAirdropOutputBm\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z=github.com/cordialsys/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_token_service_proto_rawDescOnce sync.Once
	file_stream_output_token_service_proto_rawDescData []byte
)

func file_stream_output_token_service_proto_rawDescGZIP() []byte {
	file_stream_output_token_service_proto_rawDescOnce.Do(func() {
		file_stream_output_token_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_token_service_proto_rawDesc), len(file_stream_output_token_service_proto_rawDesc)))
	})
	return file_stream_output_token_service_proto_rawDescData
}

var file_stream_output_token_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_stream_output_token_service_proto_goTypes = []any{
	(*CreateTokenOutput)(nil),            // 0: com.hedera.hapi.block.stream.output.CreateTokenOutput
	(*FreezeTokenAccountOutput)(nil),     // 1: com.hedera.hapi.block.stream.output.FreezeTokenAccountOutput
	(*UnfreezeTokenAccountOutput)(nil),   // 2: com.hedera.hapi.block.stream.output.UnfreezeTokenAccountOutput
	(*GrantTokenKycOutput)(nil),          // 3: com.hedera.hapi.block.stream.output.GrantTokenKycOutput
	(*RevokeTokenKycOutput)(nil),         // 4: com.hedera.hapi.block.stream.output.RevokeTokenKycOutput
	(*DeleteTokenOutput)(nil),            // 5: com.hedera.hapi.block.stream.output.DeleteTokenOutput
	(*UpdateTokenOutput)(nil),            // 6: com.hedera.hapi.block.stream.output.UpdateTokenOutput
	(*MintTokenOutput)(nil),              // 7: com.hedera.hapi.block.stream.output.MintTokenOutput
	(*BurnTokenOutput)(nil),              // 8: com.hedera.hapi.block.stream.output.BurnTokenOutput
	(*WipeTokenAccountOutput)(nil),       // 9: com.hedera.hapi.block.stream.output.WipeTokenAccountOutput
	(*AssociateTokenOutput)(nil),         // 10: com.hedera.hapi.block.stream.output.AssociateTokenOutput
	(*DissociateTokenOutput)(nil),        // 11: com.hedera.hapi.block.stream.output.DissociateTokenOutput
	(*UpdateTokenFeeScheduleOutput)(nil), // 12: com.hedera.hapi.block.stream.output.UpdateTokenFeeScheduleOutput
	(*PauseTokenOutput)(nil),             // 13: com.hedera.hapi.block.stream.output.PauseTokenOutput
	(*UnpauseTokenOutput)(nil),           // 14: com.hedera.hapi.block.stream.output.UnpauseTokenOutput
	(*UpdateTokenNftsOutput)(nil),        // 15: com.hedera.hapi.block.stream.output.UpdateTokenNftsOutput
	(*TokenAirdropOutput)(nil),           // 16: com.hedera.hapi.block.stream.output.TokenAirdropOutput
}
var file_stream_output_token_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_output_token_service_proto_init() }
func file_stream_output_token_service_proto_init() {
	if File_stream_output_token_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_token_service_proto_rawDesc), len(file_stream_output_token_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_token_service_proto_goTypes,
		DependencyIndexes: file_stream_output_token_service_proto_depIdxs,
		MessageInfos:      file_stream_output_token_service_proto_msgTypes,
	}.Build()
	File_stream_output_token_service_proto = out.File
	file_stream_output_token_service_proto_goTypes = nil
	file_stream_output_token_service_proto_depIdxs = nil
}
