//*
// # Util Service
// Block stream messages that report the results of transactions handled by
// the `Util` service.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/output/util_service.proto

package output

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Block data produced by `prng` transactions submitted to the `Util` service.
//
// The `entropy` reported in this block stream message is deterministically
// produced, but has high dispersion and is very difficult to predict.
//
// This message SHALL NOT duplicate information already contained in
// the original transaction.
type UtilPrngOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entropy:
	//
	//	*UtilPrngOutput_PrngBytes
	//	*UtilPrngOutput_PrngNumber
	Entropy       isUtilPrngOutput_Entropy `protobuf_oneof:"entropy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtilPrngOutput) Reset() {
	*x = UtilPrngOutput{}
	mi := &file_stream_output_util_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilPrngOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilPrngOutput) ProtoMessage() {}

func (x *UtilPrngOutput) ProtoReflect() protoreflect.Message {
	mi := &file_stream_output_util_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilPrngOutput.ProtoReflect.Descriptor instead.
func (*UtilPrngOutput) Descriptor() ([]byte, []int) {
	return file_stream_output_util_service_proto_rawDescGZIP(), []int{0}
}

func (x *UtilPrngOutput) GetEntropy() isUtilPrngOutput_Entropy {
	if x != nil {
		return x.Entropy
	}
	return nil
}

func (x *UtilPrngOutput) GetPrngBytes() []byte {
	if x != nil {
		if x, ok := x.Entropy.(*UtilPrngOutput_PrngBytes); ok {
			return x.PrngBytes
		}
	}
	return nil
}

func (x *UtilPrngOutput) GetPrngNumber() uint32 {
	if x != nil {
		if x, ok := x.Entropy.(*UtilPrngOutput_PrngNumber); ok {
			return x.PrngNumber
		}
	}
	return 0
}

type isUtilPrngOutput_Entropy interface {
	isUtilPrngOutput_Entropy()
}

type UtilPrngOutput_PrngBytes struct {
	// *
	// A deterministic pseudo-random sequence of 48 bytes.
	// <p>
	// This value SHALL be the result of a corresponding
	// `UtilService` `prng` transaction.
	PrngBytes []byte `protobuf:"bytes,1,opt,name=prng_bytes,json=prngBytes,proto3,oneof"`
}

type UtilPrngOutput_PrngNumber struct {
	// *
	// A deterministic pseudo-random number generated within a
	// specified range.
	// <p>
	// This value SHALL be the result of a corresponding `UtilService`
	// `prng` transaction.<br/>
	// Note that the transaction only permits a non-negative range, the
	// output SHALL always be a whole number.
	PrngNumber uint32 `protobuf:"varint,2,opt,name=prng_number,json=prngNumber,proto3,oneof"`
}

func (*UtilPrngOutput_PrngBytes) isUtilPrngOutput_Entropy() {}

func (*UtilPrngOutput_PrngNumber) isUtilPrngOutput_Entropy() {}

var File_stream_output_util_service_proto protoreflect.FileDescriptor

const file_stream_output_util_service_proto_rawDesc = "" +
	"\n" +
	" stream/output/util_service.proto\x12#com.hedera.hapi.block.stream.output\"_\n" +
	"\x0eUtilPrngOutput\x12\x1f\n" +
	"\n" +
	"prng_bytes\x18\x01 \x01(\fH\x00R\tprngBytes\x12!\n" +
	"\vprng_number\x18\x02 \x01(\rH\x00R\n" +
	"prngNumberB\t\n" +
	"\aentropyBl\n" +
	"*com.hedera.hapi.block.stream.output.protocP\x01Z<github.com/hashgraph/hedera-protobufs-go/block/stream/outputb\x06proto3"

var (
	file_stream_output_util_service_proto_rawDescOnce sync.Once
	file_stream_output_util_service_proto_rawDescData []byte
)

func file_stream_output_util_service_proto_rawDescGZIP() []byte {
	file_stream_output_util_service_proto_rawDescOnce.Do(func() {
		file_stream_output_util_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_output_util_service_proto_rawDesc), len(file_stream_output_util_service_proto_rawDesc)))
	})
	return file_stream_output_util_service_proto_rawDescData
}

var file_stream_output_util_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stream_output_util_service_proto_goTypes = []any{
	(*UtilPrngOutput)(nil), // 0: com.hedera.hapi.block.stream.output.UtilPrngOutput
}
var file_stream_output_util_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_output_util_service_proto_init() }
func file_stream_output_util_service_proto_init() {
	if File_stream_output_util_service_proto != nil {
		return
	}
	file_stream_output_util_service_proto_msgTypes[0].OneofWrappers = []any{
		(*UtilPrngOutput_PrngBytes)(nil),
		(*UtilPrngOutput_PrngNumber)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_output_util_service_proto_rawDesc), len(file_stream_output_util_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_output_util_service_proto_goTypes,
		DependencyIndexes: file_stream_output_util_service_proto_depIdxs,
		MessageInfos:      file_stream_output_util_service_proto_msgTypes,
	}.Build()
	File_stream_output_util_service_proto = out.File
	file_stream_output_util_service_proto_goTypes = nil
	file_stream_output_util_service_proto_depIdxs = nil
}
