//*
// # Block Service
// The Service API exposed by the Block Nodes.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: block_service.proto

package block

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockNodeService_ServerStatus_FullMethodName = "/com.hedera.hapi.block.BlockNodeService/serverStatus"
)

// BlockNodeServiceClient is the client API for BlockNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Remote procedure calls (RPCs) for the Block-Node ancillary services.
type BlockNodeServiceClient interface {
	// *
	// Read the status of this Block-Node.
	// <p>
	// A client SHOULD request server status prior to requesting block stream
	// data or a state snapshot.
	ServerStatus(ctx context.Context, in *ServerStatusRequest, opts ...grpc.CallOption) (*ServerStatusResponse, error)
}

type blockNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockNodeServiceClient(cc grpc.ClientConnInterface) BlockNodeServiceClient {
	return &blockNodeServiceClient{cc}
}

func (c *blockNodeServiceClient) ServerStatus(ctx context.Context, in *ServerStatusRequest, opts ...grpc.CallOption) (*ServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatusResponse)
	err := c.cc.Invoke(ctx, BlockNodeService_ServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockNodeServiceServer is the server API for BlockNodeService service.
// All implementations must embed UnimplementedBlockNodeServiceServer
// for forward compatibility.
//
// *
// Remote procedure calls (RPCs) for the Block-Node ancillary services.
type BlockNodeServiceServer interface {
	// *
	// Read the status of this Block-Node.
	// <p>
	// A client SHOULD request server status prior to requesting block stream
	// data or a state snapshot.
	ServerStatus(context.Context, *ServerStatusRequest) (*ServerStatusResponse, error)
	mustEmbedUnimplementedBlockNodeServiceServer()
}

// UnimplementedBlockNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockNodeServiceServer struct{}

func (UnimplementedBlockNodeServiceServer) ServerStatus(context.Context, *ServerStatusRequest) (*ServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerStatus not implemented")
}
func (UnimplementedBlockNodeServiceServer) mustEmbedUnimplementedBlockNodeServiceServer() {}
func (UnimplementedBlockNodeServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlockNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockNodeServiceServer will
// result in compilation errors.
type UnsafeBlockNodeServiceServer interface {
	mustEmbedUnimplementedBlockNodeServiceServer()
}

func RegisterBlockNodeServiceServer(s grpc.ServiceRegistrar, srv BlockNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockNodeService_ServiceDesc, srv)
}

func _BlockNodeService_ServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockNodeServiceServer).ServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockNodeService_ServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockNodeServiceServer).ServerStatus(ctx, req.(*ServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockNodeService_ServiceDesc is the grpc.ServiceDesc for BlockNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.hedera.hapi.block.BlockNodeService",
	HandlerType: (*BlockNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "serverStatus",
			Handler:    _BlockNodeService_ServerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "block_service.proto",
}

const (
	BlockAccessService_SingleBlock_FullMethodName = "/com.hedera.hapi.block.BlockAccessService/singleBlock"
)

// BlockAccessServiceClient is the client API for BlockAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Remote procedure calls (RPCs) for the Block-Node block services.
type BlockAccessServiceClient interface {
	// *
	// Read a single block from the Block-Node.
	// <p>
	// The request SHALL describe the block number of the block to retrieve.
	SingleBlock(ctx context.Context, in *SingleBlockRequest, opts ...grpc.CallOption) (*SingleBlockResponse, error)
}

type blockAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockAccessServiceClient(cc grpc.ClientConnInterface) BlockAccessServiceClient {
	return &blockAccessServiceClient{cc}
}

func (c *blockAccessServiceClient) SingleBlock(ctx context.Context, in *SingleBlockRequest, opts ...grpc.CallOption) (*SingleBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleBlockResponse)
	err := c.cc.Invoke(ctx, BlockAccessService_SingleBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockAccessServiceServer is the server API for BlockAccessService service.
// All implementations must embed UnimplementedBlockAccessServiceServer
// for forward compatibility.
//
// *
// Remote procedure calls (RPCs) for the Block-Node block services.
type BlockAccessServiceServer interface {
	// *
	// Read a single block from the Block-Node.
	// <p>
	// The request SHALL describe the block number of the block to retrieve.
	SingleBlock(context.Context, *SingleBlockRequest) (*SingleBlockResponse, error)
	mustEmbedUnimplementedBlockAccessServiceServer()
}

// UnimplementedBlockAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockAccessServiceServer struct{}

func (UnimplementedBlockAccessServiceServer) SingleBlock(context.Context, *SingleBlockRequest) (*SingleBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleBlock not implemented")
}
func (UnimplementedBlockAccessServiceServer) mustEmbedUnimplementedBlockAccessServiceServer() {}
func (UnimplementedBlockAccessServiceServer) testEmbeddedByValue()                            {}

// UnsafeBlockAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockAccessServiceServer will
// result in compilation errors.
type UnsafeBlockAccessServiceServer interface {
	mustEmbedUnimplementedBlockAccessServiceServer()
}

func RegisterBlockAccessServiceServer(s grpc.ServiceRegistrar, srv BlockAccessServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockAccessService_ServiceDesc, srv)
}

func _BlockAccessService_SingleBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockAccessServiceServer).SingleBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockAccessService_SingleBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockAccessServiceServer).SingleBlock(ctx, req.(*SingleBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockAccessService_ServiceDesc is the grpc.ServiceDesc for BlockAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.hedera.hapi.block.BlockAccessService",
	HandlerType: (*BlockAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "singleBlock",
			Handler:    _BlockAccessService_SingleBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "block_service.proto",
}

const (
	StateService_StateSnapshot_FullMethodName = "/com.hedera.hapi.block.StateService/stateSnapshot"
)

// StateServiceClient is the client API for StateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Remote procedure calls (RPCs) for the Block-Node state snapshot
// and query services.
type StateServiceClient interface {
	// *
	// Read a state snapshot from the Block-Node.
	// <p>
	// The request SHALL describe the last block number present in the
	// snapshot.<br/>
	// Block-Node implementations MAY decline a request for a snapshot older
	// than the latest available, but MUST clearly document this behavior.
	StateSnapshot(ctx context.Context, in *StateSnapshotRequest, opts ...grpc.CallOption) (*StateSnapshotResponse, error)
}

type stateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateServiceClient(cc grpc.ClientConnInterface) StateServiceClient {
	return &stateServiceClient{cc}
}

func (c *stateServiceClient) StateSnapshot(ctx context.Context, in *StateSnapshotRequest, opts ...grpc.CallOption) (*StateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateSnapshotResponse)
	err := c.cc.Invoke(ctx, StateService_StateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServiceServer is the server API for StateService service.
// All implementations must embed UnimplementedStateServiceServer
// for forward compatibility.
//
// *
// Remote procedure calls (RPCs) for the Block-Node state snapshot
// and query services.
type StateServiceServer interface {
	// *
	// Read a state snapshot from the Block-Node.
	// <p>
	// The request SHALL describe the last block number present in the
	// snapshot.<br/>
	// Block-Node implementations MAY decline a request for a snapshot older
	// than the latest available, but MUST clearly document this behavior.
	StateSnapshot(context.Context, *StateSnapshotRequest) (*StateSnapshotResponse, error)
	mustEmbedUnimplementedStateServiceServer()
}

// UnimplementedStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateServiceServer struct{}

func (UnimplementedStateServiceServer) StateSnapshot(context.Context, *StateSnapshotRequest) (*StateSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StateSnapshot not implemented")
}
func (UnimplementedStateServiceServer) mustEmbedUnimplementedStateServiceServer() {}
func (UnimplementedStateServiceServer) testEmbeddedByValue()                      {}

// UnsafeStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateServiceServer will
// result in compilation errors.
type UnsafeStateServiceServer interface {
	mustEmbedUnimplementedStateServiceServer()
}

func RegisterStateServiceServer(s grpc.ServiceRegistrar, srv StateServiceServer) {
	// If the following call pancis, it indicates UnimplementedStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateService_ServiceDesc, srv)
}

func _StateService_StateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).StateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateService_StateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).StateSnapshot(ctx, req.(*StateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateService_ServiceDesc is the grpc.ServiceDesc for StateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.hedera.hapi.block.StateService",
	HandlerType: (*StateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "stateSnapshot",
			Handler:    _StateService_StateSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "block_service.proto",
}

const (
	BlockStreamService_PublishBlockStream_FullMethodName   = "/com.hedera.hapi.block.BlockStreamService/publishBlockStream"
	BlockStreamService_SubscribeBlockStream_FullMethodName = "/com.hedera.hapi.block.BlockStreamService/subscribeBlockStream"
)

// BlockStreamServiceClient is the client API for BlockStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Remote procedure calls (RPCs) for the Block-Node stream services.
type BlockStreamServiceClient interface {
	// *
	// Publish a stream of blocks.
	// <p>
	// Each item in the stream MUST contain one `BlockItem`.<br/>
	// Each Block MUST begin with a single `BlockHeader` block item.<br/>
	// The Block-Node SHALL append each `BlockItem` to an internal structure
	// to construct full blocks.<br/>
	// Each Block MUST end with a single `BlockStateProof` block item.<br/>
	// It is RECOMMENDED that the implementations verify the Block using the
	// `BlockStateProof` to validate all data was received correctly.<br/>
	// This API SHOULD, generally, be restricted based on mTLS authentication
	// to a limited set of Publisher (i.e. consensus node) systems.
	PublishBlockStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishStreamRequest, PublishStreamResponse], error)
	// *
	// Subscribe to a stream of blocks.
	// <p>
	// Each item in the stream SHALL contain one `BlockItem` or a
	// response code.<br/>
	// The request message MUST specify start and end block numbers
	// to return/<br/>
	// The Block-Node SHALL stream the full contents of the blocks
	// requested.<br/>
	// The block items SHALL be streamed in order originally produced within
	// a block.<br/>
	// The blocks shall be streamed in ascending order by `block_number`.<br/>
	// The Block-Node SHALL end the stream when the last requested block,
	// if set, has been sent.<br/>
	// A request with an end block of `0` SHALL be interpreted to indicate the
	// stream has no end. The Block-Node SHALL continue to stream new blocks
	// as soon as each becomes available.<br/>
	// The Block-Node SHALL end the stream with response code containing a
	// status of SUCCESS when the stream is complete.<br/>
	// The Block-Node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_INVALID_START_BLOCK_NUMBER` if the start block
	// number is greater than the end block number.<br/>
	// The Block-Node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_PAYMENT_INSUFFICIENT` if insufficient payment
	// remains to complete the requested stream.<br/>
	// The Block-Node SHALL make every reasonable effort to fulfill as much
	// of the request as possible in the event payment is not sufficient to
	// complete the request.
	SubscribeBlockStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeStreamResponse], error)
}

type blockStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockStreamServiceClient(cc grpc.ClientConnInterface) BlockStreamServiceClient {
	return &blockStreamServiceClient{cc}
}

func (c *blockStreamServiceClient) PublishBlockStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishStreamRequest, PublishStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockStreamService_ServiceDesc.Streams[0], BlockStreamService_PublishBlockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishStreamRequest, PublishStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_PublishBlockStreamClient = grpc.BidiStreamingClient[PublishStreamRequest, PublishStreamResponse]

func (c *blockStreamServiceClient) SubscribeBlockStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockStreamService_ServiceDesc.Streams[1], BlockStreamService_SubscribeBlockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeStreamRequest, SubscribeStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_SubscribeBlockStreamClient = grpc.ServerStreamingClient[SubscribeStreamResponse]

// BlockStreamServiceServer is the server API for BlockStreamService service.
// All implementations must embed UnimplementedBlockStreamServiceServer
// for forward compatibility.
//
// *
// Remote procedure calls (RPCs) for the Block-Node stream services.
type BlockStreamServiceServer interface {
	// *
	// Publish a stream of blocks.
	// <p>
	// Each item in the stream MUST contain one `BlockItem`.<br/>
	// Each Block MUST begin with a single `BlockHeader` block item.<br/>
	// The Block-Node SHALL append each `BlockItem` to an internal structure
	// to construct full blocks.<br/>
	// Each Block MUST end with a single `BlockStateProof` block item.<br/>
	// It is RECOMMENDED that the implementations verify the Block using the
	// `BlockStateProof` to validate all data was received correctly.<br/>
	// This API SHOULD, generally, be restricted based on mTLS authentication
	// to a limited set of Publisher (i.e. consensus node) systems.
	PublishBlockStream(grpc.BidiStreamingServer[PublishStreamRequest, PublishStreamResponse]) error
	// *
	// Subscribe to a stream of blocks.
	// <p>
	// Each item in the stream SHALL contain one `BlockItem` or a
	// response code.<br/>
	// The request message MUST specify start and end block numbers
	// to return/<br/>
	// The Block-Node SHALL stream the full contents of the blocks
	// requested.<br/>
	// The block items SHALL be streamed in order originally produced within
	// a block.<br/>
	// The blocks shall be streamed in ascending order by `block_number`.<br/>
	// The Block-Node SHALL end the stream when the last requested block,
	// if set, has been sent.<br/>
	// A request with an end block of `0` SHALL be interpreted to indicate the
	// stream has no end. The Block-Node SHALL continue to stream new blocks
	// as soon as each becomes available.<br/>
	// The Block-Node SHALL end the stream with response code containing a
	// status of SUCCESS when the stream is complete.<br/>
	// The Block-Node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_INVALID_START_BLOCK_NUMBER` if the start block
	// number is greater than the end block number.<br/>
	// The Block-Node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_PAYMENT_INSUFFICIENT` if insufficient payment
	// remains to complete the requested stream.<br/>
	// The Block-Node SHALL make every reasonable effort to fulfill as much
	// of the request as possible in the event payment is not sufficient to
	// complete the request.
	SubscribeBlockStream(*SubscribeStreamRequest, grpc.ServerStreamingServer[SubscribeStreamResponse]) error
	mustEmbedUnimplementedBlockStreamServiceServer()
}

// UnimplementedBlockStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockStreamServiceServer struct{}

func (UnimplementedBlockStreamServiceServer) PublishBlockStream(grpc.BidiStreamingServer[PublishStreamRequest, PublishStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PublishBlockStream not implemented")
}
func (UnimplementedBlockStreamServiceServer) SubscribeBlockStream(*SubscribeStreamRequest, grpc.ServerStreamingServer[SubscribeStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeBlockStream not implemented")
}
func (UnimplementedBlockStreamServiceServer) mustEmbedUnimplementedBlockStreamServiceServer() {}
func (UnimplementedBlockStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeBlockStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockStreamServiceServer will
// result in compilation errors.
type UnsafeBlockStreamServiceServer interface {
	mustEmbedUnimplementedBlockStreamServiceServer()
}

func RegisterBlockStreamServiceServer(s grpc.ServiceRegistrar, srv BlockStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockStreamService_ServiceDesc, srv)
}

func _BlockStreamService_PublishBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlockStreamServiceServer).PublishBlockStream(&grpc.GenericServerStream[PublishStreamRequest, PublishStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_PublishBlockStreamServer = grpc.BidiStreamingServer[PublishStreamRequest, PublishStreamResponse]

func _BlockStreamService_SubscribeBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockStreamServiceServer).SubscribeBlockStream(m, &grpc.GenericServerStream[SubscribeStreamRequest, SubscribeStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_SubscribeBlockStreamServer = grpc.ServerStreamingServer[SubscribeStreamResponse]

// BlockStreamService_ServiceDesc is the grpc.ServiceDesc for BlockStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.hedera.hapi.block.BlockStreamService",
	HandlerType: (*BlockStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "publishBlockStream",
			Handler:       _BlockStreamService_PublishBlockStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "subscribeBlockStream",
			Handler:       _BlockStreamService_SubscribeBlockStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "block_service.proto",
}
