//*
// # Block Service
// The Service API exposed by the Block Nodes.
//
// ## Workarounds
// > There are incorrect elements in this file to work around bugs in the
// > PBJ Compiler.
// >> Issues 262, 263, 240, 218, 217, and 216 are related.
// >
// > Issue 263
// >> A number of fields reference child messages, these _should_ specify
// >> the parent message (i.e. `Parent.child field = #;`) but do not do
// >> so due to issue 263.
// >
// > Issue 262
// >> Some fields reference messages defined in other packages that share
// >> a common prefix (e.g. `com.hedera.hapi.block.stream`). These fields
// >> specify the entire package instead of the shorter and clearer suffix
// >> due to issue 262
// >
// > Issue 240
// >> These files currently cause PBJ integration tests to fail if included
// >> due to issue 240.
// >
// > Issue 218
// >> These files have the same value for package and java_package. Ideally
// >> we would not specify `java_package` or the pbj comment in that situation,
// >> but Issue 218 prevents eliding the unnecessary directives.
// >
// > Issue 217
// >> These files may cause PBJ to fail compilation due to comments preceeding
// >> the `syntax` keyword.
// >
// > Issue 216
// >> These files would do well with validation support, but cannot make
// >> use of validation, even as an advisory element, due to Issue 216.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: block_service.proto

package block

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockStreamService_ServerStatus_FullMethodName         = "/com.hedera.hapi.block.BlockStreamService/serverStatus"
	BlockStreamService_SingleBlock_FullMethodName          = "/com.hedera.hapi.block.BlockStreamService/singleBlock"
	BlockStreamService_StateSnapshot_FullMethodName        = "/com.hedera.hapi.block.BlockStreamService/stateSnapshot"
	BlockStreamService_PublishBlockStream_FullMethodName   = "/com.hedera.hapi.block.BlockStreamService/publishBlockStream"
	BlockStreamService_SubscribeBlockStream_FullMethodName = "/com.hedera.hapi.block.BlockStreamService/subscribeBlockStream"
)

// BlockStreamServiceClient is the client API for BlockStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Remote procedure calls (RPCs) for the Block Node.
type BlockStreamServiceClient interface {
	// *
	// Read the status of this block node server.
	// <p>
	// A client SHOULD request server status prior to requesting block stream
	// data or a state snapshot.
	ServerStatus(ctx context.Context, in *ServerStatusRequest, opts ...grpc.CallOption) (*ServerStatusResponse, error)
	// *
	// Read a single block from the block node.
	// <p>
	// The request SHALL describe the block number of the block to retrieve.
	SingleBlock(ctx context.Context, in *SingleBlockRequest, opts ...grpc.CallOption) (*SingleBlockResponse, error)
	// *
	// Read a state snapshot from the block node.
	// <p>
	// The request SHALL describe the last block number present in the
	// snapshot.<br/>
	// Block node implementations MAY decline a request for a snapshot older
	// than the latest available, but MUST clearly document this behavior.
	StateSnapshot(ctx context.Context, in *StateSnapshotRequest, opts ...grpc.CallOption) (*StateSnapshotResponse, error)
	// *
	// Publish a stream of blocks.
	// <p>
	// Each item in the stream MUST contain one `BlockItem`.<br/>
	// Each Block MUST begin with a single `BlockHeader` block item.<br/>
	// The block node SHALL append each `BlockItem` to an internal structure
	// to construct full blocks.<br/>
	// Each Block MUST end with a single `BlockStateProof` block item.<br/>
	// It is RECOMMENDED that the implementations verify the Block using the
	// `BlockStateProof` to validate all data was received correctly.<br/>
	// This API SHOULD, generally, be restricted based on mTLS authentication
	// to a limited set of source (i.e. consensus node) systems.
	PublishBlockStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishStreamRequest, PublishStreamResponse], error)
	// *
	// Subscribe to a stream of blocks.
	// <p>
	// Each item in the stream SHALL contain one `BlockItem` or a
	// response code.<br/>
	// The request message MUST specify start and end block numbers
	// to return/<br/>
	// The block node SHALL stream the full contents of the blocks
	// requested.<br/>
	// The block items SHALL be streamed in order originally produced within
	// a block.<br/>
	// The blocks shall be streamed in ascending order by `block_number`.<br/>
	// The block node SHALL end the stream when the last requested block,
	// if set, has been sent.<br/>
	// A request with an end block of `0` SHALL be interpreted to indicate the
	// stream has no end. The block node SHALL continue to stream new blocks
	// as soon as each becomes available.<br/>
	// The block node SHALL end the stream with response code containing a
	// status of SUCCESS when the stream is complete.<br/>
	// The block node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_INVALID_START_BLOCK_NUMBER` if the start block
	// number is greater than the end block number.<br/>
	// The block node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_PAYMENT_INSUFFICIENT` if insufficient payment
	// remains to complete the requested stream.<br/>
	// The block node SHALL make every reasonable effort to fulfill as much
	// of the request as possible in the event payment is not sufficient to
	// complete the request.
	SubscribeBlockStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeStreamResponse], error)
}

type blockStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockStreamServiceClient(cc grpc.ClientConnInterface) BlockStreamServiceClient {
	return &blockStreamServiceClient{cc}
}

func (c *blockStreamServiceClient) ServerStatus(ctx context.Context, in *ServerStatusRequest, opts ...grpc.CallOption) (*ServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatusResponse)
	err := c.cc.Invoke(ctx, BlockStreamService_ServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockStreamServiceClient) SingleBlock(ctx context.Context, in *SingleBlockRequest, opts ...grpc.CallOption) (*SingleBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleBlockResponse)
	err := c.cc.Invoke(ctx, BlockStreamService_SingleBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockStreamServiceClient) StateSnapshot(ctx context.Context, in *StateSnapshotRequest, opts ...grpc.CallOption) (*StateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateSnapshotResponse)
	err := c.cc.Invoke(ctx, BlockStreamService_StateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockStreamServiceClient) PublishBlockStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishStreamRequest, PublishStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockStreamService_ServiceDesc.Streams[0], BlockStreamService_PublishBlockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishStreamRequest, PublishStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_PublishBlockStreamClient = grpc.BidiStreamingClient[PublishStreamRequest, PublishStreamResponse]

func (c *blockStreamServiceClient) SubscribeBlockStream(ctx context.Context, in *SubscribeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockStreamService_ServiceDesc.Streams[1], BlockStreamService_SubscribeBlockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeStreamRequest, SubscribeStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_SubscribeBlockStreamClient = grpc.ServerStreamingClient[SubscribeStreamResponse]

// BlockStreamServiceServer is the server API for BlockStreamService service.
// All implementations must embed UnimplementedBlockStreamServiceServer
// for forward compatibility.
//
// *
// Remote procedure calls (RPCs) for the Block Node.
type BlockStreamServiceServer interface {
	// *
	// Read the status of this block node server.
	// <p>
	// A client SHOULD request server status prior to requesting block stream
	// data or a state snapshot.
	ServerStatus(context.Context, *ServerStatusRequest) (*ServerStatusResponse, error)
	// *
	// Read a single block from the block node.
	// <p>
	// The request SHALL describe the block number of the block to retrieve.
	SingleBlock(context.Context, *SingleBlockRequest) (*SingleBlockResponse, error)
	// *
	// Read a state snapshot from the block node.
	// <p>
	// The request SHALL describe the last block number present in the
	// snapshot.<br/>
	// Block node implementations MAY decline a request for a snapshot older
	// than the latest available, but MUST clearly document this behavior.
	StateSnapshot(context.Context, *StateSnapshotRequest) (*StateSnapshotResponse, error)
	// *
	// Publish a stream of blocks.
	// <p>
	// Each item in the stream MUST contain one `BlockItem`.<br/>
	// Each Block MUST begin with a single `BlockHeader` block item.<br/>
	// The block node SHALL append each `BlockItem` to an internal structure
	// to construct full blocks.<br/>
	// Each Block MUST end with a single `BlockStateProof` block item.<br/>
	// It is RECOMMENDED that the implementations verify the Block using the
	// `BlockStateProof` to validate all data was received correctly.<br/>
	// This API SHOULD, generally, be restricted based on mTLS authentication
	// to a limited set of source (i.e. consensus node) systems.
	PublishBlockStream(grpc.BidiStreamingServer[PublishStreamRequest, PublishStreamResponse]) error
	// *
	// Subscribe to a stream of blocks.
	// <p>
	// Each item in the stream SHALL contain one `BlockItem` or a
	// response code.<br/>
	// The request message MUST specify start and end block numbers
	// to return/<br/>
	// The block node SHALL stream the full contents of the blocks
	// requested.<br/>
	// The block items SHALL be streamed in order originally produced within
	// a block.<br/>
	// The blocks shall be streamed in ascending order by `block_number`.<br/>
	// The block node SHALL end the stream when the last requested block,
	// if set, has been sent.<br/>
	// A request with an end block of `0` SHALL be interpreted to indicate the
	// stream has no end. The block node SHALL continue to stream new blocks
	// as soon as each becomes available.<br/>
	// The block node SHALL end the stream with response code containing a
	// status of SUCCESS when the stream is complete.<br/>
	// The block node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_INVALID_START_BLOCK_NUMBER` if the start block
	// number is greater than the end block number.<br/>
	// The block node SHALL end the stream with a response code containing a
	// status of `READ_STREAM_PAYMENT_INSUFFICIENT` if insufficient payment
	// remains to complete the requested stream.<br/>
	// The block node SHALL make every reasonable effort to fulfill as much
	// of the request as possible in the event payment is not sufficient to
	// complete the request.
	SubscribeBlockStream(*SubscribeStreamRequest, grpc.ServerStreamingServer[SubscribeStreamResponse]) error
	mustEmbedUnimplementedBlockStreamServiceServer()
}

// UnimplementedBlockStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockStreamServiceServer struct{}

func (UnimplementedBlockStreamServiceServer) ServerStatus(context.Context, *ServerStatusRequest) (*ServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerStatus not implemented")
}
func (UnimplementedBlockStreamServiceServer) SingleBlock(context.Context, *SingleBlockRequest) (*SingleBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleBlock not implemented")
}
func (UnimplementedBlockStreamServiceServer) StateSnapshot(context.Context, *StateSnapshotRequest) (*StateSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StateSnapshot not implemented")
}
func (UnimplementedBlockStreamServiceServer) PublishBlockStream(grpc.BidiStreamingServer[PublishStreamRequest, PublishStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PublishBlockStream not implemented")
}
func (UnimplementedBlockStreamServiceServer) SubscribeBlockStream(*SubscribeStreamRequest, grpc.ServerStreamingServer[SubscribeStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeBlockStream not implemented")
}
func (UnimplementedBlockStreamServiceServer) mustEmbedUnimplementedBlockStreamServiceServer() {}
func (UnimplementedBlockStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeBlockStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockStreamServiceServer will
// result in compilation errors.
type UnsafeBlockStreamServiceServer interface {
	mustEmbedUnimplementedBlockStreamServiceServer()
}

func RegisterBlockStreamServiceServer(s grpc.ServiceRegistrar, srv BlockStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlockStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockStreamService_ServiceDesc, srv)
}

func _BlockStreamService_ServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockStreamServiceServer).ServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockStreamService_ServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockStreamServiceServer).ServerStatus(ctx, req.(*ServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockStreamService_SingleBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockStreamServiceServer).SingleBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockStreamService_SingleBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockStreamServiceServer).SingleBlock(ctx, req.(*SingleBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockStreamService_StateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockStreamServiceServer).StateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockStreamService_StateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockStreamServiceServer).StateSnapshot(ctx, req.(*StateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockStreamService_PublishBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlockStreamServiceServer).PublishBlockStream(&grpc.GenericServerStream[PublishStreamRequest, PublishStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_PublishBlockStreamServer = grpc.BidiStreamingServer[PublishStreamRequest, PublishStreamResponse]

func _BlockStreamService_SubscribeBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockStreamServiceServer).SubscribeBlockStream(m, &grpc.GenericServerStream[SubscribeStreamRequest, SubscribeStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_SubscribeBlockStreamServer = grpc.ServerStreamingServer[SubscribeStreamResponse]

// BlockStreamService_ServiceDesc is the grpc.ServiceDesc for BlockStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.hedera.hapi.block.BlockStreamService",
	HandlerType: (*BlockStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "serverStatus",
			Handler:    _BlockStreamService_ServerStatus_Handler,
		},
		{
			MethodName: "singleBlock",
			Handler:    _BlockStreamService_SingleBlock_Handler,
		},
		{
			MethodName: "stateSnapshot",
			Handler:    _BlockStreamService_StateSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "publishBlockStream",
			Handler:       _BlockStreamService_PublishBlockStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "subscribeBlockStream",
			Handler:       _BlockStreamService_SubscribeBlockStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "block_service.proto",
}
