// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: state/contract/bytecode.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// The bytecode for a contract id.
type Bytecode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The raw bytes (not hex-encoded) of a contract's bytecode.
	Code          []byte `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bytecode) Reset() {
	*x = Bytecode{}
	mi := &file_state_contract_bytecode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bytecode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytecode) ProtoMessage() {}

func (x *Bytecode) ProtoReflect() protoreflect.Message {
	mi := &file_state_contract_bytecode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytecode.ProtoReflect.Descriptor instead.
func (*Bytecode) Descriptor() ([]byte, []int) {
	return file_state_contract_bytecode_proto_rawDescGZIP(), []int{0}
}

func (x *Bytecode) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

var File_state_contract_bytecode_proto protoreflect.FileDescriptor

const file_state_contract_bytecode_proto_rawDesc = "" +
	"\n" +
	"\x1dstate/contract/bytecode.proto\x12\x05proto\"\x1e\n" +
	"\bBytecode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\fR\x04codeBi\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01ZAgithub.com/cordialsys/hedera-protobufs-go/services/state/contractb\x06proto3"

var (
	file_state_contract_bytecode_proto_rawDescOnce sync.Once
	file_state_contract_bytecode_proto_rawDescData []byte
)

func file_state_contract_bytecode_proto_rawDescGZIP() []byte {
	file_state_contract_bytecode_proto_rawDescOnce.Do(func() {
		file_state_contract_bytecode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_contract_bytecode_proto_rawDesc), len(file_state_contract_bytecode_proto_rawDesc)))
	})
	return file_state_contract_bytecode_proto_rawDescData
}

var file_state_contract_bytecode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_contract_bytecode_proto_goTypes = []any{
	(*Bytecode)(nil), // 0: proto.Bytecode
}
var file_state_contract_bytecode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_state_contract_bytecode_proto_init() }
func file_state_contract_bytecode_proto_init() {
	if File_state_contract_bytecode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_contract_bytecode_proto_rawDesc), len(file_state_contract_bytecode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_contract_bytecode_proto_goTypes,
		DependencyIndexes: file_state_contract_bytecode_proto_depIdxs,
		MessageInfos:      file_state_contract_bytecode_proto_msgTypes,
	}.Build()
	File_state_contract_bytecode_proto = out.File
	file_state_contract_bytecode_proto_goTypes = nil
	file_state_contract_bytecode_proto_depIdxs = nil
}
