// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: state/file/file.proto

package file

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Representation of a Hedera Token Service file in the network Merkle tree.
//
// As with all network entities, a file has a unique entity number, which is given along
// with the network's shard and realm in the form of a shard.realm.number id.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The file's unique file identifier in the Merkle state.
	FileId *common.FileID `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// *
	// The file's consensus expiration time in seconds since the epoch.
	ExpirationSecond int64 `protobuf:"varint,2,opt,name=expiration_second,json=expirationSecond,proto3" json:"expiration_second,omitempty"`
	// *
	// All keys at the top level of a key list must sign to create, modify and delete the file.
	Keys *common.KeyList `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"`
	// *
	// The bytes that are the contents of the file
	Contents []byte `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`
	// *
	// The memo associated with the file (UTF-8 encoding max 100 bytes)
	Memo string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	// *
	// Whether this file is deleted.
	Deleted bool `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// *
	// The pre system delete expiration time in seconds
	PreSystemDeleteExpirationSecond int64 `protobuf:"varint,7,opt,name=pre_system_delete_expiration_second,json=preSystemDeleteExpirationSecond,proto3" json:"pre_system_delete_expiration_second,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_state_file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_state_file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_state_file_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetFileId() *common.FileID {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *File) GetExpirationSecond() int64 {
	if x != nil {
		return x.ExpirationSecond
	}
	return 0
}

func (x *File) GetKeys() *common.KeyList {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *File) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *File) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *File) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *File) GetPreSystemDeleteExpirationSecond() int64 {
	if x != nil {
		return x.PreSystemDeleteExpirationSecond
	}
	return 0
}

var File_state_file_file_proto protoreflect.FileDescriptor

const file_state_file_file_proto_rawDesc = "" +
	"\n" +
	"\x15state/file/file.proto\x12\x05proto\x1a\x11basic_types.proto\"\x97\x02\n" +
	"\x04File\x12&\n" +
	"\afile_id\x18\x01 \x01(\v2\r.proto.FileIDR\x06fileId\x12+\n" +
	"\x11expiration_second\x18\x02 \x01(\x03R\x10expirationSecond\x12\"\n" +
	"\x04keys\x18\x03 \x01(\v2\x0e.proto.KeyListR\x04keys\x12\x1a\n" +
	"\bcontents\x18\x04 \x01(\fR\bcontents\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\tR\x04memo\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x12L\n" +
	"#pre_system_delete_expiration_second\x18\a \x01(\x03R\x1fpreSystemDeleteExpirationSecondBe\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z=github.com/cordialsys/hedera-protobufs-go/services/state/fileb\x06proto3"

var (
	file_state_file_file_proto_rawDescOnce sync.Once
	file_state_file_file_proto_rawDescData []byte
)

func file_state_file_file_proto_rawDescGZIP() []byte {
	file_state_file_file_proto_rawDescOnce.Do(func() {
		file_state_file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_file_file_proto_rawDesc), len(file_state_file_file_proto_rawDesc)))
	})
	return file_state_file_file_proto_rawDescData
}

var file_state_file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_file_file_proto_goTypes = []any{
	(*File)(nil),           // 0: proto.File
	(*common.FileID)(nil),  // 1: proto.FileID
	(*common.KeyList)(nil), // 2: proto.KeyList
}
var file_state_file_file_proto_depIdxs = []int32{
	1, // 0: proto.File.file_id:type_name -> proto.FileID
	2, // 1: proto.File.keys:type_name -> proto.KeyList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_file_file_proto_init() }
func file_state_file_file_proto_init() {
	if File_state_file_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_file_file_proto_rawDesc), len(file_state_file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_file_file_proto_goTypes,
		DependencyIndexes: file_state_file_file_proto_depIdxs,
		MessageInfos:      file_state_file_file_proto_msgTypes,
	}.Build()
	File_state_file_file_proto = out.File
	file_state_file_file_proto_goTypes = nil
	file_state_file_file_proto_depIdxs = nil
}
