//*
// # Gossip Event
// An event that is sent and received via gossip
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in [RFC2119](https://www.ietf.org/rfc/rfc2119).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: event/gossip_event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// An event that is sent and received via gossip
type GossipEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The core event data
	EventCore *EventCore `protobuf:"bytes,1,opt,name=event_core,json=eventCore,proto3" json:"event_core,omitempty"`
	// *
	// A node signature on the event hash.<br/>
	// The signature SHALL be created with the SHA384withRSA algorithm.<br/>
	// The signature MUST verify using the public key belonging to the `event_creator`.<br/>
	// The `event_creator` public key SHALL be read from the address book that corresponds to the event's birth round.<br/>
	// The signed event hash SHALL be a SHA-384 hash.<br/>
	// The signed event hash SHALL have the following inputs, in the specified order:<br/>
	// 1. The bytes of the `event_core` field<br/>
	// 2. The SHA-384 hash of each individual `EventTransaction`, in the order the transaction appear in the `event_transaction` field
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// *
	// The event transaction.
	// <p>
	// This field MAY contain zero transactions.<br/>
	// This field MUST NOT exceed `maxTransactionCountPerEvent` entries, initially `245760`.<br/>
	// This total size of this field MUST NOT exceed `maxTransactionBytesPerEvent`, initially `245760` bytes.
	EventTransaction []*EventTransaction `protobuf:"bytes,3,rep,name=event_transaction,json=eventTransaction,proto3" json:"event_transaction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipEvent) Reset() {
	*x = GossipEvent{}
	mi := &file_event_gossip_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEvent) ProtoMessage() {}

func (x *GossipEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_gossip_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEvent.ProtoReflect.Descriptor instead.
func (*GossipEvent) Descriptor() ([]byte, []int) {
	return file_event_gossip_event_proto_rawDescGZIP(), []int{0}
}

func (x *GossipEvent) GetEventCore() *EventCore {
	if x != nil {
		return x.EventCore
	}
	return nil
}

func (x *GossipEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GossipEvent) GetEventTransaction() []*EventTransaction {
	if x != nil {
		return x.EventTransaction
	}
	return nil
}

var File_event_gossip_event_proto protoreflect.FileDescriptor

const file_event_gossip_event_proto_rawDesc = "" +
	"\n" +
	"\x18event/gossip_event.proto\x12\x1ecom.hedera.hapi.platform.event\x1a\x1devent/event_transaction.proto\x1a\x16event/event_core.proto\"\xd4\x01\n" +
	"\vGossipEvent\x12H\n" +
	"\n" +
	"event_core\x18\x01 \x01(\v2).com.hedera.hapi.platform.event.EventCoreR\teventCore\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12]\n" +
	"\x11event_transaction\x18\x03 \x03(\v20.com.hedera.hapi.platform.event.EventTransactionR\x10eventTransactionBc\n" +
	"%com.hedera.hapi.platform.event.legacyP\x01Z8github.com/cordialsys/hedera-protobufs-go/platform/eventb\x06proto3"

var (
	file_event_gossip_event_proto_rawDescOnce sync.Once
	file_event_gossip_event_proto_rawDescData []byte
)

func file_event_gossip_event_proto_rawDescGZIP() []byte {
	file_event_gossip_event_proto_rawDescOnce.Do(func() {
		file_event_gossip_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_gossip_event_proto_rawDesc), len(file_event_gossip_event_proto_rawDesc)))
	})
	return file_event_gossip_event_proto_rawDescData
}

var file_event_gossip_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_gossip_event_proto_goTypes = []any{
	(*GossipEvent)(nil),      // 0: com.hedera.hapi.platform.event.GossipEvent
	(*EventCore)(nil),        // 1: com.hedera.hapi.platform.event.EventCore
	(*EventTransaction)(nil), // 2: com.hedera.hapi.platform.event.EventTransaction
}
var file_event_gossip_event_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.platform.event.GossipEvent.event_core:type_name -> com.hedera.hapi.platform.event.EventCore
	2, // 1: com.hedera.hapi.platform.event.GossipEvent.event_transaction:type_name -> com.hedera.hapi.platform.event.EventTransaction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_gossip_event_proto_init() }
func file_event_gossip_event_proto_init() {
	if File_event_gossip_event_proto != nil {
		return
	}
	file_event_event_transaction_proto_init()
	file_event_event_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_gossip_event_proto_rawDesc), len(file_event_gossip_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_gossip_event_proto_goTypes,
		DependencyIndexes: file_event_gossip_event_proto_depIdxs,
		MessageInfos:      file_event_gossip_event_proto_msgTypes,
	}.Build()
	File_event_gossip_event_proto = out.File
	file_event_gossip_event_proto_goTypes = nil
	file_event_gossip_event_proto_depIdxs = nil
}
