// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: crypto_add_live_hash.proto

package services

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A hash---presumably of some kind of credential or certificate---along with a list of keys, each
// of which may be either a primitive or a threshold key.
type LiveHash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The account to which the livehash is attached
	AccountId *common.AccountID `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// *
	// The SHA-384 hash of a credential or certificate
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// *
	// A list of keys (primitive or threshold), all of which must sign to attach the livehash to an account, and any one of which can later delete it.
	Keys *common.KeyList `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"`
	// *
	// The duration for which the livehash will remain valid
	Duration      *Duration `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveHash) Reset() {
	*x = LiveHash{}
	mi := &file_crypto_add_live_hash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveHash) ProtoMessage() {}

func (x *LiveHash) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_add_live_hash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveHash.ProtoReflect.Descriptor instead.
func (*LiveHash) Descriptor() ([]byte, []int) {
	return file_crypto_add_live_hash_proto_rawDescGZIP(), []int{0}
}

func (x *LiveHash) GetAccountId() *common.AccountID {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *LiveHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *LiveHash) GetKeys() *common.KeyList {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *LiveHash) GetDuration() *Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// *
// At consensus, attaches the given livehash to the given account.  The hash can be deleted by the
// key controlling the account, or by any of the keys associated to the livehash.  Hence livehashes
// provide a revocation service for their implied credentials; for example, when an authority grants
// a credential to the account, the account owner will cosign with the authority (or authorities) to
// attach a hash of the credential to the account---hence proving the grant. If the credential is
// revoked, then any of the authorities may delete it (or the account owner). In this way, the
// livehash mechanism acts as a revocation service.  An account cannot have two identical livehashes
// associated. To modify the list of keys in a livehash, the livehash should first be deleted, then
// recreated with a new list of keys.
type CryptoAddLiveHashTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A hash of some credential or certificate, along with the keys of the entities that asserted it validity
	LiveHash      *LiveHash `protobuf:"bytes,3,opt,name=liveHash,proto3" json:"liveHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoAddLiveHashTransactionBody) Reset() {
	*x = CryptoAddLiveHashTransactionBody{}
	mi := &file_crypto_add_live_hash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoAddLiveHashTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoAddLiveHashTransactionBody) ProtoMessage() {}

func (x *CryptoAddLiveHashTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_add_live_hash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoAddLiveHashTransactionBody.ProtoReflect.Descriptor instead.
func (*CryptoAddLiveHashTransactionBody) Descriptor() ([]byte, []int) {
	return file_crypto_add_live_hash_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoAddLiveHashTransactionBody) GetLiveHash() *LiveHash {
	if x != nil {
		return x.LiveHash
	}
	return nil
}

var File_crypto_add_live_hash_proto protoreflect.FileDescriptor

const file_crypto_add_live_hash_proto_rawDesc = "" +
	"\n" +
	"\x1acrypto_add_live_hash.proto\x12\x05proto\x1a\x11basic_types.proto\x1a\x0eduration.proto\"\x9f\x01\n" +
	"\bLiveHash\x12.\n" +
	"\taccountId\x18\x01 \x01(\v2\x10.proto.AccountIDR\taccountId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\"\n" +
	"\x04keys\x18\x03 \x01(\v2\x0e.proto.KeyListR\x04keys\x12+\n" +
	"\bduration\x18\x05 \x01(\v2\x0f.proto.DurationR\bduration\"O\n" +
	" CryptoAddLiveHashTransactionBody\x12+\n" +
	"\bliveHash\x18\x03 \x01(\v2\x0f.proto.LiveHashR\bliveHashBZ\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z2github.com/cordialsys/hedera-protobufs-go/servicesb\x06proto3"

var (
	file_crypto_add_live_hash_proto_rawDescOnce sync.Once
	file_crypto_add_live_hash_proto_rawDescData []byte
)

func file_crypto_add_live_hash_proto_rawDescGZIP() []byte {
	file_crypto_add_live_hash_proto_rawDescOnce.Do(func() {
		file_crypto_add_live_hash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_add_live_hash_proto_rawDesc), len(file_crypto_add_live_hash_proto_rawDesc)))
	})
	return file_crypto_add_live_hash_proto_rawDescData
}

var file_crypto_add_live_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_crypto_add_live_hash_proto_goTypes = []any{
	(*LiveHash)(nil),                         // 0: proto.LiveHash
	(*CryptoAddLiveHashTransactionBody)(nil), // 1: proto.CryptoAddLiveHashTransactionBody
	(*common.AccountID)(nil),                 // 2: proto.AccountID
	(*common.KeyList)(nil),                   // 3: proto.KeyList
	(*Duration)(nil),                         // 4: proto.Duration
}
var file_crypto_add_live_hash_proto_depIdxs = []int32{
	2, // 0: proto.LiveHash.accountId:type_name -> proto.AccountID
	3, // 1: proto.LiveHash.keys:type_name -> proto.KeyList
	4, // 2: proto.LiveHash.duration:type_name -> proto.Duration
	0, // 3: proto.CryptoAddLiveHashTransactionBody.liveHash:type_name -> proto.LiveHash
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_crypto_add_live_hash_proto_init() }
func file_crypto_add_live_hash_proto_init() {
	if File_crypto_add_live_hash_proto != nil {
		return
	}
	file_duration_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_add_live_hash_proto_rawDesc), len(file_crypto_add_live_hash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crypto_add_live_hash_proto_goTypes,
		DependencyIndexes: file_crypto_add_live_hash_proto_depIdxs,
		MessageInfos:      file_crypto_add_live_hash_proto_msgTypes,
	}.Build()
	File_crypto_add_live_hash_proto = out.File
	file_crypto_add_live_hash_proto_goTypes = nil
	file_crypto_add_live_hash_proto_depIdxs = nil
}
