// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: crypto_get_info.proto

package services

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Get all the information about an account, including the balance. This does not get the list of
// account records.
type CryptoGetInfoQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard info sent from client to node, including the signed payment, and what kind of
	// response is requested (cost, state proof, both, or neither).
	Header *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// The account ID for which information is requested
	AccountID     *common.AccountID `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoGetInfoQuery) Reset() {
	*x = CryptoGetInfoQuery{}
	mi := &file_crypto_get_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoGetInfoQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoGetInfoQuery) ProtoMessage() {}

func (x *CryptoGetInfoQuery) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_get_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoGetInfoQuery.ProtoReflect.Descriptor instead.
func (*CryptoGetInfoQuery) Descriptor() ([]byte, []int) {
	return file_crypto_get_info_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoGetInfoQuery) GetHeader() *QueryHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CryptoGetInfoQuery) GetAccountID() *common.AccountID {
	if x != nil {
		return x.AccountID
	}
	return nil
}

// *
// Response when the client sends the node CryptoGetInfoQuery
type CryptoGetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard response from node to client, including the requested fields: cost, or state proof,
	// or both, or neither
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// Info about the account (a state proof can be generated for this)
	AccountInfo   *CryptoGetInfoResponse_AccountInfo `protobuf:"bytes,2,opt,name=accountInfo,proto3" json:"accountInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoGetInfoResponse) Reset() {
	*x = CryptoGetInfoResponse{}
	mi := &file_crypto_get_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoGetInfoResponse) ProtoMessage() {}

func (x *CryptoGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_get_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoGetInfoResponse.ProtoReflect.Descriptor instead.
func (*CryptoGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_crypto_get_info_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoGetInfoResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CryptoGetInfoResponse) GetAccountInfo() *CryptoGetInfoResponse_AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

type CryptoGetInfoResponse_AccountInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The account ID for which this information applies
	AccountID *common.AccountID `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	// *
	// The Contract Account ID comprising of both the contract instance and the cryptocurrency
	// account owned by the contract instance, in the format used by Solidity
	ContractAccountID string `protobuf:"bytes,2,opt,name=contractAccountID,proto3" json:"contractAccountID,omitempty"`
	// *
	// If true, then this account has been deleted, it will disappear when it expires, and all
	// transactions for it will fail except the transaction to extend its expiration date
	Deleted bool `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// *
	// [Deprecated] The Account ID of the account to which this is proxy staked. If proxyAccountID is null,
	// or is an invalid account, or is an account that isn't a node, then this account is
	// automatically proxy staked to a node chosen by the network, but without earning payments.
	// If the proxyAccountID account refuses to accept proxy staking , or if it is not currently
	// running a node, then it will behave as if proxyAccountID was null.
	//
	// Deprecated: Marked as deprecated in crypto_get_info.proto.
	ProxyAccountID *common.AccountID `protobuf:"bytes,4,opt,name=proxyAccountID,proto3" json:"proxyAccountID,omitempty"`
	// *
	// The total number of tinybars proxy staked to this account
	ProxyReceived int64 `protobuf:"varint,6,opt,name=proxyReceived,proto3" json:"proxyReceived,omitempty"`
	// *
	// The key for the account, which must sign in order to transfer out, or to modify the
	// account in any way other than extending its expiration date.
	Key *common.Key `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	// *
	// The current balance of account in tinybars
	Balance uint64 `protobuf:"varint,8,opt,name=balance,proto3" json:"balance,omitempty"`
	// *
	// [Deprecated]. The threshold amount, in tinybars, at which a record is created of any
	// transaction that decreases the balance of this account by more than the threshold
	//
	// Deprecated: Marked as deprecated in crypto_get_info.proto.
	GenerateSendRecordThreshold uint64 `protobuf:"varint,9,opt,name=generateSendRecordThreshold,proto3" json:"generateSendRecordThreshold,omitempty"`
	// *
	// [Deprecated]. The threshold amount, in tinybars, at which a record is created of any
	// transaction that increases the balance of this account by more than the threshold
	//
	// Deprecated: Marked as deprecated in crypto_get_info.proto.
	GenerateReceiveRecordThreshold uint64 `protobuf:"varint,10,opt,name=generateReceiveRecordThreshold,proto3" json:"generateReceiveRecordThreshold,omitempty"`
	// *
	// If true, no transaction can transfer to this account unless signed by this account's key
	ReceiverSigRequired bool `protobuf:"varint,11,opt,name=receiverSigRequired,proto3" json:"receiverSigRequired,omitempty"`
	// *
	// The TimeStamp time at which this account is set to expire
	ExpirationTime *common.Timestamp `protobuf:"bytes,12,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	// *
	// The duration for expiration time will extend every this many seconds. If there are
	// insufficient funds, then it extends as long as possible. If it is empty when it expires,
	// then it is deleted.
	AutoRenewPeriod *Duration `protobuf:"bytes,13,opt,name=autoRenewPeriod,proto3" json:"autoRenewPeriod,omitempty"`
	// *
	// All of the livehashes attached to the account (each of which is a hash along with the
	// keys that authorized it and can delete it)
	LiveHashes []*LiveHash `protobuf:"bytes,14,rep,name=liveHashes,proto3" json:"liveHashes,omitempty"`
	// *
	// [DEPRECATED] The metadata of the tokens associated to the account. This field was
	// deprecated by <a href="https://hips.hedera.com/hip/hip-367">HIP-367</a>, which allowed
	// an account to be associated to an unlimited number of tokens. This scale makes it more
	// efficient for users to consult mirror nodes to review their token associations.
	//
	// Deprecated: Marked as deprecated in crypto_get_info.proto.
	TokenRelationships []*common.TokenRelationship `protobuf:"bytes,15,rep,name=tokenRelationships,proto3" json:"tokenRelationships,omitempty"`
	// *
	// The memo associated with the account
	Memo string `protobuf:"bytes,16,opt,name=memo,proto3" json:"memo,omitempty"`
	// *
	// The number of NFTs owned by this account
	OwnedNfts int64 `protobuf:"varint,17,opt,name=ownedNfts,proto3" json:"ownedNfts,omitempty"`
	// *
	// The maximum number of tokens that an Account can be implicitly associated with.
	MaxAutomaticTokenAssociations int32 `protobuf:"varint,18,opt,name=max_automatic_token_associations,json=maxAutomaticTokenAssociations,proto3" json:"max_automatic_token_associations,omitempty"`
	// *
	// The alias of this account
	Alias []byte `protobuf:"bytes,19,opt,name=alias,proto3" json:"alias,omitempty"`
	// *
	// The ledger ID the response was returned from; please see <a href="https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-198.md">HIP-198</a> for the network-specific IDs.
	LedgerId []byte `protobuf:"bytes,20,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	// *
	// The ethereum transaction nonce associated with this account.
	EthereumNonce int64 `protobuf:"varint,21,opt,name=ethereum_nonce,json=ethereumNonce,proto3" json:"ethereum_nonce,omitempty"`
	// *
	// Staking metadata for this account.
	StakingInfo   *common.StakingInfo `protobuf:"bytes,22,opt,name=staking_info,json=stakingInfo,proto3" json:"staking_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoGetInfoResponse_AccountInfo) Reset() {
	*x = CryptoGetInfoResponse_AccountInfo{}
	mi := &file_crypto_get_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoGetInfoResponse_AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoGetInfoResponse_AccountInfo) ProtoMessage() {}

func (x *CryptoGetInfoResponse_AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_get_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoGetInfoResponse_AccountInfo.ProtoReflect.Descriptor instead.
func (*CryptoGetInfoResponse_AccountInfo) Descriptor() ([]byte, []int) {
	return file_crypto_get_info_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CryptoGetInfoResponse_AccountInfo) GetAccountID() *common.AccountID {
	if x != nil {
		return x.AccountID
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetContractAccountID() string {
	if x != nil {
		return x.ContractAccountID
	}
	return ""
}

func (x *CryptoGetInfoResponse_AccountInfo) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Deprecated: Marked as deprecated in crypto_get_info.proto.
func (x *CryptoGetInfoResponse_AccountInfo) GetProxyAccountID() *common.AccountID {
	if x != nil {
		return x.ProxyAccountID
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetProxyReceived() int64 {
	if x != nil {
		return x.ProxyReceived
	}
	return 0
}

func (x *CryptoGetInfoResponse_AccountInfo) GetKey() *common.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// Deprecated: Marked as deprecated in crypto_get_info.proto.
func (x *CryptoGetInfoResponse_AccountInfo) GetGenerateSendRecordThreshold() uint64 {
	if x != nil {
		return x.GenerateSendRecordThreshold
	}
	return 0
}

// Deprecated: Marked as deprecated in crypto_get_info.proto.
func (x *CryptoGetInfoResponse_AccountInfo) GetGenerateReceiveRecordThreshold() uint64 {
	if x != nil {
		return x.GenerateReceiveRecordThreshold
	}
	return 0
}

func (x *CryptoGetInfoResponse_AccountInfo) GetReceiverSigRequired() bool {
	if x != nil {
		return x.ReceiverSigRequired
	}
	return false
}

func (x *CryptoGetInfoResponse_AccountInfo) GetExpirationTime() *common.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetAutoRenewPeriod() *Duration {
	if x != nil {
		return x.AutoRenewPeriod
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetLiveHashes() []*LiveHash {
	if x != nil {
		return x.LiveHashes
	}
	return nil
}

// Deprecated: Marked as deprecated in crypto_get_info.proto.
func (x *CryptoGetInfoResponse_AccountInfo) GetTokenRelationships() []*common.TokenRelationship {
	if x != nil {
		return x.TokenRelationships
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *CryptoGetInfoResponse_AccountInfo) GetOwnedNfts() int64 {
	if x != nil {
		return x.OwnedNfts
	}
	return 0
}

func (x *CryptoGetInfoResponse_AccountInfo) GetMaxAutomaticTokenAssociations() int32 {
	if x != nil {
		return x.MaxAutomaticTokenAssociations
	}
	return 0
}

func (x *CryptoGetInfoResponse_AccountInfo) GetAlias() []byte {
	if x != nil {
		return x.Alias
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetLedgerId() []byte {
	if x != nil {
		return x.LedgerId
	}
	return nil
}

func (x *CryptoGetInfoResponse_AccountInfo) GetEthereumNonce() int64 {
	if x != nil {
		return x.EthereumNonce
	}
	return 0
}

func (x *CryptoGetInfoResponse_AccountInfo) GetStakingInfo() *common.StakingInfo {
	if x != nil {
		return x.StakingInfo
	}
	return nil
}

var File_crypto_get_info_proto protoreflect.FileDescriptor

const file_crypto_get_info_proto_rawDesc = "" +
	"\n" +
	"\x15crypto_get_info.proto\x12\x05proto\x1a\x0ftimestamp.proto\x1a\x0eduration.proto\x1a\x11basic_types.proto\x1a\x12query_header.proto\x1a\x15response_header.proto\x1a\x1acrypto_add_live_hash.proto\"p\n" +
	"\x12CryptoGetInfoQuery\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.proto.QueryHeaderR\x06header\x12.\n" +
	"\taccountID\x18\x02 \x01(\v2\x10.proto.AccountIDR\taccountID\"\xfa\b\n" +
	"\x15CryptoGetInfoResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.proto.ResponseHeaderR\x06header\x12J\n" +
	"\vaccountInfo\x18\x02 \x01(\v2(.proto.CryptoGetInfoResponse.AccountInfoR\vaccountInfo\x1a\xe5\a\n" +
	"\vAccountInfo\x12.\n" +
	"\taccountID\x18\x01 \x01(\v2\x10.proto.AccountIDR\taccountID\x12,\n" +
	"\x11contractAccountID\x18\x02 \x01(\tR\x11contractAccountID\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x12<\n" +
	"\x0eproxyAccountID\x18\x04 \x01(\v2\x10.proto.AccountIDB\x02\x18\x01R\x0eproxyAccountID\x12$\n" +
	"\rproxyReceived\x18\x06 \x01(\x03R\rproxyReceived\x12\x1c\n" +
	"\x03key\x18\a \x01(\v2\n" +
	".proto.KeyR\x03key\x12\x18\n" +
	"\abalance\x18\b \x01(\x04R\abalance\x12D\n" +
	"\x1bgenerateSendRecordThreshold\x18\t \x01(\x04B\x02\x18\x01R\x1bgenerateSendRecordThreshold\x12J\n" +
	"\x1egenerateReceiveRecordThreshold\x18\n" +
	" \x01(\x04B\x02\x18\x01R\x1egenerateReceiveRecordThreshold\x120\n" +
	"\x13receiverSigRequired\x18\v \x01(\bR\x13receiverSigRequired\x128\n" +
	"\x0eexpirationTime\x18\f \x01(\v2\x10.proto.TimestampR\x0eexpirationTime\x129\n" +
	"\x0fautoRenewPeriod\x18\r \x01(\v2\x0f.proto.DurationR\x0fautoRenewPeriod\x12/\n" +
	"\n" +
	"liveHashes\x18\x0e \x03(\v2\x0f.proto.LiveHashR\n" +
	"liveHashes\x12L\n" +
	"\x12tokenRelationships\x18\x0f \x03(\v2\x18.proto.TokenRelationshipB\x02\x18\x01R\x12tokenRelationships\x12\x12\n" +
	"\x04memo\x18\x10 \x01(\tR\x04memo\x12\x1c\n" +
	"\townedNfts\x18\x11 \x01(\x03R\townedNfts\x12G\n" +
	" max_automatic_token_associations\x18\x12 \x01(\x05R\x1dmaxAutomaticTokenAssociations\x12\x14\n" +
	"\x05alias\x18\x13 \x01(\fR\x05alias\x12\x1b\n" +
	"\tledger_id\x18\x14 \x01(\fR\bledgerId\x12%\n" +
	"\x0eethereum_nonce\x18\x15 \x01(\x03R\rethereumNonce\x125\n" +
	"\fstaking_info\x18\x16 \x01(\v2\x12.proto.StakingInfoR\vstakingInfoBZ\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z2github.com/cordialsys/hedera-protobufs-go/servicesb\x06proto3"

var (
	file_crypto_get_info_proto_rawDescOnce sync.Once
	file_crypto_get_info_proto_rawDescData []byte
)

func file_crypto_get_info_proto_rawDescGZIP() []byte {
	file_crypto_get_info_proto_rawDescOnce.Do(func() {
		file_crypto_get_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_get_info_proto_rawDesc), len(file_crypto_get_info_proto_rawDesc)))
	})
	return file_crypto_get_info_proto_rawDescData
}

var file_crypto_get_info_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_crypto_get_info_proto_goTypes = []any{
	(*CryptoGetInfoQuery)(nil),                // 0: proto.CryptoGetInfoQuery
	(*CryptoGetInfoResponse)(nil),             // 1: proto.CryptoGetInfoResponse
	(*CryptoGetInfoResponse_AccountInfo)(nil), // 2: proto.CryptoGetInfoResponse.AccountInfo
	(*QueryHeader)(nil),                       // 3: proto.QueryHeader
	(*common.AccountID)(nil),                  // 4: proto.AccountID
	(*ResponseHeader)(nil),                    // 5: proto.ResponseHeader
	(*common.Key)(nil),                        // 6: proto.Key
	(*common.Timestamp)(nil),                  // 7: proto.Timestamp
	(*Duration)(nil),                          // 8: proto.Duration
	(*LiveHash)(nil),                          // 9: proto.LiveHash
	(*common.TokenRelationship)(nil),          // 10: proto.TokenRelationship
	(*common.StakingInfo)(nil),                // 11: proto.StakingInfo
}
var file_crypto_get_info_proto_depIdxs = []int32{
	3,  // 0: proto.CryptoGetInfoQuery.header:type_name -> proto.QueryHeader
	4,  // 1: proto.CryptoGetInfoQuery.accountID:type_name -> proto.AccountID
	5,  // 2: proto.CryptoGetInfoResponse.header:type_name -> proto.ResponseHeader
	2,  // 3: proto.CryptoGetInfoResponse.accountInfo:type_name -> proto.CryptoGetInfoResponse.AccountInfo
	4,  // 4: proto.CryptoGetInfoResponse.AccountInfo.accountID:type_name -> proto.AccountID
	4,  // 5: proto.CryptoGetInfoResponse.AccountInfo.proxyAccountID:type_name -> proto.AccountID
	6,  // 6: proto.CryptoGetInfoResponse.AccountInfo.key:type_name -> proto.Key
	7,  // 7: proto.CryptoGetInfoResponse.AccountInfo.expirationTime:type_name -> proto.Timestamp
	8,  // 8: proto.CryptoGetInfoResponse.AccountInfo.autoRenewPeriod:type_name -> proto.Duration
	9,  // 9: proto.CryptoGetInfoResponse.AccountInfo.liveHashes:type_name -> proto.LiveHash
	10, // 10: proto.CryptoGetInfoResponse.AccountInfo.tokenRelationships:type_name -> proto.TokenRelationship
	11, // 11: proto.CryptoGetInfoResponse.AccountInfo.staking_info:type_name -> proto.StakingInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_crypto_get_info_proto_init() }
func file_crypto_get_info_proto_init() {
	if File_crypto_get_info_proto != nil {
		return
	}
	file_duration_proto_init()
	file_query_header_proto_init()
	file_response_header_proto_init()
	file_crypto_add_live_hash_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_get_info_proto_rawDesc), len(file_crypto_get_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crypto_get_info_proto_goTypes,
		DependencyIndexes: file_crypto_get_info_proto_depIdxs,
		MessageInfos:      file_crypto_get_info_proto_msgTypes,
	}.Build()
	File_crypto_get_info_proto = out.File
	file_crypto_get_info_proto_goTypes = nil
	file_crypto_get_info_proto_depIdxs = nil
}
