// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: file_get_contents.proto

package services

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Get the contents of a file. The content field is empty (no bytes) if the file is empty.
type FileGetContentsQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard info sent from client to node, including the signed payment, and what kind of
	// response is requested (cost, state proof, both, or neither).
	Header *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// The file ID of the file whose contents are requested
	FileID        *common.FileID `protobuf:"bytes,2,opt,name=fileID,proto3" json:"fileID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGetContentsQuery) Reset() {
	*x = FileGetContentsQuery{}
	mi := &file_file_get_contents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetContentsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetContentsQuery) ProtoMessage() {}

func (x *FileGetContentsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_file_get_contents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetContentsQuery.ProtoReflect.Descriptor instead.
func (*FileGetContentsQuery) Descriptor() ([]byte, []int) {
	return file_file_get_contents_proto_rawDescGZIP(), []int{0}
}

func (x *FileGetContentsQuery) GetHeader() *QueryHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FileGetContentsQuery) GetFileID() *common.FileID {
	if x != nil {
		return x.FileID
	}
	return nil
}

// *
// Response when the client sends the node FileGetContentsQuery
type FileGetContentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard response from node to client, including the requested fields: cost, or state proof,
	// or both, or neither
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// the file ID and contents (a state proof can be generated for this)
	FileContents  *FileGetContentsResponse_FileContents `protobuf:"bytes,2,opt,name=fileContents,proto3" json:"fileContents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGetContentsResponse) Reset() {
	*x = FileGetContentsResponse{}
	mi := &file_file_get_contents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetContentsResponse) ProtoMessage() {}

func (x *FileGetContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_get_contents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetContentsResponse.ProtoReflect.Descriptor instead.
func (*FileGetContentsResponse) Descriptor() ([]byte, []int) {
	return file_file_get_contents_proto_rawDescGZIP(), []int{1}
}

func (x *FileGetContentsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FileGetContentsResponse) GetFileContents() *FileGetContentsResponse_FileContents {
	if x != nil {
		return x.FileContents
	}
	return nil
}

type FileGetContentsResponse_FileContents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The file ID of the file whose contents are being returned
	FileID *common.FileID `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// *
	// The bytes contained in the file
	Contents      []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGetContentsResponse_FileContents) Reset() {
	*x = FileGetContentsResponse_FileContents{}
	mi := &file_file_get_contents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetContentsResponse_FileContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetContentsResponse_FileContents) ProtoMessage() {}

func (x *FileGetContentsResponse_FileContents) ProtoReflect() protoreflect.Message {
	mi := &file_file_get_contents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetContentsResponse_FileContents.ProtoReflect.Descriptor instead.
func (*FileGetContentsResponse_FileContents) Descriptor() ([]byte, []int) {
	return file_file_get_contents_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FileGetContentsResponse_FileContents) GetFileID() *common.FileID {
	if x != nil {
		return x.FileID
	}
	return nil
}

func (x *FileGetContentsResponse_FileContents) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_file_get_contents_proto protoreflect.FileDescriptor

const file_file_get_contents_proto_rawDesc = "" +
	"\n" +
	"\x17file_get_contents.proto\x12\x05proto\x1a\x11basic_types.proto\x1a\x12query_header.proto\x1a\x15response_header.proto\"i\n" +
	"\x14FileGetContentsQuery\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.proto.QueryHeaderR\x06header\x12%\n" +
	"\x06fileID\x18\x02 \x01(\v2\r.proto.FileIDR\x06fileID\"\xec\x01\n" +
	"\x17FileGetContentsResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.proto.ResponseHeaderR\x06header\x12O\n" +
	"\ffileContents\x18\x02 \x01(\v2+.proto.FileGetContentsResponse.FileContentsR\ffileContents\x1aQ\n" +
	"\fFileContents\x12%\n" +
	"\x06fileID\x18\x01 \x01(\v2\r.proto.FileIDR\x06fileID\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\fR\bcontentsBZ\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z2github.com/cordialsys/hedera-protobufs-go/servicesb\x06proto3"

var (
	file_file_get_contents_proto_rawDescOnce sync.Once
	file_file_get_contents_proto_rawDescData []byte
)

func file_file_get_contents_proto_rawDescGZIP() []byte {
	file_file_get_contents_proto_rawDescOnce.Do(func() {
		file_file_get_contents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_get_contents_proto_rawDesc), len(file_file_get_contents_proto_rawDesc)))
	})
	return file_file_get_contents_proto_rawDescData
}

var file_file_get_contents_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_file_get_contents_proto_goTypes = []any{
	(*FileGetContentsQuery)(nil),                 // 0: proto.FileGetContentsQuery
	(*FileGetContentsResponse)(nil),              // 1: proto.FileGetContentsResponse
	(*FileGetContentsResponse_FileContents)(nil), // 2: proto.FileGetContentsResponse.FileContents
	(*QueryHeader)(nil),                          // 3: proto.QueryHeader
	(*common.FileID)(nil),                        // 4: proto.FileID
	(*ResponseHeader)(nil),                       // 5: proto.ResponseHeader
}
var file_file_get_contents_proto_depIdxs = []int32{
	3, // 0: proto.FileGetContentsQuery.header:type_name -> proto.QueryHeader
	4, // 1: proto.FileGetContentsQuery.fileID:type_name -> proto.FileID
	5, // 2: proto.FileGetContentsResponse.header:type_name -> proto.ResponseHeader
	2, // 3: proto.FileGetContentsResponse.fileContents:type_name -> proto.FileGetContentsResponse.FileContents
	4, // 4: proto.FileGetContentsResponse.FileContents.fileID:type_name -> proto.FileID
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_file_get_contents_proto_init() }
func file_file_get_contents_proto_init() {
	if File_file_get_contents_proto != nil {
		return
	}
	file_query_header_proto_init()
	file_response_header_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_get_contents_proto_rawDesc), len(file_file_get_contents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_get_contents_proto_goTypes,
		DependencyIndexes: file_file_get_contents_proto_depIdxs,
		MessageInfos:      file_file_get_contents_proto_msgTypes,
	}.Build()
	File_file_get_contents_proto = out.File
	file_file_get_contents_proto_goTypes = nil
	file_file_get_contents_proto_depIdxs = nil
}
