// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: get_by_solidity_id.proto

package services

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Get the IDs in the format used by transactions, given the ID in the format used by Solidity. If
// the Solidity ID is for a smart contract instance, then both the ContractID and associated
// AccountID will be returned.
type GetBySolidityIDQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard info sent from client to node, including the signed payment, and what kind of
	// response is requested (cost, state proof, both, or neither).
	Header *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// The ID in the format used by Solidity
	SolidityID    string `protobuf:"bytes,2,opt,name=solidityID,proto3" json:"solidityID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBySolidityIDQuery) Reset() {
	*x = GetBySolidityIDQuery{}
	mi := &file_get_by_solidity_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBySolidityIDQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBySolidityIDQuery) ProtoMessage() {}

func (x *GetBySolidityIDQuery) ProtoReflect() protoreflect.Message {
	mi := &file_get_by_solidity_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBySolidityIDQuery.ProtoReflect.Descriptor instead.
func (*GetBySolidityIDQuery) Descriptor() ([]byte, []int) {
	return file_get_by_solidity_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetBySolidityIDQuery) GetHeader() *QueryHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBySolidityIDQuery) GetSolidityID() string {
	if x != nil {
		return x.SolidityID
	}
	return ""
}

// *
// Response when the client sends the node GetBySolidityIDQuery
type GetBySolidityIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard response from node to client, including the requested fields: cost, or state proof,
	// or both, or neither
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// The Account ID for the cryptocurrency account
	AccountID *common.AccountID `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	// *
	// The file Id for the file
	FileID *common.FileID `protobuf:"bytes,3,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// *
	// A smart contract ID for the instance (if this is included, then the associated accountID will
	// also be included)
	ContractID    *common.ContractID `protobuf:"bytes,4,opt,name=contractID,proto3" json:"contractID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBySolidityIDResponse) Reset() {
	*x = GetBySolidityIDResponse{}
	mi := &file_get_by_solidity_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBySolidityIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBySolidityIDResponse) ProtoMessage() {}

func (x *GetBySolidityIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_by_solidity_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBySolidityIDResponse.ProtoReflect.Descriptor instead.
func (*GetBySolidityIDResponse) Descriptor() ([]byte, []int) {
	return file_get_by_solidity_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetBySolidityIDResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBySolidityIDResponse) GetAccountID() *common.AccountID {
	if x != nil {
		return x.AccountID
	}
	return nil
}

func (x *GetBySolidityIDResponse) GetFileID() *common.FileID {
	if x != nil {
		return x.FileID
	}
	return nil
}

func (x *GetBySolidityIDResponse) GetContractID() *common.ContractID {
	if x != nil {
		return x.ContractID
	}
	return nil
}

var File_get_by_solidity_id_proto protoreflect.FileDescriptor

const file_get_by_solidity_id_proto_rawDesc = "" +
	"\n" +
	"\x18get_by_solidity_id.proto\x12\x05proto\x1a\x11basic_types.proto\x1a\x12query_header.proto\x1a\x15response_header.proto\"b\n" +
	"\x14GetBySolidityIDQuery\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.proto.QueryHeaderR\x06header\x12\x1e\n" +
	"\n" +
	"solidityID\x18\x02 \x01(\tR\n" +
	"solidityID\"\xd2\x01\n" +
	"\x17GetBySolidityIDResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.proto.ResponseHeaderR\x06header\x12.\n" +
	"\taccountID\x18\x02 \x01(\v2\x10.proto.AccountIDR\taccountID\x12%\n" +
	"\x06fileID\x18\x03 \x01(\v2\r.proto.FileIDR\x06fileID\x121\n" +
	"\n" +
	"contractID\x18\x04 \x01(\v2\x11.proto.ContractIDR\n" +
	"contractIDBZ\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z2github.com/cordialsys/hedera-protobufs-go/servicesb\x06proto3"

var (
	file_get_by_solidity_id_proto_rawDescOnce sync.Once
	file_get_by_solidity_id_proto_rawDescData []byte
)

func file_get_by_solidity_id_proto_rawDescGZIP() []byte {
	file_get_by_solidity_id_proto_rawDescOnce.Do(func() {
		file_get_by_solidity_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_by_solidity_id_proto_rawDesc), len(file_get_by_solidity_id_proto_rawDesc)))
	})
	return file_get_by_solidity_id_proto_rawDescData
}

var file_get_by_solidity_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_by_solidity_id_proto_goTypes = []any{
	(*GetBySolidityIDQuery)(nil),    // 0: proto.GetBySolidityIDQuery
	(*GetBySolidityIDResponse)(nil), // 1: proto.GetBySolidityIDResponse
	(*QueryHeader)(nil),             // 2: proto.QueryHeader
	(*ResponseHeader)(nil),          // 3: proto.ResponseHeader
	(*common.AccountID)(nil),        // 4: proto.AccountID
	(*common.FileID)(nil),           // 5: proto.FileID
	(*common.ContractID)(nil),       // 6: proto.ContractID
}
var file_get_by_solidity_id_proto_depIdxs = []int32{
	2, // 0: proto.GetBySolidityIDQuery.header:type_name -> proto.QueryHeader
	3, // 1: proto.GetBySolidityIDResponse.header:type_name -> proto.ResponseHeader
	4, // 2: proto.GetBySolidityIDResponse.accountID:type_name -> proto.AccountID
	5, // 3: proto.GetBySolidityIDResponse.fileID:type_name -> proto.FileID
	6, // 4: proto.GetBySolidityIDResponse.contractID:type_name -> proto.ContractID
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_get_by_solidity_id_proto_init() }
func file_get_by_solidity_id_proto_init() {
	if File_get_by_solidity_id_proto != nil {
		return
	}
	file_query_header_proto_init()
	file_response_header_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_by_solidity_id_proto_rawDesc), len(file_get_by_solidity_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_by_solidity_id_proto_goTypes,
		DependencyIndexes: file_get_by_solidity_id_proto_depIdxs,
		MessageInfos:      file_get_by_solidity_id_proto_msgTypes,
	}.Build()
	File_get_by_solidity_id_proto = out.File
	file_get_by_solidity_id_proto_goTypes = nil
	file_get_by_solidity_id_proto_depIdxs = nil
}
