// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: token_dissociate.proto

package services

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Dissociates the provided account with the provided tokens. Must be signed by the provided
// Account's key.
// If the provided account is not found, the transaction will resolve to INVALID_ACCOUNT_ID.
// If the provided account has been deleted, the transaction will resolve to ACCOUNT_DELETED.
// If any of the provided tokens is not found, the transaction will resolve to INVALID_TOKEN_REF.
// If any of the provided tokens has been deleted, the transaction will resolve to TOKEN_WAS_DELETED.
// If an association between the provided account and any of the tokens does not exist, the
// transaction will resolve to TOKEN_NOT_ASSOCIATED_TO_ACCOUNT.
// If a token has not been deleted and has not expired, and the user has a nonzero balance, the
// transaction will resolve to TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES.
// If a <b>fungible token</b> has expired, the user can disassociate even if their token balance is
// not zero.
// If a <b>non fungible token</b> has expired, the user can <b>not</b> disassociate if their token
// balance is not zero. The transaction will resolve to TRANSACTION_REQUIRED_ZERO_TOKEN_BALANCES.
// On success, associations between the provided account and tokens are removed.
type TokenDissociateTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The account to be dissociated with the provided tokens
	Account *common.AccountID `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// *
	// The tokens to be dissociated with the provided account
	Tokens        []*common.TokenID `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDissociateTransactionBody) Reset() {
	*x = TokenDissociateTransactionBody{}
	mi := &file_token_dissociate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDissociateTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDissociateTransactionBody) ProtoMessage() {}

func (x *TokenDissociateTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_token_dissociate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDissociateTransactionBody.ProtoReflect.Descriptor instead.
func (*TokenDissociateTransactionBody) Descriptor() ([]byte, []int) {
	return file_token_dissociate_proto_rawDescGZIP(), []int{0}
}

func (x *TokenDissociateTransactionBody) GetAccount() *common.AccountID {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *TokenDissociateTransactionBody) GetTokens() []*common.TokenID {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_token_dissociate_proto protoreflect.FileDescriptor

const file_token_dissociate_proto_rawDesc = "" +
	"\n" +
	"\x16token_dissociate.proto\x12\x05proto\x1a\x11basic_types.proto\"t\n" +
	"\x1eTokenDissociateTransactionBody\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.proto.AccountIDR\aaccount\x12&\n" +
	"\x06tokens\x18\x02 \x03(\v2\x0e.proto.TokenIDR\x06tokensBZ\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z2github.com/cordialsys/hedera-protobufs-go/servicesb\x06proto3"

var (
	file_token_dissociate_proto_rawDescOnce sync.Once
	file_token_dissociate_proto_rawDescData []byte
)

func file_token_dissociate_proto_rawDescGZIP() []byte {
	file_token_dissociate_proto_rawDescOnce.Do(func() {
		file_token_dissociate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_dissociate_proto_rawDesc), len(file_token_dissociate_proto_rawDesc)))
	})
	return file_token_dissociate_proto_rawDescData
}

var file_token_dissociate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_dissociate_proto_goTypes = []any{
	(*TokenDissociateTransactionBody)(nil), // 0: proto.TokenDissociateTransactionBody
	(*common.AccountID)(nil),               // 1: proto.AccountID
	(*common.TokenID)(nil),                 // 2: proto.TokenID
}
var file_token_dissociate_proto_depIdxs = []int32{
	1, // 0: proto.TokenDissociateTransactionBody.account:type_name -> proto.AccountID
	2, // 1: proto.TokenDissociateTransactionBody.tokens:type_name -> proto.TokenID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_dissociate_proto_init() }
func file_token_dissociate_proto_init() {
	if File_token_dissociate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_dissociate_proto_rawDesc), len(file_token_dissociate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_dissociate_proto_goTypes,
		DependencyIndexes: file_token_dissociate_proto_depIdxs,
		MessageInfos:      file_token_dissociate_proto_msgTypes,
	}.Build()
	File_token_dissociate_proto = out.File
	file_token_dissociate_proto_goTypes = nil
	file_token_dissociate_proto_depIdxs = nil
}
