// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: token_unfreeze_account.proto

package services

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Unfreezes transfers of the specified token for the account. Must be signed by the Token's
// freezeKey.
// If the provided account is not found, the transaction will resolve to INVALID_ACCOUNT_ID.
// If the provided account has been deleted, the transaction will resolve to ACCOUNT_DELETED.
// If the provided token is not found, the transaction will resolve to INVALID_TOKEN_ID.
// If the provided token has been deleted, the transaction will resolve to TOKEN_WAS_DELETED.
// If an Association between the provided token and account is not found, the transaction will
// resolve to TOKEN_NOT_ASSOCIATED_TO_ACCOUNT.
// If no Freeze Key is defined, the transaction will resolve to TOKEN_HAS_NO_FREEZE_KEY.
// Once executed the Account is marked as Unfrozen and will be able to receive or send tokens. The
// operation is idempotent.
type TokenUnfreezeAccountTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The token for which this account will be unfrozen. If token does not exist, transaction
	// results in INVALID_TOKEN_ID
	Token *common.TokenID `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// *
	// The account to be unfrozen
	Account       *common.AccountID `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUnfreezeAccountTransactionBody) Reset() {
	*x = TokenUnfreezeAccountTransactionBody{}
	mi := &file_token_unfreeze_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUnfreezeAccountTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUnfreezeAccountTransactionBody) ProtoMessage() {}

func (x *TokenUnfreezeAccountTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_token_unfreeze_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUnfreezeAccountTransactionBody.ProtoReflect.Descriptor instead.
func (*TokenUnfreezeAccountTransactionBody) Descriptor() ([]byte, []int) {
	return file_token_unfreeze_account_proto_rawDescGZIP(), []int{0}
}

func (x *TokenUnfreezeAccountTransactionBody) GetToken() *common.TokenID {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TokenUnfreezeAccountTransactionBody) GetAccount() *common.AccountID {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_token_unfreeze_account_proto protoreflect.FileDescriptor

const file_token_unfreeze_account_proto_rawDesc = "" +
	"\n" +
	"\x1ctoken_unfreeze_account.proto\x12\x05proto\x1a\x11basic_types.proto\"w\n" +
	"#TokenUnfreezeAccountTransactionBody\x12$\n" +
	"\x05token\x18\x01 \x01(\v2\x0e.proto.TokenIDR\x05token\x12*\n" +
	"\aaccount\x18\x02 \x01(\v2\x10.proto.AccountIDR\aaccountBZ\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z2github.com/cordialsys/hedera-protobufs-go/servicesb\x06proto3"

var (
	file_token_unfreeze_account_proto_rawDescOnce sync.Once
	file_token_unfreeze_account_proto_rawDescData []byte
)

func file_token_unfreeze_account_proto_rawDescGZIP() []byte {
	file_token_unfreeze_account_proto_rawDescOnce.Do(func() {
		file_token_unfreeze_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_unfreeze_account_proto_rawDesc), len(file_token_unfreeze_account_proto_rawDesc)))
	})
	return file_token_unfreeze_account_proto_rawDescData
}

var file_token_unfreeze_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_unfreeze_account_proto_goTypes = []any{
	(*TokenUnfreezeAccountTransactionBody)(nil), // 0: proto.TokenUnfreezeAccountTransactionBody
	(*common.TokenID)(nil),                      // 1: proto.TokenID
	(*common.AccountID)(nil),                    // 2: proto.AccountID
}
var file_token_unfreeze_account_proto_depIdxs = []int32{
	1, // 0: proto.TokenUnfreezeAccountTransactionBody.token:type_name -> proto.TokenID
	2, // 1: proto.TokenUnfreezeAccountTransactionBody.account:type_name -> proto.AccountID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_unfreeze_account_proto_init() }
func file_token_unfreeze_account_proto_init() {
	if File_token_unfreeze_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_unfreeze_account_proto_rawDesc), len(file_token_unfreeze_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_unfreeze_account_proto_goTypes,
		DependencyIndexes: file_token_unfreeze_account_proto_depIdxs,
		MessageInfos:      file_token_unfreeze_account_proto_msgTypes,
	}.Build()
	File_token_unfreeze_account_proto = out.File
	file_token_unfreeze_account_proto_goTypes = nil
	file_token_unfreeze_account_proto_depIdxs = nil
}
