// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: token_get_nft_infos.proto

package services

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Applicable only to tokens of type NON_FUNGIBLE_UNIQUE. Gets info on NFTs N through M on the list
// of NFTs associated with a given NON_FUNGIBLE_UNIQUE Token.
// Example: If there are 10 NFTs issued, having start=0 and end=5 will query for the first 5 NFTs.
// Querying +all 10 NFTs will require start=0 and end=10
//
// INVALID_QUERY_RANGE response code will be returned if:
// 1) Start > End
// 2) Start and End indices are non-positive
// 3) Start and End indices are out of boundaries for the retrieved nft list
// 4) The range between Start and End is bigger than the global dynamic property for maximum query
// range
//
// NOT_SUPPORTED response code will be returned if the queried token is of type FUNGIBLE_COMMON
//
// INVALID_TOKEN_ID response code will be returned if the queried token does not exist
type TokenGetNftInfosQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard info sent from client to node, including the signed payment, and what kind of
	// response is requested (cost, state proof, both, or neither).
	Header *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// The ID of the token for which information is requested
	TokenID *common.TokenID `protobuf:"bytes,2,opt,name=tokenID,proto3" json:"tokenID,omitempty"`
	// *
	// Specifies the start index (inclusive) of the range of NFTs to query for. Value must be in the
	// range [0; ownedNFTs-1]
	Start int64 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	// *
	// Specifies the end index (exclusive) of the range of NFTs to query for. Value must be in the
	// range (start; ownedNFTs]
	End           int64 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenGetNftInfosQuery) Reset() {
	*x = TokenGetNftInfosQuery{}
	mi := &file_token_get_nft_infos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenGetNftInfosQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenGetNftInfosQuery) ProtoMessage() {}

func (x *TokenGetNftInfosQuery) ProtoReflect() protoreflect.Message {
	mi := &file_token_get_nft_infos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenGetNftInfosQuery.ProtoReflect.Descriptor instead.
func (*TokenGetNftInfosQuery) Descriptor() ([]byte, []int) {
	return file_token_get_nft_infos_proto_rawDescGZIP(), []int{0}
}

func (x *TokenGetNftInfosQuery) GetHeader() *QueryHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TokenGetNftInfosQuery) GetTokenID() *common.TokenID {
	if x != nil {
		return x.TokenID
	}
	return nil
}

func (x *TokenGetNftInfosQuery) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TokenGetNftInfosQuery) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type TokenGetNftInfosResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard response from node to client, including the requested fields: cost, or state proof,
	// or both, or neither
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// The Token with type NON_FUNGIBLE that this record is for
	TokenID *common.TokenID `protobuf:"bytes,2,opt,name=tokenID,proto3" json:"tokenID,omitempty"`
	// *
	// List of NFTs associated to the specified token
	Nfts          []*TokenNftInfo `protobuf:"bytes,3,rep,name=nfts,proto3" json:"nfts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenGetNftInfosResponse) Reset() {
	*x = TokenGetNftInfosResponse{}
	mi := &file_token_get_nft_infos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenGetNftInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenGetNftInfosResponse) ProtoMessage() {}

func (x *TokenGetNftInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_get_nft_infos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenGetNftInfosResponse.ProtoReflect.Descriptor instead.
func (*TokenGetNftInfosResponse) Descriptor() ([]byte, []int) {
	return file_token_get_nft_infos_proto_rawDescGZIP(), []int{1}
}

func (x *TokenGetNftInfosResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TokenGetNftInfosResponse) GetTokenID() *common.TokenID {
	if x != nil {
		return x.TokenID
	}
	return nil
}

func (x *TokenGetNftInfosResponse) GetNfts() []*TokenNftInfo {
	if x != nil {
		return x.Nfts
	}
	return nil
}

var File_token_get_nft_infos_proto protoreflect.FileDescriptor

const file_token_get_nft_infos_proto_rawDesc = "" +
	"\n" +
	"\x19token_get_nft_infos.proto\x12\x05proto\x1a\x11basic_types.proto\x1a\x18token_get_nft_info.proto\x1a\x12query_header.proto\x1a\x15response_header.proto\"\x95\x01\n" +
	"\x15TokenGetNftInfosQuery\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.proto.QueryHeaderR\x06header\x12(\n" +
	"\atokenID\x18\x02 \x01(\v2\x0e.proto.TokenIDR\atokenID\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x03R\x03end\"\x9c\x01\n" +
	"\x18TokenGetNftInfosResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.proto.ResponseHeaderR\x06header\x12(\n" +
	"\atokenID\x18\x02 \x01(\v2\x0e.proto.TokenIDR\atokenID\x12'\n" +
	"\x04nfts\x18\x03 \x03(\v2\x13.proto.TokenNftInfoR\x04nftsBZ\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01Z2github.com/cordialsys/hedera-protobufs-go/servicesb\x06proto3"

var (
	file_token_get_nft_infos_proto_rawDescOnce sync.Once
	file_token_get_nft_infos_proto_rawDescData []byte
)

func file_token_get_nft_infos_proto_rawDescGZIP() []byte {
	file_token_get_nft_infos_proto_rawDescOnce.Do(func() {
		file_token_get_nft_infos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_get_nft_infos_proto_rawDesc), len(file_token_get_nft_infos_proto_rawDesc)))
	})
	return file_token_get_nft_infos_proto_rawDescData
}

var file_token_get_nft_infos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_token_get_nft_infos_proto_goTypes = []any{
	(*TokenGetNftInfosQuery)(nil),    // 0: proto.TokenGetNftInfosQuery
	(*TokenGetNftInfosResponse)(nil), // 1: proto.TokenGetNftInfosResponse
	(*QueryHeader)(nil),              // 2: proto.QueryHeader
	(*common.TokenID)(nil),           // 3: proto.TokenID
	(*ResponseHeader)(nil),           // 4: proto.ResponseHeader
	(*TokenNftInfo)(nil),             // 5: proto.TokenNftInfo
}
var file_token_get_nft_infos_proto_depIdxs = []int32{
	2, // 0: proto.TokenGetNftInfosQuery.header:type_name -> proto.QueryHeader
	3, // 1: proto.TokenGetNftInfosQuery.tokenID:type_name -> proto.TokenID
	4, // 2: proto.TokenGetNftInfosResponse.header:type_name -> proto.ResponseHeader
	3, // 3: proto.TokenGetNftInfosResponse.tokenID:type_name -> proto.TokenID
	5, // 4: proto.TokenGetNftInfosResponse.nfts:type_name -> proto.TokenNftInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_token_get_nft_infos_proto_init() }
func file_token_get_nft_infos_proto_init() {
	if File_token_get_nft_infos_proto != nil {
		return
	}
	file_token_get_nft_info_proto_init()
	file_query_header_proto_init()
	file_response_header_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_get_nft_infos_proto_rawDesc), len(file_token_get_nft_infos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_get_nft_infos_proto_goTypes,
		DependencyIndexes: file_token_get_nft_infos_proto_depIdxs,
		MessageInfos:      file_token_get_nft_infos_proto_msgTypes,
	}.Build()
	File_token_get_nft_infos_proto = out.File
	file_token_get_nft_infos_proto_goTypes = nil
	file_token_get_nft_infos_proto_depIdxs = nil
}
