//*
// # Block Stream Info
// Information stored in consensus state at the beginning of each block to
// record the status of the immediately prior block.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: state/blockstream/block_stream_info.proto

package blockstream

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A message stored in state to maintain block stream parameters.<br/>
// Nodes use this information for three purposes.
//  1. To maintain hash chain continuity at restart and reconnect boundaries.
//  1. To store historical hashes for implementation of the EVM `BLOCKHASH`
//     and `PREVRANDAO` opcodes.
//  1. To track the amount of consensus time that has passed between blocks.
//
// This value MUST be updated for every block.<br/>
// This value MUST be transmitted in the "state changes" section of
// _each_ block, but MUST be updated at the beginning of the _next_ block.<br/>
// This value SHALL contain the block hash up to, and including, the
// immediately prior completed block.
type BlockStreamInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A block number.<br/>
	// This is the current block number.
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// *
	// A consensus time for the current block.<br/>
	// This is the _first_ consensus time in the current block, and
	// is used to determine if this block was the first across an
	// important boundary in consensus time, such as UTC midnight.
	// This may also be used to purge entities expiring between the last
	// block time and this time.
	BlockTime *common.Timestamp `protobuf:"bytes,2,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	// *
	// A concatenation of hash values.<br/>
	// This combines several trailing output block item hashes and
	// is used as a seed value for a pseudo-random number generator.<br/>
	// This is also requiried to implement the EVM `PREVRANDAO` opcode.
	TrailingOutputHashes []byte `protobuf:"bytes,3,opt,name=trailing_output_hashes,json=trailingOutputHashes,proto3" json:"trailing_output_hashes,omitempty"`
	// *
	// A concatenation of hash values.<br/>
	// This field combines up to 256 trailing block hashes.
	// <p>
	// If this message is for block number N, then the earliest available
	// hash SHALL be for block number N-256.<br/>
	// The latest available hash SHALL be for block N-1.<br/>
	// This is REQUIRED to implement the EVM `BLOCKHASH` opcode.
	TrailingBlockHashes []byte `protobuf:"bytes,4,opt,name=trailing_block_hashes,json=trailingBlockHashes,proto3" json:"trailing_block_hashes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BlockStreamInfo) Reset() {
	*x = BlockStreamInfo{}
	mi := &file_state_blockstream_block_stream_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockStreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockStreamInfo) ProtoMessage() {}

func (x *BlockStreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_state_blockstream_block_stream_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockStreamInfo.ProtoReflect.Descriptor instead.
func (*BlockStreamInfo) Descriptor() ([]byte, []int) {
	return file_state_blockstream_block_stream_info_proto_rawDescGZIP(), []int{0}
}

func (x *BlockStreamInfo) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockStreamInfo) GetBlockTime() *common.Timestamp {
	if x != nil {
		return x.BlockTime
	}
	return nil
}

func (x *BlockStreamInfo) GetTrailingOutputHashes() []byte {
	if x != nil {
		return x.TrailingOutputHashes
	}
	return nil
}

func (x *BlockStreamInfo) GetTrailingBlockHashes() []byte {
	if x != nil {
		return x.TrailingBlockHashes
	}
	return nil
}

var File_state_blockstream_block_stream_info_proto protoreflect.FileDescriptor

const file_state_blockstream_block_stream_info_proto_rawDesc = "" +
	"\n" +
	")state/blockstream/block_stream_info.proto\x12&com.hedera.hapi.node.state.blockstream\x1a\x0ftimestamp.proto\"\xcf\x01\n" +
	"\x0fBlockStreamInfo\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12/\n" +
	"\n" +
	"block_time\x18\x02 \x01(\v2\x10.proto.TimestampR\tblockTime\x124\n" +
	"\x16trailing_output_hashes\x18\x03 \x01(\fR\x14trailingOutputHashes\x122\n" +
	"\x15trailing_block_hashes\x18\x04 \x01(\fR\x13trailingBlockHashesBl\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01ZDgithub.com/cordialsys/hedera-protobufs-go/services/state/blockstreamb\x06proto3"

var (
	file_state_blockstream_block_stream_info_proto_rawDescOnce sync.Once
	file_state_blockstream_block_stream_info_proto_rawDescData []byte
)

func file_state_blockstream_block_stream_info_proto_rawDescGZIP() []byte {
	file_state_blockstream_block_stream_info_proto_rawDescOnce.Do(func() {
		file_state_blockstream_block_stream_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_blockstream_block_stream_info_proto_rawDesc), len(file_state_blockstream_block_stream_info_proto_rawDesc)))
	})
	return file_state_blockstream_block_stream_info_proto_rawDescData
}

var file_state_blockstream_block_stream_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_blockstream_block_stream_info_proto_goTypes = []any{
	(*BlockStreamInfo)(nil),  // 0: com.hedera.hapi.node.state.blockstream.BlockStreamInfo
	(*common.Timestamp)(nil), // 1: proto.Timestamp
}
var file_state_blockstream_block_stream_info_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.node.state.blockstream.BlockStreamInfo.block_time:type_name -> proto.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_state_blockstream_block_stream_info_proto_init() }
func file_state_blockstream_block_stream_info_proto_init() {
	if File_state_blockstream_block_stream_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_blockstream_block_stream_info_proto_rawDesc), len(file_state_blockstream_block_stream_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_blockstream_block_stream_info_proto_goTypes,
		DependencyIndexes: file_state_blockstream_block_stream_info_proto_depIdxs,
		MessageInfos:      file_state_blockstream_block_stream_info_proto_msgTypes,
	}.Build()
	File_state_blockstream_block_stream_info_proto = out.File
	file_state_blockstream_block_stream_info_proto_goTypes = nil
	file_state_blockstream_block_stream_info_proto_depIdxs = nil
}
