//*
// # Block Stream
// The base element of the block stream _at rest_.
// A `Block` contains a record of all transactions, results, and outputs for
// a block in the chain. Each `Block` also contains a state proof for
// validation and a header with version and algorithm information.
//
// Block entries are not designed for streaming, but for storing blocks in
// persistent storage, verifying block stream data, and as query responses
// when a block is requested from a block node.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/block.proto

package stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A single complete Hedera block chain block.
//
// This is a single block structure and SHALL NOT represent the primary
// mechanism to transmit a block stream.<br/>
// The primary mechanism for transmitting block stream data SHALL be to
// stream individual block items to the block node(s).<br/>
// The only delimiter between blocks when streamed SHALL be the `BlockHeader`
// item and `BlockProof` item.
//
// This block SHALL be verifiable as correct using only data in the block,
// including the `BlockProof`, and public keys for the consensus nodes.
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A list of items that, together, make up this block.
	// <p>
	// This list SHALL begin with a `BlockHeader`.<br/>
	// This list SHALL end with a `BlockProof`.<br/>
	// Items in this list SHALL be in exactly the same order produced by
	// consensus.<br/>
	// Items in this list MAY be filtered, if so requested.<br/>
	// If this list is filtered, removed items SHALL be replaced with
	// `FilteredBlockItem` entries.<br/>
	Items         []*BlockItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_stream_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_stream_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_stream_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetItems() []*BlockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_stream_block_proto protoreflect.FileDescriptor

const file_stream_block_proto_rawDesc = "" +
	"\n" +
	"\x12stream/block.proto\x12\x1ccom.hedera.hapi.block.stream\x1a\x17stream/block_item.proto\"F\n" +
	"\x05Block\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.com.hedera.hapi.block.stream.BlockItemR\x05itemsB_\n" +
	"#com.hedera.hapi.block.stream.protocP\x01Z6github.com/cordialsys/hedera-protobufs-go/block/streamb\x06proto3"

var (
	file_stream_block_proto_rawDescOnce sync.Once
	file_stream_block_proto_rawDescData []byte
)

func file_stream_block_proto_rawDescGZIP() []byte {
	file_stream_block_proto_rawDescOnce.Do(func() {
		file_stream_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_block_proto_rawDesc), len(file_stream_block_proto_rawDesc)))
	})
	return file_stream_block_proto_rawDescData
}

var file_stream_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stream_block_proto_goTypes = []any{
	(*Block)(nil),     // 0: com.hedera.hapi.block.stream.Block
	(*BlockItem)(nil), // 1: com.hedera.hapi.block.stream.BlockItem
}
var file_stream_block_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.block.stream.Block.items:type_name -> com.hedera.hapi.block.stream.BlockItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stream_block_proto_init() }
func file_stream_block_proto_init() {
	if File_stream_block_proto != nil {
		return
	}
	file_stream_block_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_block_proto_rawDesc), len(file_stream_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_block_proto_goTypes,
		DependencyIndexes: file_stream_block_proto_depIdxs,
		MessageInfos:      file_stream_block_proto_msgTypes,
	}.Build()
	File_stream_block_proto = out.File
	file_stream_block_proto_goTypes = nil
	file_stream_block_proto_depIdxs = nil
}
