//*
// # Record File Block
// This block carries the data from "record stream" and "sidecar"
// files that preceded the block stream. Record blocks are full blocks,
// not block items, but do not have a block header or block proof.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: stream/record_file_item.proto

package stream

import (
	common "github.com/cordialsys/hedera-protobufs-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A Block Item for record files.
//
// A `RecordFileItem` contains data produced before the innovation of the
// Block Stream, when data was stored in files and validated by individual
// signature files rather than a block proof.<br/>
// This item enables a single format, the Block Stream, to carry both
// historical and current data; eliminating the need to search two sources for
// block and block chain data.<br/>
// Any block containing this item requires special handling.
//   - The block SHALL NOT have a `BlockHeader`.
//   - The block SHALL NOT have a `BlockProof`.
//   - The block SHALL contain _exactly one_ `RecordFileItem`.
//   - The block SHALL NOT contain any item other than a `RecordFileItem`.
//   - The content of the `RecordFileItem` MUST be validated using the
//     signature data and content provided herein according to the
//     process used for Record Files prior to the creation of Block Stream.
//   - This block item only replaces the requirement to read several
//     individual files from cloud storage services.
type RecordFileItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The block number of this block.
	// <p>
	// This value MUST be exactly `1` more than the previous block.<br/>
	// Client systems SHOULD optimistically reject any block with a gap or
	// reverse in `number` sequence, and MAY assume the block stream has
	// encountered data loss, data corruption, or unauthorized modification.
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// *
	// The consensus time the record file was produced for.<br/>
	// This comes from the record file name.
	CreationTime *common.Timestamp `protobuf:"bytes,2,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	// *
	// The contents of a record file.<br/>
	// The first 4 bytes are a 32bit int little endian version number.
	// The versions that existed are 2,3,5 and 6.
	RecordFileContents []byte `protobuf:"bytes,3,opt,name=record_file_contents,json=recordFileContents,proto3" json:"record_file_contents,omitempty"`
	// *
	// The contents of sidecar files for this block.<br/>
	// Each block can have zero or more sidecar files.
	SidecarFileContents [][]byte `protobuf:"bytes,4,rep,name=sidecar_file_contents,json=sidecarFileContents,proto3" json:"sidecar_file_contents,omitempty"`
	// *
	// A hash algorithm.<br/>
	// This is the algorithm used to hash the block.
	// <p>
	// This SHOULD always be `SHA2_384`.
	HashAlgorithm common.BlockHashAlgorithm `protobuf:"varint,5,opt,name=hash_algorithm,json=hashAlgorithm,proto3,enum=proto.BlockHashAlgorithm" json:"hash_algorithm,omitempty"`
	// *
	// A collection of RSA signatures from consensus nodes.<br/>
	// These signatures validate the hash of the record_file_contents field.
	RecordFileHashSignatures [][]byte `protobuf:"bytes,6,rep,name=record_file_hash_signatures,json=recordFileHashSignatures,proto3" json:"record_file_hash_signatures,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RecordFileItem) Reset() {
	*x = RecordFileItem{}
	mi := &file_stream_record_file_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFileItem) ProtoMessage() {}

func (x *RecordFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_stream_record_file_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFileItem.ProtoReflect.Descriptor instead.
func (*RecordFileItem) Descriptor() ([]byte, []int) {
	return file_stream_record_file_item_proto_rawDescGZIP(), []int{0}
}

func (x *RecordFileItem) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *RecordFileItem) GetCreationTime() *common.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *RecordFileItem) GetRecordFileContents() []byte {
	if x != nil {
		return x.RecordFileContents
	}
	return nil
}

func (x *RecordFileItem) GetSidecarFileContents() [][]byte {
	if x != nil {
		return x.SidecarFileContents
	}
	return nil
}

func (x *RecordFileItem) GetHashAlgorithm() common.BlockHashAlgorithm {
	if x != nil {
		return x.HashAlgorithm
	}
	return common.BlockHashAlgorithm(0)
}

func (x *RecordFileItem) GetRecordFileHashSignatures() [][]byte {
	if x != nil {
		return x.RecordFileHashSignatures
	}
	return nil
}

var File_stream_record_file_item_proto protoreflect.FileDescriptor

const file_stream_record_file_item_proto_rawDesc = "" +
	"\n" +
	"\x1dstream/record_file_item.proto\x12\x1ccom.hedera.hapi.block.stream\x1a\x11basic_types.proto\x1a\x0ftimestamp.proto\"\xc6\x02\n" +
	"\x0eRecordFileItem\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x125\n" +
	"\rcreation_time\x18\x02 \x01(\v2\x10.proto.TimestampR\fcreationTime\x120\n" +
	"\x14record_file_contents\x18\x03 \x01(\fR\x12recordFileContents\x122\n" +
	"\x15sidecar_file_contents\x18\x04 \x03(\fR\x13sidecarFileContents\x12@\n" +
	"\x0ehash_algorithm\x18\x05 \x01(\x0e2\x19.proto.BlockHashAlgorithmR\rhashAlgorithm\x12=\n" +
	"\x1brecord_file_hash_signatures\x18\x06 \x03(\fR\x18recordFileHashSignaturesB_\n" +
	"#com.hedera.hapi.block.stream.protocP\x01Z6github.com/cordialsys/hedera-protobufs-go/block/streamb\x06proto3"

var (
	file_stream_record_file_item_proto_rawDescOnce sync.Once
	file_stream_record_file_item_proto_rawDescData []byte
)

func file_stream_record_file_item_proto_rawDescGZIP() []byte {
	file_stream_record_file_item_proto_rawDescOnce.Do(func() {
		file_stream_record_file_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_record_file_item_proto_rawDesc), len(file_stream_record_file_item_proto_rawDesc)))
	})
	return file_stream_record_file_item_proto_rawDescData
}

var file_stream_record_file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stream_record_file_item_proto_goTypes = []any{
	(*RecordFileItem)(nil),         // 0: com.hedera.hapi.block.stream.RecordFileItem
	(*common.Timestamp)(nil),       // 1: proto.Timestamp
	(common.BlockHashAlgorithm)(0), // 2: proto.BlockHashAlgorithm
}
var file_stream_record_file_item_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.block.stream.RecordFileItem.creation_time:type_name -> proto.Timestamp
	2, // 1: com.hedera.hapi.block.stream.RecordFileItem.hash_algorithm:type_name -> proto.BlockHashAlgorithm
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stream_record_file_item_proto_init() }
func file_stream_record_file_item_proto_init() {
	if File_stream_record_file_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_record_file_item_proto_rawDesc), len(file_stream_record_file_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_record_file_item_proto_goTypes,
		DependencyIndexes: file_stream_record_file_item_proto_depIdxs,
		MessageInfos:      file_stream_record_file_item_proto_msgTypes,
	}.Build()
	File_stream_record_file_item_proto = out.File
	file_stream_record_file_item_proto_goTypes = nil
	file_stream_record_file_item_proto_depIdxs = nil
}
